### PR TITLE
Update tasks-tracker (Leagues 5 prep)

### PR DESCRIPTION
**Pull request by tylerthardy**
Relevance:
This PR lets us handle League updates going forward without having to update the plugin. This includes configuring filters for task data. The plugin is essentially driven by our [task-json-store](https://github.com/osrs-reldo/task-json-store)

Changes:
- Removed all hard-coded task data
- Refactored task services to pull all task data from [task-json-store](https://github.com/osrs-reldo/task-json-store) and Client structs
- Refactored filters to pull from [task-json-store](https://github.com/osrs-reldo/task-json-store)

image

### CODE REVIEW

**Comment by LlemonDuck** [comment]
btw you're likely to receive a much quicker review if you can remove the new dependency on assistedinject

**Comment by tylerthardy** [comment]
> btw you're likely to receive a much quicker review if you can remove the new dependency on assistedinject

Feeling heroic enough to review? Removed it & tested

**Comment by LlemonDuck** [comment]
You have a number of InputStreamReaders and such that aren't being closed. You should wrap them in a try-with-resources block

**Comment by tylerthardy** [comment]
Here's a diff for the latest update
https://github.com/osrs-reldo/tasks-tracker-plugin/compare/a32f8deb2dcf3ff94cc65eff00765d9397fbd10f...osrs-reldo:2bc27e069d2ef8966c28a2acc988c66104392570

**Pull request merged**
