### PR TITLE
Update inventory-count

### PR DESCRIPTION
**Pull request by zenrion**

### CODE REVIEW

**Comment by Nightfirecat** [comment]
You should add `authors=robrichardson13,Zenrion` to this file so the bot doesn't add the non-author plugin change label.

**Comment by YvesW** [comment]
@robrichardson13 are you okay with the author change/addition?

**Comment by zenrion** [comment]
> @robrichardson13 are you okay with the author change/addition?

He added me as a contributor for plugin repository this morning, but we can wait for his reply. No problem.

**Comment by robrichardson13** [comment]
> @robrichardson13 are you okay with the author change/addition?

Yeah looks good to me!

**Review by iProdigy — APPROVED** [review]

**Review by pajlada — APPROVED** [review]

**Pull request merged**
