### PR TITLE
rep link created

### PR DESCRIPTION
**Pull request by chrihb**
Tracks average drop rates and contribution at Nex

### CODE REVIEW

**Comment by Worley03** [comment]
I was just about to publish similar plugin. Don't want to crowd the plugin hub, so do you mind looking over mine, and I'll look over yours? We can maybe we can pull together and make something even better? https://github.com/Worley03/nex-droprate-calculator

**Comment by chrihb** [comment]
> I was just about to publish similar plugin. Don't want to crowd the plugin hub, so do you mind looking over mine, and I'll look over yours? We can maybe we can pull together and make something even better? https://github.com/Worley03/nex-droprate-calculator
> 
> Mine currently tracks the drop rate and dynamically shows changes, would you mine if I add your Overlay onto mine to show a dynamically changing drop rate? (Mine uses a panel to give more details) I think mine has a few more features, as well as MVP bonus, averages across runs, etc..

Hi!

This was just a little sideproject to see how making plugins for runelite works. If you wanna use the overlay, go ahead! Figured it takes up less screen real-estate than a whole panel. 

Mine only show the average across runs for the session, so yours is definetly more fleshed out! I wasn't really gonna submit it at first, but figured I might as well try to see how it works!

**Comment by Worley03** [comment]
> > I should be done with the changes tomorrow. Take a look at my repo and see what you think. https://github.com/Worley03/nex-droprate-calculator
> 
> Looks good as far as i can tell!
> 
> I do think the idea itself can be applied to other groupbosses in the game though, to make a universal plugin that works with the nightmare, hueycoatl, etc aswell. That was the original thought atleast :)

That's a great idea, should be fairly simple to do too! I'll look into it later this week. Feel free to fork my repo and make it yourself tho!

**Comment by chrihb** [comment]
> > > I should be done with the changes tomorrow. Take a look at my repo and see what you think. https://github.com/Worley03/nex-droprate-calculator
> > 
> > 
> > Looks good as far as i can tell!
> > I do think the idea itself can be applied to other groupbosses in the game though, to make a universal plugin that works with the nightmare, hueycoatl, etc aswell. That was the original thought atleast :)
> 
> That's a great idea, should be fairly simple to do too! I'll look into it later this week. Feel free to fork my repo and make it yourself too!

Might have a look at it later this week if I have the time.

But as for this plugin, should I just close the pull request? Again, not a 100% sure how this works haha

**Comment by Worley03** [comment]
Yup, just close it!

**Pull request closed without merging**
