### PR TITLE
Combat Timer

### PR DESCRIPTION
**Pull request by JohnMichaelRouth**
A plugin that starts a timer whenever a certain sound effect plays. You can make the overlay panel flash after a certain amount of seconds. The overlay panel disappears after you get too far away or perform a certain action.

### CODE REVIEW

**Comment by Bram91** [comment]
This plugin seems to go against: https://secure.runescape.com/m=news/third-party-client-guidelines?oldschool=1

Specifically:
> Indicates the time where a boss mechanic may start or end

> Adds additional visual or audio indicators of a boss mechanic except in cases where this is a manually triggered external helper.

**Comment by JohnMichaelRouth** [comment]
> This plugin seems to go against: https://secure.runescape.com/m=news/third-party-client-guidelines?oldschool=1
> 
> Specifically:
> 
> > Indicates the time where a boss mechanic may start or end
> 
> > Adds additional visual or audio indicators of a boss mechanic except in cases where this is a manually triggered external helper.

Should I remove the default config? All this plugin is doing is starting a timer and flashing a box

**Comment by JohnMichaelRouth** [comment]
I made this because it was tedious to manually start and stop a timer, this doesn't have any logic specific to any boss mechanics
Do I need to remove parts of this to be compliant with the rules?

**Comment by Nightfirecat** [comment]
The issue is that it is trivial to go to a boss, find the sound ID attached to certain mechanics, and set up delayed alerts/triggers for when the action needs to be reacted to. This was recently addressed for the Watchdog plugin in #5829 by disabling such alerts in boss regions/raids. If the same change is applied here, that would make it allowable in my eyes.

**Comment by raiyni** [comment]
Closing based on guidelines.

**Pull request closed without merging**
