### PR TITLE
Create morghttpclient

### PR DESCRIPTION
**Pull request by MorgApps**
morghttpclient Plugin Saves data into the local host on port 8081 url for player's stats (xp gained, skill level and experience points total), also captures total health and health remaining, run energy, the animation id useful tracking if interacting with objects, if in combat the name of the npc and its health, logs world location, local location, camera position and where the mouse is located:

### CODE REVIEW

**Comment by Nightfirecat** [comment]
You've forgotten to set both your repository URL and commit hash.

**Comment by MorgApps** [comment]
morghttpclient Plugin Saves data into the local host on port 8081 url for player's stats (xp gained, skill level and experience points total), also captures total health and health remaining, run energy, the animation id useful tracking if interacting with objects, if in combat the name of the npc and its health, logs world location, local location, camera position and where the mouse is located. Updated commit hash

**Comment by MorgApps** [comment]
> You've forgotten to set both your repository URL and commit hash.

@Nightfirecat is this g2g?

**Comment by MorgApps** [comment]
@Nightfirecat  fixed the issue in runelite-plugin.properties
changed: plugins=com.morghttpclient.HttpServerPlugi
to: plugins=com.morghttpclient.HttpServerPlugin

**Comment by MorgApps** [comment]
@Nightfirecat - fixed added license - BSD 2-Clause License

**Comment by Nightfirecat** [comment]
Don't use `enabledByDefault = false`, it's confusing for users to install a plugin which isn't turned on by default: <https://github.com/MorgApps/morghttpclient/blob/09be5164987e7f37d48bf2f14466d6d9d478b694/src/main/java/com/morghttpclient/HttpServerPlugin.java#L31>

**Comment by MorgApps** [comment]
@Nightfirecat changed enabledByDefault = false to: 
enabledByDefault = true

**Pull request merged**
