### PR TITLE
Create partyreadycheck

### PR DESCRIPTION
**Pull request by scainburger**
Display an alert and play a sound to check ready status of your party. Currently only works for ToB parties.

### CODE REVIEW

**Comment by raiyni** [comment]
Do not set `loadWhenOutdated` and `enabledByDefault`

**Comment by scainburger** [comment]
Done

**Comment by scainburger** [comment]
My bad, that @Extension annotation was left over from OpenOSRS development. Thanks for your patience :)

**Comment by scainburger** [comment]
My bad, that annotation was left over from development within another client. Thanks for your patience :)

**Pull request merged**
