### PR TITLE
Create nature-runecraft-utilities

### PR DESCRIPTION
**Pull request by alex-macm**
This plugin swaps the achivement diary cape left click option to teleport to Jarr when standing at the nature altar.

### CODE REVIEW

**Comment by YvesW** [comment]
What if you just left click to TP to Jarr, and shift-click to teleport to Kaleb, using MES?

**Comment by alex-macm** [comment]
> What if you just left click to TP to Jarr, and shift-click to teleport to Kaleb, using MES?

MES left click to kaleb, and then this overrides the left click at the altar to Jarr. no shift click required, for maximum reclined gaming.

**Comment by LlemonDuck** [comment]
Use a more specific config name that is less likely to conflict with other plugins (e.g. `naturerunecraftutilities`)

https://github.com/alex-macm/Nature-Runecrafting-Util/blob/820856abbc7491120431e4a6607e609dc9097e38/src/main/java/com/NatureRCUtil/NatureRCUtilConfig.java#L34

**Comment by alex-macm** [comment]
> Use a more specific config name that is less likely to conflict with other plugins (e.g. `naturerunecraftutilities`)
> 
> https://github.com/alex-macm/Nature-Runecrafting-Util/blob/820856abbc7491120431e4a6607e609dc9097e38/src/main/java/com/NatureRCUtil/NatureRCUtilConfig.java#L34

changed

**Comment by geheur** [comment]
Did you try getting this added to runecrafting utilities instead of as a standalone plugin? It feels like it would fit there perfectly.

**Pull request merged**
