### PR TITLE
Update Default Tab - v1.0.1

### PR DESCRIPTION
**Pull request by damencs**
- allows plugin functionality in the wilderness ... still restricted for PvP worlds

### CODE REVIEW

**Comment by Nightfirecat** [comment]
I'm a bit confused. Why is it enabled in the wilderness, but not PvP worlds? How is it slower than a keypress from the user?

**Comment by damencs** [comment]
> I'm a bit confused. Why is it enabled in the wilderness, but not PvP worlds? How is it slower than a keypress from the user?

@Nightfirecat - I guess we could enable it in PvP worlds as well. There's requests to be able to use this in the wilderness for alt'ing wilderness bosses but there's not really the same experience with PvP worlds - in my mind that is. - I guess if we enable it in Wildy, we could do the same for PvP worlds.

As for the delay, nevermind. I thought there was a more noticeable delay- but disregard that point.

**Comment by Nightfirecat** [comment]
If it has a couple of ticks delay for wildy/pvp, that's fine.

**Comment by damencs** [comment]
> If it has a couple of ticks delay for wildy/pvp, that's fine.

@Nightfirecat - Added a 3-tick delay and config option for swapping when in wilderness or pvp worlds.

**Pull request merged**
