### PR TITLE
ToB QoL - Plugin Release - v1.0.0

### PR DESCRIPTION
**Pull request by damencs**
Provides Quality of Life Enhancements to Theatre of Blood will fitting into existing 3rd Party Client Guidelines to the best of RL Maintainer's and I's understanding of the said guidelines.

### CODE REVIEW

**Comment by LlemonDuck** [comment]
Missing LICENSE

**Comment by damencs** [comment]
> Missing LICENSE

Yeah, I noticed this. 🚀 I realized I skipped an entire set of steps. 3AM getting making an impact right now, hah.

**Comment by Nightfirecat** [comment]
1. Please don't reflect into the client with ConfigReflectUtil. It's probably best to remove that class and functionality.
2. Both the Xarpus exhumed highlights and Verzik yellow pool highlights fall under this line in the statement: (For colorblindness purposes, it would be fine to recolor the yellow pool model to use a different color.)
  > * Anything that automatically indicates where to stand, or not to stand. This applies to only automatic indicators, and not tiles which have been manually marked.  
3. Xarpus "Sheesh" shouldn't play if ingame volume is muted. ie. it should only play as a replacement for the sound effect that would play normally.

**Comment by damencs** [comment]
> 1. Please don't reflect into the client with ConfigReflectUtil. It's probably best to remove that class and functionality.

This has been removed.

> 2. Both the Xarpus exhumed highlights and Verzik yellow pool highlights fall under this line in the statement: (For colorblindness purposes, it would be fine to recolor the yellow pool model to use a different color.)
> 
> > * Anything that automatically indicates where to stand, or not to stand. This applies to only automatic indicators, and not tiles which have been manually marked.

These have been removed.

> ~~3. Xarpus "Sheesh" shouldn't play if ingame volume is muted. ie. it should only play as a replacement for the sound effect that would play normally.~~

Discussed in GitHub to be removed from considerations.

**Pull request merged**
