### PR TITLE
Add new plugin: Walk here

### PR DESCRIPTION
**Pull request by Thource**
Adds a configurable keybind to make "walk here" left click.

### CODE REVIEW

**Comment by YvesW** [comment]
What is the use case for this? Is there anything that's not already covered by MES's shift click walk here settings?

**Comment by Thource** [comment]
> What is the use case for this? Is there anything that's not already covered by MES's shift click walk here settings?

This allows you to bind a separate key to walk through things, so that you don’t lose your swapped menu entries when you hold the walk here button.

I’ve been made aware that it’s possible to do this with custom entry swaps plugin in the config, but this is a zero setup required option.

**Comment by raiyni** [comment]
I don't really see the point in adding new plugins that can be a config option

**Comment by MESLewis** [comment]
As mentioned above this plugin is very similar to core functionality and also other popular hub plugins. If this functionality is something you would still like I suggest PRing to <https://runelite.net/plugin-hub/show/hotkeyable-menu-swaps>, since it fits with that plugins existing functionality.

**Pull request closed without merging**
