### PR TITLE
Update rl-weather

### PR DESCRIPTION
**Pull request by bogstandard**
Introduces real-world-location matching (optional)

### CODE REVIEW

**Comment by Nightfirecat** [comment]
You will need to follow [the Third party dependencies section of the README](https://github.com/runelite/plugin-hub#third-party-dependencies) to add your new dependencies.

**Comment by bogstandard** [comment]
Okay thanks, sorry gradle verification is new to me 😔

Would adding the following to [`package/verification-template/build.gradle`](https://github.com/runelite/plugin-hub/blob/master/package/verification-template/build.gradle), then running that command do the trick? These dependencies are those reported as failing on the [run error report](https://github.com/runelite/plugin-hub/runs/4685713960?check_suite_focus=true).

```
thirdParty("com.squareup.retrofit2:retrofit:2.9.0") {
   because "rl-weather"
}

thirdParty("com.squareup.retrofit2:converter-gson:2.9.0") {
   because "rl-weather"
}
```

If this pull request involves too many third-party dependencies I'm happy to remove & rework the new feature if needed.

**Comment by Nightfirecat** [comment]
Yup, that should do the trick.

**Comment by bogstandard** [comment]
Thanks, hopefully that's done it and it's only failing because of the need for manual review? 

Apologies for being a nuisance with this one! I should have done my homework beforehand..

**Comment by Nightfirecat** [comment]
It's failing because you added the dependencies to `build.gradle`, but didn't run `../gradlew --write-verification-metadata sha256` afterward to update the metadata file. I recommend looking at what other PRs which have made dependency changes look like to make sure yours looks similar.

**Comment by bogstandard** [comment]
Success!(?) Hopefully this time that's done it, big apologies for the very messy PR everyone. Misunderstanding on my side of things. 

Again, if the new deps aren't okay I'm happy to pull them out and rewrite and attempt without them.

**Comment by abextm** [comment]
it would really save me a lot of time if you just used okhttp + gson without retrofit since its a small change anyway

**Comment by bogstandard** [comment]
Understood, will adjust the code to use those.

**Comment by thyme4soup** [comment]
nice

**Comment by Nightfirecat** [comment]
You should use the client's OkHttpClient instead of creating your own. Additionally, you should set the user agent to include your plugin's name. (something like `RuneLite.USER_AGENT + " (rl-weather)"`)

**Comment by Nightfirecat** [comment]
@bogstandard I see this was updated in your repo recently to accommodate the client and user agent changes, can you update the hash in this PR to include those changes?

**Comment by bogstandard** [comment]
Hi @Nightfirecat that hash has now been bumped to include those latest changes to master. Cheers for your help & patience with this!

**Pull request merged**
