### PR TITLE
Update vengeance-helper

### PR DESCRIPTION
**Pull request by Th3mike**

### CODE REVIEW

**Comment by Th3mike** [comment]
some upgrades on that plugin

**Comment by YvesW** [comment]
Please keep it to 1 PR. You can keep pushing changes (updated commit hashes) to your pluginhub branch and it will update the PR.

**Comment by Felanbird** [comment]
Update your old PR, don't open new ones for additional changes.

**Comment by Th3mike** [comment]
> Update your old PR, don't open new ones for additional changes.

oh sorry guys i will do that

**Pull request closed without merging**
