### PR TITLE
Add Improvedattacktimer

### PR DESCRIPTION
**Pull request by Lexer747**
# Improved Attack Timer!

* Use target NPCs as attack detection - improving robustness between updates. Manual updates will still be needed for things which dynamically change attack speed.
* Use new ID lookup to detect 4 tick staffs
* Add many valarmore spec animation IDs (+ elder maul spec)
* Red Keris Detection for the slowed follow up attack
* Blood Moon set effect

### Other misc things:

* Java 11
* Issue template for missing weapons
* Add some missing license info

## Why not contribute to the existing plugin?

It's been March since a [pull](https://github.com/ngraves95/attacktimer/pull/42) request was raised to fix the sang and others, I thought instead of complaining on the github about wanting it merged (especially with all the Perilous moons bugs I also wanted to raise), why not just fork and fix it all myself. I really like seeing my attack cool down at bosses, helps alot of switches and positioning.

Plus I saw this as a good excuse to dip my toes into world contributing to Runelite, given how much I've used this client over the years, see how it all works and if some better solutions exist.

### CODE REVIEW

**Comment by raiyni** [comment]
Seeing as you are reusing everything about the plugin, we would rather you get added as a contributor to the current plugin's repository. If the author is awol after earnest attempts at contact, we will be able to transfer the plugin's url.

**Comment by Lexer747** [comment]
> Seeing as you are reusing everything about the plugin, we would rather you get added as a contributor to the current plugin's repository. 

Fair enough! I will make an earnest attempt to get my changes merged into thier repo first then.

> If the author is awol after earnest attempts at contact, we will be able to transfer the plugin's url.

Is there no option for a middle ground to give time for the original author to come back? Like `NPC Highlight` and `Better NPC Indicators`.

**Comment by Felanbird** [comment]
> Is there no option for a middle ground to give time for the original author to come back? Like `NPC Highlight` and `Better NPC Indicators`.

Yes of course, if the author comes back then we can just not transfer the plugin to you

**Comment by Lexer747** [comment]
With https://github.com/runelite/plugin-hub/pull/6223 - I will work on upstreaming all of my other fixes and improvements instead of putting continuing my fork. Would you like me to close this issue or leave it open?

**Comment by cdfisher** [comment]
> With #6223 - I will work on upstreaming all of my other fixes and improvements instead of putting continuing my fork. Would you like me to close this issue or leave it open?

If you're going to be contributing to another plugin instead of submitting this one, it's probably best to just close this PR

**Pull request closed without merging**
