### PR TITLE
Camdozaal v1.1 - Migrate Camdozaal plugin from old repo to new one.

### PR DESCRIPTION
**Pull request by TicTac7x**

### CODE REVIEW

**Comment by Hydrox6** [comment]
You should really just not change the plugin's name, leave it in the `camdozaal` file

**Comment by TicTac7x** [comment]
> You should really just not change the plugin's name, leave it in the `camdozaal` file

I would like to go forward with the name change.

**Comment by Adam-** [comment]
I too would prefer if it wasn't renamed. There is no reason to rename it and it just causes headaches

**Comment by abextm** [comment]
I've decided to disallow renames like this since it is entirely pointless. Do not rename the file in this repo

**Comment by TicTac7x** [comment]
As a sign of protest I have decided to request disabling this plugin

**Pull request merged**
