### PR TITLE
Create tictac7x-deposit-worn-items

### PR DESCRIPTION
**Pull request by TicTac7x**

### CODE REVIEW

**Comment by raiyni** [comment]
The bank plugin already does this?

**Comment by TicTac7x** [comment]
Yes, but it still opens the menu on left click, which i don't want to see. My plugin also adds lock icon to clearly see that left click is disabled, which the bank plugin does not do.

**Comment by tylerwgrass** [comment]
Your desired changes would make more sense as proposed to the bank plugin instead of creating a new plugin

**Comment by TicTac7x** [comment]
Maybe, but last time i opened PR for core plugin, the PR stayed idle for 2 years until it got rejected. Somif possible, I would like to go forward with this plugin.

**Pull request merged**
