### PR TITLE
Add damage counter plugin

### PR DESCRIPTION
**Pull request by 0anth**
This plugin tracks your damage done to boss monsters and after each kill, it writes a line in the chat with how much damage you did and what percentage that was of the total boss health.

### CODE REVIEW

**Comment by Nightfirecat** [comment]
The build is failing for this plugin

**Comment by 0anth** [comment]
> The build is failing for this plugin

I'm not sure why it's failing to build with Travis... it's building in IntelliJ without errors. Any idea why this might be?

**Comment by Adam-** [comment]
It looks like you forgot to commit at least the `DpsOverlay` class. Here is the build output https://travis-ci.org/github/runelite/plugin-hub/builds/739017825

**Comment by 0anth** [comment]
Facepalm on my behalf, it was late last night for me. It's now building correctly.

**Pull request merged**
