### PR TITLE
Create chat-filter-updater

### PR DESCRIPTION
**Pull request by Psicoses**
A plugin to automatically update runelite's chat filter regex. It pulls from a url after every plugin start and sets the chat filter's config to what's stored in the url.

### CODE REVIEW

**Comment by raiyni** [comment]
Inject our okhttp object and use that to fetch your url.

**Comment by Psicoses** [comment]
> Inject our okhttp object and use that to fetch your url.

Gotchya, done.

**Comment by raiyni** [comment]
Two more things:

* Use enqueue instead of execute so requests aren't on thread
*  If you care about saving the current chat filter a user has, it will be overwritten permanently if they toggle config settings in your plugin

**Comment by Psicoses** [comment]
Okay its queuing the request for the url now.

As for the config, it does store the user's regex as the plugin starts so that changes can be reverted by toggling. Changes are only permanently lost if the user restarts the client.

I added a warning to notify the user that the filter will be permanently overwritten, and any changes while the plugin is on will be lost.

Thank you for your patience and let me know if there is anything else.

**Pull request merged**
