### PR TITLE
Update wasted-bank-space

### PR DESCRIPTION
**Pull request by mcgeer**
Added Ability to not flag items, panel changes, ability to select new icons instead of the yield sign. Robes of Ruin and pride 2024 items added

### CODE REVIEW

**Comment by iProdigy** [comment]
For [`DelayedRunnable`](https://github.com/mcgeer/WastedBankSpace/compare/ccc5614f8e6c4037336fec1150e2c6e1df2cb049...mcgeer:24ed999f6c8f024bb0f3b860ddce65191563a8d2#diff-d4c8b694cdbc7ce5e2b269d0dd9165ace79f3c09e5fb23f891f40702ecc3b606R9), would it be possible to use runelite's `SharedExecutorService` instead? in java 11, each Timer results in a new thread created (while in java 8 all timers shared a single TimerThread)

**Review by iProdigy — DISMISSED** [review]

**Comment by mcgeer** [comment]
I can look into ScheduledExecutorService

**Comment by Felanbird** [comment]
@mcgeer This PR has a merge conflict now as I've gone ahead and reverted your plugin to the commit right before cat_h, that way it was not broken until this PR is approved & merged.

**Comment by raiyni** [comment]
What  are you doing?

**Comment by mcgeer** [comment]
> What are you doing?

My bad thought I could reopen now, use gerrit at work. Just made a new PR.

**Pull request closed without merging**
