### PR TITLE
Create fishing-notifier

### PR DESCRIPTION
**Pull request by Bram91**

### CODE REVIEW

**Comment by Nightfirecat** [comment]
Just to understand the use case here, is this just to have a separate notifier plugin with instant notifications instead of using the idle notifier plugin with a very short idle time?

**Comment by Broooklyn** [comment]
That is correct - Think Abex's Idle Notifier but for Fishing instead of Mining

**Comment by Bram91** [comment]
Yup that's correct

**Comment by Nightfirecat** [comment]
You must [license your repository](https://github.com/runelite/plugin-hub#licensing-your-repository).

**Comment by Bram91** [comment]
Oops 🙃  fixed now.

**Pull request merged**
