### PR TITLE
Update pet-to-npc-transmog

### PR DESCRIPTION
**Pull request by Tony905x**
Update 2.3 - bug fix for custom fields in panel

### CODE REVIEW

**Review by pajlada — DISMISSED** [review]
When choosing a preset then clicking "Enable Custom", it always fires the "Please provide NPC details or select a preset. Click 'Instructions' for help." dialog if you don't have a custom NPC saved yet

Not really blocking, plugin works as expected from my limited use of it

**Comment by iProdigy** [comment]
Could you use slf4j here instead of System.err https://github.com/Tony905x/pet-to-npc-transmog/blob/d1dffba29de7ef2831934a830ffd80153f96c93d/src/main/java/com/pettonpc/NpcFollowerPanel.java#L359

**Comment by Tony905x** [comment]
> Could you use slf4j here instead of System.err https://github.com/Tony905x/pet-to-npc-transmog/blob/d1dffba29de7ef2831934a830ffd80153f96c93d/src/main/java/com/pettonpc/NpcFollowerPanel.java#L359

I have updated it, I never used that before so let me know if any issues.  I also removed the error message pajlada was talking about

**Review by pajlada — APPROVED** [review]
Most use the `@Slf4j` annotation on the class rather than a LoggerFactory but I imagine it won't make a difference

**Review by pajlada — CHANGES_REQUESTED** [review]
You have an uncaught exception in your `updateFieldsWithDropdownData` function
```
java.lang.NumberFormatException: null
	at java.base/java.lang.Integer.parseInt(Integer.java:614)
	at java.base/java.lang.Integer.parseInt(Integer.java:770)
	at com.pettonpc.NpcFollowerPanel.updateFieldsWithDropdownData(NpcFollowerPanel.java:653)
	at com.pettonpc.NpcFollowerPlugin.panelChange(NpcFollowerPlugin.java:221)
	at com.pettonpc.NpcFollowerPanel.lambda$new$1(NpcFollowerPanel.java:232)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.JToggleButton$ToggleButtonModel.setPressed(JToggleButton.java:401)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6635)
```

which can also be triggered by changing the preset after having "Enable Custom" enabled
```
java.lang.NumberFormatException: null
	at java.base/java.lang.Integer.parseInt(Integer.java:614)
	at java.base/java.lang.Integer.parseInt(Integer.java:770)
	at com.pettonpc.NpcFollowerPanel.updateFieldsWithDropdownData(NpcFollowerPanel.java:653)
	at com.pettonpc.NpcFollowerPlugin.panelChange(NpcFollowerPlugin.java:221)
	at com.pettonpc.NpcFollowerPanel.lambda$new$0(NpcFollowerPanel.java:218)
	at java.desktop/javax.swing.JComboBox.fireActionEvent(JComboBox.java:1264)
	at java.desktop/javax.swing.JComboBox.setSelectedItem(JComboBox.java:589)
```

This is my plugin-related config:
```
petToNpcTransmog.asd_npcModelID6=19100
petToNpcTransmog.asd_npcModelID2=7049
petToNpcTransmog.asd_npcModelID3=7041
petToNpcTransmog.asd_npcModelID4=7057
petToNpcTransmog.asd_npcModelID5=2985
petToNpcTransmog.asd_npcModelID1=7034
petToNpcTransmog.asd_npcSpawnAnim=4
petToNpcTransmog.asd_npcXoffset=0
petToNpcTransmog.asd_npcYoffset=0
petToNpcTransmog.asd_npcStandingAnim=7861
petToNpcTransmog.asd_npcRadius=60
petToNpcTransmog.asd_npcModelID15=0
petToNpcTransmog.asd_npcModelID16=0
petToNpcTransmog.asd_npcModelID13=4
petToNpcTransmog.asd_npcModelID14=60
petToNpcTransmog.asd_npcModelID11=7861
petToNpcTransmog.asd_npcModelID12=2156
petToNpcTransmog.lastSelectedConfig=Wise Old Man
petToNpcTransmog.asd_npcWalkingAnim=2156
petToNpcTransmog.isCustomEnabled=false
petToNpcTransmog.savedConfigNames=asd
```

**Comment by Tony905x** [comment]
I cant seem to replicate this.  can you tell me how you were able to change the preset when enable custom is selected?  The preset dropdown should be greyed out whenever enable custom is checked

**Comment by pajlada** [comment]
> I cant seem to replicate this. can you tell me how you were able to change the preset when enable custom is selected? The preset dropdown should be greyed out whenever enable custom is checked

Not sure, I'm unable to reproduce now on a fresh config, so maybe it was an artifact of the old version, then running the new version

**Review by pajlada — APPROVED** [review]

**Review by iProdigy — APPROVED** [review]

**Pull request merged**
