### PR TITLE
Update tog-crowdsourcing: Add ping column

### PR DESCRIPTION
**Pull request by jcarbelbide**
Closes https://github.com/jcarbelbide/tog-crowdsourcing/issues/2

### CODE REVIEW

**Comment by Nightfirecat** [comment]
We don't want to add another plugin which is sending pings to every world, on top of the world hopper plugin. If displaying ping is a needed feature, we'd prefer to incorporate a change in core to expose that data from the world hopper plugin as a service.

**Comment by Nightfirecat** [comment]
There are a handful of services provided by core plugins, see `ClueScrollService`, `ItemStatChangesService`, `SlayerPluginService`, `XpTrackerService`, etc. You'd want to follow the way those services are implemented to enable sharing that data. I'd recommend discussing this in the #runelite or #development channels [of our Discord server](https://runelite.net/discord) if you have other questions or need direction. If written properly, I don't see any reason we'd turn down a pull request which would help the world hopper plugin open that data for other plugins to use--like I said, it would keep there from being cases where we double up on sending pings for multiple plugins to get the same data.

**Comment by jcarbelbide** [comment]
Perfect, I'll take a look at this, and I'll continue this conversation in the discord server. Thanks for the help!

**Comment by LlemonDuck** [comment]
closing as stale, feel free to re-open if you implement the above

**Pull request closed without merging**
