### PR TITLE
Create loot-lens

### PR DESCRIPTION
**Pull request by Zzeetaa**
a simple plugin which adds a sound effect from the content creator lens when opening chests in the gauntlet

### CODE REVIEW

**Comment by Zzeetaa** [comment]
consent

proof of permission

**Comment by iProdigy** [comment]
`LootConfig#greeting` is unused and you should not use `example` as the config group: https://github.com/Zzeetaa/loot/blob/f050d97ef33e682abd533d25a46dfa9098eb7598/src/main/java/com/loot/LootConfig.java#L7

<sup>perhaps the clip volume should be configurable via config</sup>

to read the wav resource, you should use `getResourceAsStream` because `new File("src/main/resources/sound/loot.wav")` will not work as explained here: https://github.com/runelite/plugin-hub?tab=readme-ov-file#plugin-resources

**Comment by LlemonDuck** [comment]
Marking as draft for now. Please make the requested changes, then mark the plugin as ready for review.

**Comment by MESLewis** [comment]
Closed at author request.

**Pull request closed without merging**
