### PR TITLE
Added ScapeCloud

### PR DESCRIPTION
**Pull request by austinbuckler**
ScapeCloud is an image upload service for Old School RuneScape. Instead of users images being saved to their local machine, they are uploaded to the cloud ready to be shared. We utilize metadata from the client to provide extra functionality about the image such as: Combat Level, Nearby Players, Total Level, Player Name, Account Type (Ironman), and more.

### CODE REVIEW

**Comment by Nightfirecat** [comment]
Can you make [the membership of scape-cloud](https://github.com/orgs/scape-cloud/people) display you as a public member? I see you've contributed to this repo, but I'd like to be sure that you have ownership or write privs for this org.

**Comment by austinbuckler** [comment]
> Can you make the membership of scape-cloud display you as a public member? I see you've contributed to this repo, but I'd like to be sure that you have ownership or write privs for this org.
Done

> The code LGTM, though you may want to avoid adding an identical screenshot button to what's present in the main client as it will likely cause confusion for some users.
Thats fair, I will make the change tonight :)

**Comment by raiyni** [comment]
Your warning should also include a mention about taking/uploading screenshots.

**Comment by austinbuckler** [comment]
> Your warning should also include a mention about taking/uploading screenshots.

Good catch! Updated 🤘🏻

**Comment by Nightfirecat** [comment]
LGTM. Did you want to make that screenshot button image change now or later?

**Comment by austinbuckler** [comment]
> LGTM. Did you want to make that screenshot button image change now or later?

I can take a stab at it right now, hopefully it won't take too long.

**Comment by austinbuckler** [comment]
I do plan on changing it completely, for now I've changed the color to distinguish it a bit from the default. I know this isn't exactly what you meant by change it. I'm not very good at pixel art and would rather submit a bunch of changes at once. Just know this will be one of the top priorities in the next update. 👍

**Pull request merged**
