### PR TITLE
Update spec-jingle

### PR DESCRIPTION
**Pull request by Servilabs**
update spec jingle to new version, which adds 8 new sounds and a new threshold section for values that only play when the spec reaches that exact value.

### CODE REVIEW

**Comment by tylerwgrass** [comment]
How is someone supposed to know how many sounds there are, what they are, and how to use them? 
I don't think someone reading the config is going to understand how to use this.

**Comment by Servilabs** [comment]
Thank you, noted, I have an instruction section to the config panel.

**Comment by iProdigy** [comment]
it's still unclear to users what sound id's 1-9 correspond to

**Comment by Servilabs** [comment]
I just looked for a bunch of different id's that might be good for notifications and somewhat different.

**Comment by Servilabs** [comment]
sound description has been added to the configuration

**Review by iProdigy — APPROVED** [review]
the game sound IDs (e.g., 3924) probably don't need to be in the instructions (more likely to confuse users)

regardless, LGTM (code could be optimized, but not a blocker)

**Review by tylerwgrass — APPROVED** [review]
some things to consider:
- The "how to" stuff would be good to also maybe have in the README
- if a user has a different sound set for both the threshold configs at the same threshold, the first sound is ignored, which might confuse people (no real suggestions here just fyi)

**Pull request merged**
