### PR TITLE
add help icons that link to pack sources, and add 11 new packs

### PR DESCRIPTION
**Pull request by TrevorMDev**

### CODE REVIEW

**Comment by TrevorMartz** [comment]
The diff seems to show existing packs have changed, those are ones I've added a helper link to. The tiles remain the same.

**Comment by TrevorMDev** [comment]
Thanks, I missed that tag

**Comment by raiyni** [comment]
This would much less annoying to review if you used json files in the resources folder

**Comment by TrevorMDev** [comment]
Sorry about that, I will look into converting to json. Thanks for the suggestion.

**Pull request merged**
