### PR TITLE
Watchdog v3.5.0

### PR DESCRIPTION
**Pull request by adamk33n3r**
Side panel priority config option
update inventory change alert to sum all items matched by regex

### CODE REVIEW

**Comment by adamk33n3r** [comment]
> You'll need to replace your `println` usage with a logger

Sorry, which are you talking about? I didn't add any println

**Comment by Bram91** [comment]
This one: https://github.com/adamk33n3r/runelite-watchdog/blob/1d495807d7a60e1afc89b7ae53229fc0d5cbcfba/src/main/java/com/adamk33n3r/runelite/watchdog/elevenlabs/ElevenLabs.java#L80

**Comment by Felanbird** [comment]
https://github.com/adamk33n3r/runelite-watchdog/blob/1d495807d7a60e1afc89b7ae53229fc0d5cbcfba/src/main/java/com/adamk33n3r/runelite/watchdog/elevenlabs/ElevenLabs.java#L80

We made the checker block any `println`'s to prevent logs with no info about what plugin is writing them

**Comment by adamk33n3r** [comment]
Oh shoot, over a year ago! Haha, ok no problem. I'll fix that up in a bit.

**Comment by adamk33n3r** [comment]
Should I also be removing the `e.printStackTrace()`?

**Comment by Felanbird** [comment]
> Should I also be removing the `e.printStackTrace()`?

Yes, since the checker is still mad about them https://github.com/runelite/plugin-hub/pull/7158/checks?check_run_id=34505515018

https://github.com/search?q=repo%3Aadamk33n3r%2Frunelite-watchdog%20e.printStackTrace&type=code

**Comment by adamk33n3r** [comment]
Funny that the checker mentions use of `java.lang.System.err` when there technically isn't :P but ok, I removed the rest of them!

**Comment by adamk33n3r** [comment]
Uhhh...looks like it's still telling me that?

**Pull request merged**
