### PR TITLE
Create odablock plugin

### PR DESCRIPTION
**Pull request by DapperMickie**
A sound plugin like c-engineers plugin but with many new ones added and of course the Odablock voice!

### CODE REVIEW

**Comment by Nightfirecat** [comment]
Do you have permission from odablock to use his voice clips?

**Comment by DapperMickie** [comment]
I do and I have proof if needed

**Comment by Felanbird** [comment]
> I do and I have proof if needed

It is needed yes

**Comment by DapperMickie** [comment]
Where do I provide it?

**Comment by Felanbird** [comment]
You can post it here, if it's a voice clip where he also included a bunch of person info for some reason, then you can join the [discord](https://runelite.net/discord/) and dm it to the bot 
image

**Comment by DapperMickie** [comment]
image

**Comment by Nightfirecat** [comment]
[Don't use the same icon as the C Engineer plugin.](https://github.com/DapperMickie/odablock-sounds/blob/92be9166029a276e0e7a8904e293499e5df96e82/icon.png)
LGTM otherwise

**Comment by DapperMickie** [comment]
I have updated the icon, thanks for checking the code out :)

**Pull request merged**
