### PR TITLE
Create player-notifier

### PR DESCRIPTION
**Pull request by jcarbelbide**
Created a plugin that turns the screen red when unknown players are nearby. Please let me know if there are any questions. 

Thank you for your time!

### CODE REVIEW

**Comment by abextm** [comment]
This is a rejected feature

**Comment by jcarbelbide** [comment]
> This is a rejected feature

Thanks for letting me know! Just so I and anyone else in the future that may try to implement this understands, by rejected feature, do you mean that it is against the rules for third party clients?

**Comment by Nightfirecat** [comment]
Rejected features are documented here: https://github.com/runelite/runelite/wiki/Rejected-or-Rolled-Back-Features

**Comment by jcarbelbide** [comment]
Thanks, abextm, Nightfirecat. It looks like this would most likely fall under PK/Skull Warnings, since this is a warning for potential PKing. 

Digging through this [link](https://github.com/runelite/runelite/issues?utf8=%E2%9C%93&q=label%3Awontfix), I also found these relevant conversations for anyone seeing this in the future: 
[7578](https://github.com/runelite/runelite/issues/7578)
[10244](https://github.com/runelite/runelite/issues/10244)
[Comment by Adam on Notifications during PvP](https://github.com/runelite/runelite/issues/7072#issuecomment-450448227)

**Pull request closed without merging**
