### PR TITLE
Fixed performance issue, added option to count full potions only

### PR DESCRIPTION
**Pull request by mrchooch**

### CODE REVIEW

**Comment by iProdigy** [comment]
Is changing the config group intentional? You will effectively be setting everyone on the default config

**Comment by mrchooch** [comment]
Oops, good catch

**Comment by iProdigy** [comment]
Could you also remove this unused field https://github.com/mrchooch/potion-bars/blob/dd2197a0b904c95ee46be67715288886865365d4/src/main/java/com/potionbar/PotionBarPlugin.java#L30 (also unnecessary given `@Slf4j`)

**Review by iProdigy — DISMISSED** [review]
final nit: could do `potionPanels.clear();` on plugin shutDown

**Review by iProdigy — APPROVED** [review]

**Review by tylerwgrass — APPROVED** [review]

**Pull request merged**
