### PR TITLE
Create visual-metronome-extended plugin.

### PR DESCRIPTION
**Pull request by fredolite**
Adds functionality similar to the visual-metronome plugin that lets you configure and switch between different tick cycles with a hotkey.

https://user-images.githubusercontent.com/107812648/174500100-194cb182-0490-4f7c-a0fc-afec935729a5.mp4

image

### CODE REVIEW

**Comment by Hydrox6** [comment]
This should probably just be an edit to the existing `visual-metronome` plugin, instead of a brand new plugin that essentially copies it.

**Comment by fredolite** [comment]
I looked into making these changes to the existing plugin but it looked like it would be a little messy vs a simplified version with just the functionality I needed.  

Feel free to close this PR if you want and I can reach out to the existing plugin's maintainer to see if we can work something out.

**Comment by Nightfirecat** [comment]
We'd appreciate at least reaching out to them and seeing if they would like to incorporate these changes instead of having a second plugin doing nearly the same thing. @vincent0955

**Comment by vincent0955** [comment]
> I looked into making these changes to the existing plugin but it looked like it would be a little messy vs a simplified version with just the functionality I needed.
> 
> Feel free to close this PR if you want and I can reach out to the existing plugin's maintainer to see if we can work something out.

hey, some people asked and were looking forward to this feature, idk if you still wanna work something out. But if you want to make a pull request ill merge it, or if not then I'll try to implement it.

**Comment by Nightfirecat** [comment]
Closing due to inactivity.

**Pull request closed without merging**
