### PR TITLE
Create regular expression item counter 

### PR DESCRIPTION
**Pull request by jammy-dodgers**
Sorry for duplicating this, Github didn't warn me that renaming the branch on my fork would automatically close the pull request. Couldn't find a way to change the PR to the newly renamed branch.

Counts the number of items in your inventory / equipped that matches regular expressions.
An example of a place where this is useful: 
You need 1250 more mole parts of either kind to finish making all your saradomin brews. 
You can match on "Mole (claw|skin)" and it will display the total number of things in your inventory that match the regex
(Though I didn't get a screenshot of that specific example, I'm sure you get the idea of it)

alt text

### CODE REVIEW

**Comment by raiyni** [comment]
Remove the `log.info` calls

**Comment by raiyni** [comment]
There's really no need for you to do this btw https://github.com/jammy-dodgers/item-counter/blob/b514be630d9ec95733c459d8f08951de02665360/src/main/java/cc/jambox/ItemCounterPlugin.java#L140

**Comment by jammy-dodgers** [comment]
> There's really no need for you to do this btw https://github.com/jammy-dodgers/item-counter/blob/b514be630d9ec95733c459d8f08951de02665360/src/main/java/cc/jambox/ItemCounterPlugin.java#L140

It's creating a type-safe generically typed array without compiler warnings. I don't think there are other ways to do this in Java because of type erasure

**Comment by raiyni** [comment]
I'm tell you that you don't need generics for two Item arrays.

**Comment by jammy-dodgers** [comment]
I was writing it with the intent of being reusable, but yeah I guess so

**Pull request merged**
