### PR TITLE
Add Scouting plugin

### PR DESCRIPTION
**Pull request by peanubnutter**
The Scouting plugin crowdsources various events as you encounter them, automatically reporting any enabled event types to the server. Currently only some Forestry events are supported.

### CODE REVIEW

**Comment by peanubnutter** [comment]
The current version of this plugin is made obsolete by https://secure.runescape.com/m=news/wrapping-up-forestry---changes--tweaks?oldschool=1

However, I planned to add some new event types in the future... So maybe I will just close this PR and open a new one later if/when I add new event types. Though it's also not clear when exactly the changes in the blog will be made. So the plugin could see some use for a short while.

**Comment by peanubnutter** [comment]
Let's still go ahead with this plugin since it will find some use before Jagex actually changes Forestry. Anything I can do to expedite review?

**Comment by Alexsuperfly** [comment]
Please use a more descriptive config group than just ["scouting"](https://github.com/peanubnutter/scoutingplugin/blob/58f2ce69525a2d0134f0d3fc4057939c8285ef37/src/main/java/com/scouting/ScoutingConfig.java#L7), such as perhaps "event-scouting" or "activity-scouting".
otherwise LGTM

**Comment by peanubnutter** [comment]
> Please use a more descriptive config group than just ["scouting"](https://github.com/peanubnutter/scoutingplugin/blob/58f2ce69525a2d0134f0d3fc4057939c8285ef37/src/main/java/com/scouting/ScoutingConfig.java#L7), such as perhaps "event-scouting" or "activity-scouting". otherwise LGTM

Will do. Just to be clear, must I only change the config group or also the plugin name and its documentation?

**Comment by Alexsuperfly** [comment]
> > Please use a more descriptive config group than just ["scouting"](https://github.com/peanubnutter/scoutingplugin/blob/58f2ce69525a2d0134f0d3fc4057939c8285ef37/src/main/java/com/scouting/ScoutingConfig.java#L7), such as perhaps "event-scouting" or "activity-scouting". otherwise LGTM
> 
> Will do. Just to be clear, must I only change the config group or also the plugin name and its documentation?

im ok with the name, but having a more descriptive one is always better, helps users know what plugin they're looking at when editing a config, and if theres an error would help identify it in a stacktrace too

**Comment by peanubnutter** [comment]
Feedback addressed. Ready to merge!


Update plugin name to Event Scouting; Fix Pheasant pet bug; Expose call URL override

Full Changes: https://github.com/peanubnutter/scoutingplugin/commit/cf200bdf9b0e055cc345e511e849cdf7342919aa

**Pull request merged**
