### PR TITLE
Update VoiceScape

### PR DESCRIPTION
**Pull request by derfurkan**
- Added icon
- Removed main server
- Fixed typo
- Added Push-To-Talk
- Added name hashing for security
- Added default servers
- Fixed bugs
- Added support for proxies
- Updated ReadMe Page

### CODE REVIEW

**Comment by derfurkan** [comment]
Ready to be reviewed

**Comment by derfurkan** [comment]
Ready to be reviewed

**Comment by derfurkan** [comment]
Ready to be reviewed

**Comment by Nightfirecat** [comment]
FYI, all hub PRs should be considered "ready to review" since we have no insight to your development process/conventions other than what is shown here. If something is submitted which turns out to not be ready for review, the PR should be closed or marked as draft instead of being left open.

**Comment by derfurkan** [comment]
> FYI, all hub PRs should always be considered "ready to review" since we have no insight to your development process/conventions other than what is shown here. If something is submitted which turns out to not be ready for review, the PR should be closed or marked as draft instead of being left open.

You're right. I should mark this as draft and re-open this when i'm totally finished with it. I'm constantly adding new features that come into my mind so i add them and find some bugs while adding them. Thank you and have a great day!

**Comment by Nightfirecat** [comment]
You register a hotkey listener in plugin startup, but never unregister it. Please do so on plugin shutdown.
The rest LGTM

**Comment by derfurkan** [comment]
> You register a hotkey listener in plugin startup, but never unregister it. Please do so on plugin shutdown. The rest LGTM

Fixed this issue and pushed it to the pull request.

**Pull request merged**
