### PR TITLE
Update Resting to v1.1.5

### PR DESCRIPTION
**Pull request by ScreteMonge**
Updated for new item offsets

### CODE REVIEW

**Comment by raiyni** [comment]
Need to fix https://github.com/runelite/plugin-hub/actions/runs/10483700656/job/29036837977?pr=6495#step:6:76

**Comment by ScreteMonge** [comment]
@raiyni should be fixed now, thanks.

**Review by iProdigy — DISMISSED** [review]
instead of doing `WidgetUtil.componentToInterface`, you could just use `InterfaceID` (i.e., `MINIMAP`, `BANK`, `DIALOG_OPTION`, `DIALOG_NPC`, `DIALOG_PLAYER`, and `BANK_PIN`)

**Comment by ScreteMonge** [comment]
Thanks @iProdigy , changes have been made

**Review by iProdigy — APPROVED** [review]

**Pull request merged**
