### PR TITLE
Added Barbarian Assault pb Tracking

### PR DESCRIPTION
**Pull request by SkylerPIlot**
This plugin serves as a carbon copy of the barbarian assault plugin found ingame along with just adding the extra functionality of saving the best run time to the user's config file, which can then be called up using the !pb commands

### CODE REVIEW

**Comment by Nightfirecat** [comment]
The configurations this plugin sets should be identifiable by the same config keys it uses for user configs, ie. `BaPb`

**Comment by SkylerPIlot** [comment]
The main goal with saving it under "personalbest" was the ability to automatically be integrated into the !pb command so someone could just do !pb without me having to write my own handling for chat commands. I can easily integrate my own chat command handling though and will update the pr when its implemented.

**Comment by SkylerPIlot** [comment]
This newest commits saves the configurations this plugin makes under the BaPB key
This newest update also adds a new chat command to all who download the plugin. 

!ba

which can be used with !ba Barbarian Assault
!ba Ba healer
and so forth for all roles that will allow pbs to be shown to all who install and turn on the plugin.
I plan to update the readme with all changes and how to run the plugin.

**Comment by LlemonDuck** [comment]
Wouldn't this plugin be better as just the chat command and pb detection only? Why do you need to duplicate the existing core plugin?

**Comment by SkylerPIlot** [comment]
I duplicated the plugin functionality so I could just have them activate it and deactivate the main one. Could just as easily be gutted down to just saving the personal best and the chat command.

**Comment by SkylerPIlot** [comment]
There we go, now the plugin only adds the !ba command as well as saving into the user's config file

**Comment by SkylerPIlot** [comment]
That was weird the bot couldn't seem to find my license when doing the workflow even though the commit in question had a license file, for now, I merged the branch into master along with updating my build.gradle so the workflows should now work as expected

**Pull request merged**
