### PR TITLE
Update Twitch Live Loadout Plugin to v1.1.0

### PR DESCRIPTION
**Pull request by pepijnverburg**
Added syncing of ToA invocations, syncing of looting bag and many stability improvements.

Changelog:
- Tombs of Amascut Invocations can now be synced automatically when at the raid lobby and in the raid itself.
- You can now switch between dark and light theme for your viewers.
- All bank items are now synced to your viewers, rather than only the 200 most valuable items.
- The looting bag can now be synced to viewers.
- Items can now have 'special behaviours' for example the looting bag opens a new side-panel as one of the first items for this behaviour.
- Collection log can be filtered using keywords to chose what you want too sync.
- Added support and documentation links to the `Status` tab in the plugin tab.
- Added automatic detection which account should be synced when multi-logging. The plugin keeps track of which RuneLite window is focussed on for a minimum (configurable) time to determine which account to sync.
- Expanded the `Status` tab to be more transparent in which RuneLite window is currently synchronizing data.
- Enhanced the stability of the plugin by ignoring game events that are disabled by the streamer to sync anyways.

### CODE REVIEW

**Comment by Nightfirecat** [comment]
It doesn't look like the Discord icon included in this PR [abides by their branding guidelines](https://discord.com/branding). (specifically, neither of the options they offer have the icon with a circle around it)

**Comment by pepijnverburg** [comment]
@Nightfirecat Thanks for the review! I got the icon from the RuneLite build-in 'info' plugin (see screenshot), because I thought a bit of consistency would be nice. 

Happy to change the icon and if you want also submit a PR to get the icons of the built-in info plugin updated to match the branding guidelines of the various platforms (Github, Discord and Patreon in this case).

Screen Shot 2022-09-27 at 21 12 06

Let me know what your preference is :)

**Comment by Nightfirecat** [comment]
Even within the core client we aren't consistent about it, since you can see the discord button in the titlebar is not contained in a circle. That said, we probably should update the info panel icons accordingly. I've opened https://github.com/runelite/runelite/issues/15743 to track this for the main client. For now I'd recommend just using [Discord's plain white icon variant](https://assets-global.website-files.com/6257adef93867e50d84d30e2/62f0a9e560a799075a4e0cea_Discord-Logo-White%20(3).png)

**Comment by pepijnverburg** [comment]
@Nightfirecat Ah, never noticed the icon at the top! Probably Discord changed their guidelines in the mean time as well, so it is easy to get it outdated... 

Will have a look at updating the icons for the core client while I'm at it anyways for this plugin. I think the same is applicable for Patreon (https://www.patreon.com/brand) and GitHub (https://github.com/logos). I do like the circle around it for the sake of creating a sense of unity and consistency across the logo's, but better to change them to match the guidelines.

**Comment by pepijnverburg** [comment]
@Nightfirecat I got to updating the icons. Let me know if they are good now. Will look at PR for the core client if they are.

**Pull request merged**
