### PR TITLE
Create hide-anything

### PR DESCRIPTION
**Pull request by RuneAd**

### CODE REVIEW

**Comment by raiyni** [comment]
I'm confused about what the point of this is. You can already do this with entity just.

**Review by RuneAd — COMMENTED** [review]
Added license

**Comment by RuneAd** [comment]
> I'm confused about what the point of this is. You can already do this with entity hider

Thank you for your feedback! While it's true that Entity Hider offers functionality to hide groups of entities, our plugin is designed to provide a significantly more tailored and granular approach. Here's how it stands out:

**Individual Control:** Unlike Entity Hider, which hides entire categories of entities (like all players or all NPCs), our plugin allows you to selectively hide individual players or NPCs. This level of precision enables a much more customized gameplay experience.

**Advanced Spam and Bot Management:** Our plugin **(WILL)** include advanced tools to automatically detect and hide spammers or bots, offering seamless control over in-game disruptions without the need for constant manual adjustments.

**Dynamic Auto-Hiding Features:** The plugin can intelligently auto-hide entities based on criteria you define, providing a smoother and more adaptable gameplay environment. (**With a few updates of course, just getting the base started)**

We believe these features empower players with enhanced control and personalization, going beyond what existing tools like Entity Hider can achieve. We're confident that this added functionality will bring a fresh level of enjoyment and convenience to your in-game experience.

Let us know if you have further questions or suggestions! 😊

**Comment by raiyni** [comment]
We aren't going to accept a plugin that providers finer grain control of hiding players and entities as that would fall under some third party client guidelines. We also aren't accepting plugins that crowd source information about players through third party apis.

**Pull request closed without merging**
