### PR TITLE
add butler-info plugin

### PR DESCRIPTION
**Pull request by NickMckloski**
This plugin helps keep track of information relating to a POH butler/servant. It tracks things like the items the butler is holding, time until butler returns from bank, and number of trips until payment is required again.

### CODE REVIEW

**Comment by pwatts6060** [comment]
You could add this into my butler plugin so there's just one butler plugin and you'd get the features to players quicker as lots have it already

**Comment by NickMckloski** [comment]
> You could add this into my butler plugin so there's just one butler plugin and you'd get the features to players quicker as lots have it already

I did think about that, but to be honest your plugin didn't work for me for some reason. This is a complete rewrite. I also plan to add more in the future and would like to be the repo maintainer for that work.

**Comment by pwatts6060** [comment]
> > You could add this into my butler plugin so there's just one butler plugin and you'd get the features to players quicker as lots have it already
> 
> I did think about that, but to be honest your plugin didn't work for me for some reason. This is a complete rewrite. I also plan to add more in the future and would like to be the repo maintainer for that work.

Your plugin seems to do everything mine does and more. We could just replace mine with yours and I'll give you full contributor and merging permissions if you're interested.

**Comment by NickMckloski** [comment]
> > > You could add this into my butler plugin so there's just one butler plugin and you'd get the features to players quicker as lots have it already
> > 
> > 
> > I did think about that, but to be honest your plugin didn't work for me for some reason. This is a complete rewrite. I also plan to add more in the future and would like to be the repo maintainer for that work.
> 
> Your plugin seems to do everything mine does and more. We could just replace mine with yours and I'll give you full contributor and merging permissions if you're interested.

Sure. Could we just update the repo url and commit in your plugin to point at my repo? Seems easier if that's possible.

**Comment by pwatts6060** [comment]
> > > > You could add this into my butler plugin so there's just one butler plugin and you'd get the features to players quicker as lots have it already
> > > 
> > > 
> > > I did think about that, but to be honest your plugin didn't work for me for some reason. This is a complete rewrite. I also plan to add more in the future and would like to be the repo maintainer for that work.
> > 
> > 
> > Your plugin seems to do everything mine does and more. We could just replace mine with yours and I'll give you full contributor and merging permissions if you're interested.
> 
> Sure. Could we just update the repo url and commit in your plugin to point at my repo? Seems easier if that's possible.

yeh that works

**Comment by NickMckloski** [comment]
> > > > > You could add this into my butler plugin so there's just one butler plugin and you'd get the features to players quicker as lots have it already
> > > > 
> > > > 
> > > > I did think about that, but to be honest your plugin didn't work for me for some reason. This is a complete rewrite. I also plan to add more in the future and would like to be the repo maintainer for that work.
> > > 
> > > 
> > > Your plugin seems to do everything mine does and more. We could just replace mine with yours and I'll give you full contributor and merging permissions if you're interested.
> > 
> > 
> > Sure. Could we just update the repo url and commit in your plugin to point at my repo? Seems easier if that's possible.
> 
> yeh that works

Cool, ill close this pr and make a new one then.

**Pull request closed without merging**
