### PR TITLE
Create coxscavcalculator

### PR DESCRIPTION
**Pull request by Bwana-Ian**
Created a new plugin for calculating the required scav supplies and herbs needed for potions in CoX

### CODE REVIEW

**Comment by Bwana-Ian** [comment]
Put file in wrong spot changing and re-pull requesting

**Comment by Hydrox6** [comment]
Don't make a new pull request, just update this one

**Comment by IanSiebold** [comment]
This should be good to go now.

**Comment by Bwana-Ian** [comment]
Is there anything you need from me to get this approved?

**Comment by Bwana-Ian** [comment]
I believe I fixed the work flow errors I was getting with this

**Pull request merged**
