### PR TITLE
Update status-socket

### PR DESCRIPTION
**Pull request by DStatIO**
Made some fresh updates and fixed some bugs to have equipment bonuses and better hit splat tracking.

### CODE REVIEW

**Comment by raiyni** [comment]
You need to commit your commit hash.

**Comment by DStatIO** [comment]
> You need to commit your commit hash.

Thanks for that. Got that fixed.

**Comment by Nuginu** [comment]
This might sounds really dumb, but how do you use this? interested in tracking average hits and whatnot.

**Comment by DStatIO** [comment]
> This might sounds really dumb, but how do you use this? interested in tracking average hits and whatnot.

Feel free to contact me on discord: DStat#0001
Willing to help out

**Comment by Nuginu** [comment]
> > This might sounds really dumb, but how do you use this? interested in tracking average hits and whatnot.
> 
> Feel free to contact me on discord: `DStat#0001`
> Willing to help out

Sent you a Msg. Name on Discord is the same as my display name here.

**Pull request merged**
