### PR TITLE
Update discord-rare-drop-notificater plugin for RL version 1.7.0

### PR DESCRIPTION
**Pull request by BossHuso**

### CODE REVIEW

**Comment by Adam-** [comment]
@MasterKenth are you still alive / do you care if someone else takes maintainership over this?

**Comment by MasterKenth** [comment]
> @MasterKenth are you still alive / do you care if someone else takes maintainership over this?

I do not mind at all! I'm not currently actively playing and sadly don't have time to work on this. If anyone would like to take over please feel free to do so, and if anything else is required from me to make that happen please inform me and I'll deal with it asap 🙂.

**Comment by BossHuso** [comment]
@MasterKenth 

Thanks for responding :) Would you mind adding me as a collaborate in the main repo or transfer it if you don't expect to work on it anymore? I'll make sure to keep your name / credits in place.

Would make it easier for me to handle the current issues placed :)

**Comment by MasterKenth** [comment]
> @MasterKenth
> 
> Thanks for responding :) Would you mind adding me as a collaborate in the main repo or transfer it if you don't expect to work on it anymore? I'll make sure to keep your name / credits in place.
> 
> Would make it easier for me to handle the current issues placed :)

I don't expect to work on it any time soon, however I was unable to transfer the repo as you already have a fork of it with the same name. I've invited you as a collaborator in the meantime.

**Comment by BossHuso** [comment]
> > @MasterKenth
> > Thanks for responding :) Would you mind adding me as a collaborate in the main repo or transfer it if you don't expect to work on it anymore? I'll make sure to keep your name / credits in place.
> > Would make it easier for me to handle the current issues placed :)
> 
> I don't expect to work on it any time soon, however I was unable to transfer the repo as you already have a fork of it with the same name. I've invited you as a collaborator in the meantime.

Could you try it again now? Just deleted the fork after the PR :)

**Comment by MasterKenth** [comment]
> > > @MasterKenth
> > > Thanks for responding :) Would you mind adding me as a collaborate in the main repo or transfer it if you don't expect to work on it anymore? I'll make sure to keep your name / credits in place.
> > > Would make it easier for me to handle the current issues placed :)
> > 
> > 
> > I don't expect to work on it any time soon, however I was unable to transfer the repo as you already have a fork of it with the same name. I've invited you as a collaborator in the meantime.
> 
> Could you try it again now? Just deleted the fork after the PR :)

Seems to be working now! After you've accepted it should be yours 👍 .

**Pull request merged**
