### PR TITLE
Update click-to-minimize

### PR DESCRIPTION
**Pull request by WaylonJ**
This changes the plugin's config from:
key: value 
to
key: list\<value\> 

so that players can have multiple of the same action leading to other actions.

e.g. 
search: chest,
search: wardrobe

previously it would overwrite the first value causing it to fail.

### CODE REVIEW

**Comment by Alexsuperfly** [comment]
https://github.com/runelite/runelite/blob/master/runelite-client/src/main/java/net/runelite/client/util/Text.java#L82 ?

**Comment by WaylonJ** [comment]
Removing jsoup and using that, thanks! 🙌
Ill have an update shortly

**Comment by WaylonJ** [comment]
Updated the original issue to remove jsoup and fix duplicate action issue,

Included new changes in recent commit. Updated config to include 
- 'ignore case' toggle for actions, 
- 'ignoreFullInventory' toggle to not do anything if the inventory is full,
- Keybind for minimizing the window (useful when cutting gems or other menu context items).

**Comment by WaylonJ** [comment]
Added a new config to allow functionality to work with menu options (e.g. grand exchange confirm menu)

Comparison of all changes to the current commit for this pr can be found here:
https://github.com/WaylonJ/OSRS_ClickToMinimize/compare/536c4473442d20c79772df7f5e64d792500142b9...ac730fa35a3751f746db234980bf9d33b2eb0692

**Pull request merged**
