### PR TITLE
Update dynamic-inventory-tags

### PR DESCRIPTION
**Pull request by BraveH**
Fixes weapon styles broken by new update & hide on toolbar setting

### CODE REVIEW

**Comment by BraveH** [comment]
Hello! Any updates on this? As it’s just causing bugs to be open on the GitHub page requesting this fix.

**Comment by cdfisher** [comment]
> Hello! Any updates on this? As it’s just causing bugs to be open on the GitHub page requesting this fix.

Generally it can take a couple of weeks for hub PRs to be reviewed depending on when the reviewers are free.

**Comment by jboss94** [comment]
This still seems to now work, is there a solution on my end?

**Comment by Felanbird** [comment]
This is not an repo for issue reports, this is a repo for plugin authors to submit their changes for review.

You can find the support link by searching for the plugin in the Plugin Hub panel and clicking the ? button on the plugin, or by right-clicking the plugin in the plugin panel and clicking the Support menu option.

**Comment by cdfisher** [comment]
> This still seems to now work, is there a solution on my end?

The update has been merged. If there are still issues contact @BraveH or open an issue [here.](https://github.com/BraveH/gear-switch-alert)

**Pull request merged**
