### PR TITLE
Add raids-dry-meter plugin

### PR DESCRIPTION
**Pull request by RydawgRS**
*BETA*This keeps logs of users luck for uniques at raids. Only currently works for solo Chambers of Xeric.

### CODE REVIEW

**Comment by abextm** [comment]
Your folder name should be something that resembles your plugin's name.

**Comment by RydawgRS** [comment]
Gotcha, I just adjusted the folder name unless I misunderstood what you meant

**Comment by abextm** [comment]
No I meant <https://github.com/RydawgRS/raids-dry-meter/blob/c8591e069c46767305cbe4954f641a2eb9af617a/src/main/java/com/raidsdrymeter/storage/RecordWriter.java#L21> should read something like `new File(RUNELITE_DIR, "raids-dry-meter");`

**Comment by RydawgRS** [comment]
fixed

**Pull request merged**
