### PR TITLE
New Plugin bolt-sounds

### PR DESCRIPTION
**Pull request by pelletier2017**
Adding a new plugin to customize sounds for crossbow bolt procs and special attacks

### CODE REVIEW

**Comment by pelletier2017** [comment]
Any idea what is wrong? The commit seems to be found here and its the same commit in runelite-plugin.properties

https://github.com/pelletier2017/runelite-bolt-sounds/tree/39cc09ab7270d8b1ff568d1942af34b3f63113b8

**Comment by geheur** [comment]
`commit=commithash`
you forgot commit=

**Comment by LlemonDuck** [comment]
we cannot distribute many of the sounds included here due to a lack of permissions to use the copyright. many plugin authors get around this issue by not including any sounds, but instead allowing users to provide their own sound files.

please remove the included sound files or replace them with publicly licensed clips.

**Comment by Nightfirecat** [comment]
Closing due to inactivity.

**Pull request closed without merging**
