### PR TITLE
Update raid-name-logger to v1.1

### PR DESCRIPTION
**Pull request by stevenkaan**
Made some small changes to the plugin
- Changed the root directory
- Made the plugin so it shows the raids in the top of the plugin instead of the middle

### CODE REVIEW

**Comment by stevenkaan** [comment]
It seems like i put the wrong group in my build.gradle.. Don't know how much this matters?

**Comment by stevenkaan** [comment]
Okey.. Seems like i can update it without closing this request ;)

**Comment by raiyni** [comment]
Remove your test code please 

```
        addRaid(Arrays.asList("Test"));
        addRaid(Arrays.asList("Test"));
```

**Comment by stevenkaan** [comment]
> Remove your test code please
> 
> ```
>         addRaid(Arrays.asList("Test"));
>         addRaid(Arrays.asList("Test"));
> ```

Thanks, didn't notice this.
- Removed the test code and also removed some unused imports.

**Comment by raiyni** [comment]
You need to remove the button from the navigation panel on plugin shutdown too.

**Comment by stevenkaan** [comment]
> You need to remove the button from the navigation panel on plugin shutdown too.

I added the following in 'shutdown'
- clientToolbar.removeNavigation(navigationButton);

**Pull request merged**
