### PR TITLE
Create bank-highlighter

### PR DESCRIPTION
**Pull request by Evamist**
Bank Highlighter, inspired by RuneLite's "Inventory Tags," lets you color-code items in your bank or inventory (while the bank is open) for easier visibility. This feature is particularly useful for organizing skill/combat gear sets and quickly finding the items you need. Simply hold Shift, right-click on 'Bank Highlight,' and select your desired color.

### CODE REVIEW

**Comment by YvesW** [comment]
I've not done an extensive review, but...
- Your license is attributed to Tony905x? Did Tony work on this?
- If you only copy pasted a (significant) part of core code, you should attribute it to among others the people that wrote it. This code seems to be 99.9% inventory tags, if you exclude the removed licenses.
- Why do you have code that migrates a config value? I guess because this was directly copied from inventory tags?

**Comment by Evamist** [comment]
> Member

Hey! Honestly I'm still learning I've never made a plugin before, just wanted something that hasn't been done. Yes was created from Inventory Tags hence including in all descriptions (do I need to add more or contact them). And not sure how I missed that but no idea who Tony is.

**Comment by Evamist** [comment]
Anything I can do?

**Comment by Evamist** [comment]
@YvesW Anything more I can do?

**Comment by Felanbird** [comment]
> @YvesW Anything more I can do?

Wait, all of [these plugins](https://github.com/runelite/plugin-hub/pulls?q=sort%3Aupdated-desc+is%3Aopen+label%3A%22plugin+added%22) are ahead of you in the queue + updates for other plugins. Yves just gave you a quick review based on what he noticed at a glance.

**Comment by Evamist** [comment]
@Felanbird As mentioned above, I'm new to this. I wasn't demanding a responce now, just sending my part ready. And tagged the person as I realised the original message didn't.

**Comment by Evamist** [comment]
@YvesW @Felanbird Hey guys! Any approx idea of how long this is going to take to be looked at?

**Comment by LlemonDuck** [comment]
this shouldn't render over the bank pin interface <https://github.com/Evamist/Bank-Highlighter/blob/6ed4d76a3f368ba1e61b6630536b99342a8410c7/src/main/java/com/bankhighlighter/BankHighlighterOverlay.java#L36>

Other than that, everything looks fine

**Comment by Evamist** [comment]
@LlemonDuck Thank you. Updated!

**Comment by LlemonDuck** [comment]
As a heads up, your icon.png is named with an extra .png on the end. I'm gonna merge the plugin now regardless since I've reviewed it as is, but you may wish to submit another small PR to fix the icon.

**Pull request merged**
