### PR TITLE
Add DMWatch plugin.

### PR DESCRIPTION
**Pull request by DMWatch**
It's a hybrid of player indicators (indicate party member tiers) runewatch but for death matching community
party plugin to share information between users to reduce scams and risk

Allows people to be marked as specific roles like scammer or regular or streamer.

### CODE REVIEW

**Comment by Nightfirecat** [comment]
Why are you modifying line-markers and radius-markers?

**Comment by zguilt** [comment]
When I originally created this commit, I accidently had it added as an amend to a commit rather than one on it's own (fat fingered a check box in my git gui app). I didn't realize until you responded that I had done that. 

Should be cleaned up now. 

How can I issue the rebuild work flow?

**Comment by zguilt** [comment]
Is there a way for me to make sure on the rebuild workflow issued that it’ll work? I corrected the gson issue but am not sure about any other issues that the workflow checks. 

Also does it only rebuild when an admin tells it to or is there a work flow button i am blind to? Thanks!

**Comment by Nightfirecat** [comment]
There's a button we need to press since this is a submission from an account which hasn't previously had any contributions to this repository

**Comment by zguilt** [comment]
> There's a button we need to press since this is a submission from an account which hasn't previously had any contributions to this repository

Good to know. My community friends are excited what we have put together. Thanks for issuing the rebuild, looks like it worked this time. 

Now to practice patience. :)

**Pull request merged**
