### PR TITLE
Create bankers-note-helper

### PR DESCRIPTION
**Pull request by robromanowski**
This is a plugin for Banker's Note.

It will display an icon of the current item Banker's Note is using. (Similar to how Rune Pouch shows small icons for what Runes are currently in the pouch).

### CODE REVIEW

**Comment by cdfisher** [comment]
Your build is failing because you use WidgetInfo or WidgetID. [link](https://github.com/runelite/plugin-hub/actions/runs/12208857039/job/34062753064?pr=7119#step:6:87)

**Comment by raiyni** [comment]
Can you name this without calling it better and give it a more descriptive name of what it does?

**Comment by robromanowski** [comment]
Sure, I can certainly do that! Will fix the name and description soon.

Currently trying to figure out switching off WidgetInfo

**Comment by robromanowski** [comment]
Hey @raiyni and @cdfisher!

I have successfully removed the deprecated usage of WidgetInfo and have replaced it with ComponentID/InterfaceID.

Furthermore, as asked, I have renamed it to "Banker's Note Helper" to remove the word _better_,

I have also updated the README, to give more info about it! It's pretty simple so let me know if you need more:

> Puts an icon in the corner of Banker's Note.
> Allows for an outline in the color of your choice.
> 
> Example:
> 
> image
> 
> If you are switching between multiple items with Banker's Note, you want to ensure you un-note the right one.
> This plugin will show a little icon, overlayed over the Banker's Note item, to show what it is currently set too.

Hope that's good!

Final question - I'm new to this style of PR's, where we merge off the commit hash. Since I changed the name of the repo as well (that URL changed) and I have a new hash - how do you advise me to update the PR?

**Comment by iProdigy** [comment]
the most important is to update the repo url and commit hash. optionally you can also rename the file to `bankers-note-helper`

**Comment by robromanowski** [comment]
> the most important is to update the repo url and commit hash. optionally you can also rename the file to `bankers-note-helper`

Awesome, thanks! Done!

**Comment by LlemonDuck** [comment]
* this file isn't needed https://github.com/robromanowski/bankersnotehelper/blob/eae4cc548bef0860b46b5e471c5a83514bfa4171/src/main/resources/META-INF/services/net.runelite.client.plugins.Plugin
* demote this to log.debug https://github.com/robromanowski/bankersnotehelper/blob/eae4cc548bef0860b46b5e471c5a83514bfa4171/src/main/java/com/bankersnotehelper/BankersNoteHelperOverlay.java#L38
* demote this to log.debug https://github.com/robromanowski/bankersnotehelper/blob/eae4cc548bef0860b46b5e471c5a83514bfa4171/src/main/java/com/bankersnotehelper/BankersNoteHelperPlugin.java#L129

everything else looks good

**Comment by raiyni** [comment]
You should probably use WidgetItemOverlay and cache your image you are drawing probably

**Comment by robromanowski** [comment]
> * this file isn't needed https://github.com/robromanowski/bankersnotehelper/blob/eae4cc548bef0860b46b5e471c5a83514bfa4171/src/main/resources/META-INF/services/net.runelite.client.plugins.Plugin
> 
>     * demote this to log.debug https://github.com/robromanowski/bankersnotehelper/blob/eae4cc548bef0860b46b5e471c5a83514bfa4171/src/main/java/com/bankersnotehelper/BankersNoteHelperOverlay.java#L38
> 
>     * demote this to log.debug https://github.com/robromanowski/bankersnotehelper/blob/eae4cc548bef0860b46b5e471c5a83514bfa4171/src/main/java/com/bankersnotehelper/BankersNoteHelperPlugin.java#L129
> 
> 
> everything else looks good

Awesome, thanks!

Removed the file, and changed those log levels!

**Pull request merged**
