### PR TITLE
Add equipment-inspector plugin

### PR DESCRIPTION
**Pull request by botanicvelious**
Allows you to see the equipment that someone has equipped.

### CODE REVIEW

**Comment by botanicvelious** [comment]
note: there is no features like how much items are worth etc, just the names and icons

**Comment by botanicvelious** [comment]
updated to not show charges on equipped items and always show max charges

**Comment by dekvall** [comment]
Even without price information, I believe that a plugin like this can be abused in PvP scenarios. It would still be significantly easier to determine potential risk with this plugin rather than by visual inspection. I think that if it were to be added, it should be disabled in PvP altogether.
Furthermore, the implementation is mostly a copy of the unlicensed code in https://github.com/runelite/runelite/pull/3733. Though, maybe that's fine since it was PRed with the intention of adding it to the main client.

**Comment by botanicvelious** [comment]
Updated it to not work in any pvp area

**Comment by dekvall** [comment]
I guess it's fine then, please add a link to your repository in the `support` field of `runelite-plugin.properties`

@sean-duffy As the original author, are you ok with this?

**Comment by sean-duffy** [comment]
Fine by me, will look forward to using it in the plugin hub! 👍

**Comment by Nightfirecat** [comment]
For what it's worth, I don't think this needs a non-PVP limiter. Generally speaking, anyone who is familiar with PVP in almost any capacity will be able to identify items (and therefore risk) without any aid, so this wouldn't impact them whatsoever.

**Comment by botanicvelious** [comment]
> 
> 
> For what it's worth, I don't think this needs a non-PVP limiter. Generally speaking, anyone who is familiar with PVP in almost any capacity will be able to identify items (and therefore risk) without any aid, so this wouldn't impact them whatsoever.

While I personally agree especially since it normalizes all charges etc on items I can see the argument, so fair enough.

@sean-duffy thanks :) only downside is that to normalize charges etc it no longer shows the trim version name etc... tho it does show the base item so you can at least figure it out

@dekvall done

**Comment by botanicvelious** [comment]
> 
> 
> Like I mentioned before, I don't think the wilderness check is valuable since it doesn't really impact players who know what kind of valuables to look for, and it can be worked around by any of the following:
> 
>     * Perform the lookup on a player while standing outside of the wilderness
> 
>     * Perform the lookup on a player while in a PVP world (afaict there's no check for this)
> 
> 
> If someone was unaware enough to not be able to recognize gear but still wanted to use this to identify targets to potentially lure into PVP, this could still be used in those cases. I'll reiterate that my opinion is that there are basically 0 players for whom that'll be the case where this plugin would aid them in doing so.
> 
> Regardless, LGTM

If it will be approved without the wilderness check I will remove it, I tend to agree.

**Comment by abextm** [comment]
imo this is fine without a wildy check; you still need to know the value of an item, and if you know that you probably know what it looks like.

**Comment by botanicvelious** [comment]
update to remove the pvp check! 👍

**Pull request merged**
