### PR TITLE
Create autumngarden

### PR DESCRIPTION
**Pull request by Ailie-Luibh**
My plugin is an adaptation of Majesty373's Spring Garden plugin. It helps with the Autumn Garden portion of Sorceress' Garden instead as the name implies.

### CODE REVIEW

**Comment by abextm** [comment]
Have you considered pring this to the existing summer garden plugin?

**Comment by pwatts6060** [comment]
> Have you considered pring this to the existing summer garden plugin?

I think users are fine with separate ones, the gardens are close together and share the same teleport point when you finish a round probably, people definitely don't want to have multiple gardens at the same time with one plugin. 

If it was merged, at least a combo box to choose which garden you are doing.

**Comment by Ailie-Luibh** [comment]
So far the summer and spring garden addons are already separated from one another. If I were to merge all of them would I push it to the summer garden one, my own branch? Not sure how that would work.

**Comment by pwatts6060** [comment]
Needed this for leagues and cloned it. Works well, should be merged now imo.

**Pull request merged**
