### PR TITLE
Create ferocitylootlogger

### PR DESCRIPTION
**Pull request by gord5500**

### CODE REVIEW

**Comment by gord5500** [comment]
We are doing a bingo event and using the plugin Adam made for sending web hooks to Discord. This is just an addition in that we can allow the user to enter a list of items to also send if they don't meet the GP threshold

**Comment by gord5500** [comment]
Changed the plugins property in runelite-plugin.properties to 'com.ferocitylootlogger.FerocityLoggerPlugin' which should be the correct path. Thanks Nightfirecat for your help!

**Comment by Nightfirecat** [comment]
[Your config group](https://github.com/gord5500/loot-logger-extended/blob/71f63f827861ff8168ffdb1a5dcad54a62ec0d1f/src/main/java/com/ferocitylootlogger/FerocityLoggerConfig.java#L10) should be unique to your plugin so it does not conflict with others.

**Comment by Nightfirecat** [comment]
Closing this PR as it is inactive.

**Pull request closed without merging**
