### PR TITLE
Refactored Elysium Events to Clan Events

### PR DESCRIPTION
**Pull request by cmsu224**

### CODE REVIEW

**Comment by cmsu224** [comment]
Due to requests from other clan chats wanting to use the plugin, I've changed the name from Elysium Events to Clan Events.

**Comment by Adam-** [comment]
Plugins get their name from both the `runelite-plugin.properties` and from the `PluginDescriptor`. The name internally used by the pluginhub is unrelated, and changing it essentially introduces a new plugin and causes you to lose your install base. So we recommend not renaming the plugin here.

**Comment by cmsu224** [comment]
> Plugins get their name from both the `runelite-plugin.properties` and from the `PluginDescriptor`. The name internally used by the pluginhub is unrelated, and changing it essentially introduces a new plugin and causes you to lose your install base. So we recommend not renaming the plugin here.

I've undone the name change in the pluginhub; Will there be any conflicts if I change the repository url in the elysiumevents-plugin?
image

**Comment by Adam-** [comment]
> 
> 
> > Plugins get their name from both the `runelite-plugin.properties` and from the `PluginDescriptor`. The name internally used by the pluginhub is unrelated, and changing it essentially introduces a new plugin and causes you to lose your install base. So we recommend not renaming the plugin here.
> 
> I've undone the name change in the pluginhub; Will there be any conflicts if I change the repository url in the elysiumevents-plugin?
> image

That's fine

**Pull request merged**
