### PR TITLE
Create hpdisplay

### PR DESCRIPTION
**Pull request by austinwblake**
This plugin allows you to make a real life LED health bar using an Arduino, LED strip and a few other electronic components.

### CODE REVIEW

**Comment by LlemonDuck** [comment]
Your build is failing since you did not add your new dependency (jSerialComm) to the third party metadata verification list: https://github.com/runelite/plugin-hub#third-party-dependencies

However, do note that we also have to review any dependencies pulled in and such a complex dependency with all these numerous natives is probably more than we'll have time willing to review.

**Comment by Nightfirecat** [comment]
This PR has been failing CI for a month without further changes; closing due to inactivity.

**Comment by austinwblake** [comment]
I have been waiting for my dependency (jSerialComm) to be reviewed. Did I not correctly add it to the third party metadata verification list?

**Comment by Adam-** [comment]
> I have been waiting for my dependency (jSerialComm) to be reviewed. Did I not correctly add it to the third party metadata verification list?

No. If you did, your PR would have change to `verification-metadata.xml` showing it was added.

**Pull request closed without merging**
