### PR TITLE
 Collapsible-Modern-Chat-Plugin

### PR DESCRIPTION
**Pull request by UNDEAD-B0T**
how badly did i mess this up... the plugin is fine but new to github shenanigans

### CODE REVIEW

**Comment by Nightfirecat** [comment]
You need to create your plugin file [in the `plugins/` directory, not `pluginhub/`](https://github.com/runelite/plugin-hub/tree/master/plugins), and include the full 40-character hash, not just the short hash.

**Comment by Nightfirecat** [comment]
Also, please push changes to this branch instead of closing and re-opening PRs.

**Comment by UNDEAD-B0T** [comment]
ah okay ty ill try fixing

**Comment by UNDEAD-B0T** [comment]
is this okay or do i still have to make the the file in plugins/ area cause im not sure how to do that without creating another pull request :/

**Comment by Nightfirecat** [comment]
Delete the `pluginhub/plugin` file you've created and create a file with the same contents in a `plugins/resizable-modern-chat` file

**Pull request closed without merging**
