### PR TITLE
Create spring-garden

### PR DESCRIPTION
**Pull request by Jonesa5**
This plugin marks and colors the tiles that are safe or not safe to walk to while doing the Sorceress's Garden/Spring. The tiles are green when it is safe to move to them, and they are red when it is not safe to move to them. The plugin uses the Spring Elementals' locations' to determine if it is safe to move or not.

### CODE REVIEW

**Comment by geheur** [comment]
Don't create new pull requests when you need to make a change, just update the commit hash, commit, and push. Github will detect the new commit.

**Comment by Jonesa5** [comment]
It says that the build has failed do to missing package "net.runelite.client.plugins.springgarden". I'm not sure why this is coming up. Do you have any suggestions?

**Comment by geheur** [comment]
You imported the wrong thing. I'm guessing you installed a snapshot version of runelite that had your plugin built-in, and then when you moved it to a plugin hub panel and copy-pasted it over you had the old import statements which imported files from your fork of runelite.

I would change the runelite version in build.gradle to 1.7.5 instead of 1.7.5-snapshot.

**Comment by melkypie** [comment]
Your import statements lead to net.runelite.client.plugins.springgarden which is a non-existend plugin. You should instead change them to import your plugin-hub classes under package com.majesty373.springgarden. This works locally due to you having compiled a SNAPSHOT version of the client and using that when building your hub plugin.

**Comment by Jonesa5** [comment]
Thank you for all the information! Im pretty sure it worked this time

**Pull request merged**
