### PR TITLE
Create Collapsible-Modern-Chat-Plugin

### PR DESCRIPTION
**Pull request by UNDEAD-B0T**
Resizeable/Modern Layout only: collapses chat to an icon that shows DMs and all chat

### CODE REVIEW

**Comment by UNDEAD-B0T** [comment]
sorry for my confusion... im kinda a dummy

**Comment by NathanQuayle** [comment]
`@ConfigGroup("example")`

I believe your ConfigGroup needs to be unique and can't be "example".

**Comment by UNDEAD-B0T** [comment]
i think its now correctly updated?

**Comment by NathanQuayle** [comment]
It's not been picked up, by the looks of it.

You'll need to update the commit hash in your PR to point to your most recent hash created by the change. 

Doing so should should automatically update this PR with those changes.

**Comment by UNDEAD-B0T** [comment]
very true thanks

**Comment by UNDEAD-B0T** [comment]
should now be all good? 🙏

**Comment by Gollum69** [comment]
greetings undead bot i like your plugin it sounds similar to my suggestion https://github.com/runelite/runelite/discussions/16173#discussion-4766335
is it similar or nah bc i am part braindead perhaps im wrong, if it is i would love this plugin!

**Comment by UNDEAD-B0T** [comment]
> greetings undead bot i like your plugin it sounds similar to my suggestion [runelite/runelite#16173 (comment)](https://github.com/runelite/runelite/discussions/16173#discussion-4766335) is it similar or nah bc i am part braindead perhaps im wrong, if it is i would love this plugin!

basically when chat is not open, only one button will show and its the "all" button mixed with the "private" side by side... so itll glow red when getting a private message but youll also have access to the all button... its meant to clean up the ui but hopefully it can help with what you suggested

**Review by UNDEAD-B0T — COMMENTED** [review]
i think everything is good to go?

**Comment by Nightfirecat** [comment]
Yes, please be patient as it takes time for us to get around to reviewing every hub plugin update

**Comment by Gollum69** [comment]
alot of time undead bot dont worry

**Review by UNDEAD-B0T — COMMENTED** [review]
did i fix the naming error? also do i submit review when ready for next process or is the pr being open already enough sorry didnt know

**Comment by Ben-Colwell** [comment]
You need to fix this before it can be merged. 

collapsible-modern-chat: Plugin class "com.example.collapsiblemodernchatplugin" is missing from the output jar
in file /tmp/pluginhub-package18081573101360670095/collapsible-modern-chat/repo/runelite-plugin.properties:
plugins=com.example.collapsiblemodernchatplugin

Perhaps you wanted com.collapsiblemodernchat.collapsiblemodernchatplugin

**Review by UNDEAD-B0T — COMMENTED** [review]
another change, thanks... i was actually really confused there, i appreciate it

**Pull request merged**
