### PR TITLE
Add Plugin 'Vineyard Helper'

### PR DESCRIPTION
**Pull request by SurfaceCode**
Vineyard Helper highlights tiles containing pickable grapevines in Aldarin vineyard. In addition, the highlight changes colour depending on whether or not the Grape barrel is full. Currently the animation which indicates pickable grapevines is extremely hard to see. This plugin increases the accessibility of the Aldarin vineyard content and greatly improves the experience, which is useful to interested players and, in particular, snowflake accounts.

### CODE REVIEW

**Comment by tylerwgrass** [comment]
Any particular reason `objectIds` is defined in the config when it shouldn't be changed?

**Comment by SurfaceCode** [comment]
> Any particular reason `objectIds` is defined in the config when it shouldn't be changed?

Obsolete feature from early versions/debugging. Has been fixed in newest commit.

**Comment by SurfaceCode** [comment]
Accidentally closed pull request briefly, sorry, not familiar with GitHub.

**Review by tylerwgrass — APPROVED** [review]
Non-blocking considerations:
- You may want to check chat message type is `GAMEMESSAGE`
- You may also be able to use the `DIALOG` message type for the hand-in message check

**Pull request merged**
