### PR TITLE
Create local-consciousness

### PR DESCRIPTION
**Pull request by YeahImRose**
Local Consciousness is a plugin that lets you make an item bounce around on your screen.

Hugely inspired by Global Consciousness, which was removed from the Plugin Hub due to no longer working and not being maintained.

### CODE REVIEW

**Comment by YvesW** [comment]
Does this plugin do anything that's significantly different from Global Consciousness?

**Comment by YeahImRose** [comment]
> Does this plugin do anything that's significantly different from Global Consciousness?

Not at the moment, but I couldn't locate the Global Consciousness plugin's repo, so I wrote this from scratch from my friend's memory of its functionality

**Comment by YeahImRose** [comment]
I looked a bit further and found the original repo, I'll try to reach out to the old dev and see if they plan on fixing the problem or if I should PR them/if they're okay with my replacement plugin.

**Comment by YeahImRose** [comment]
Couldn't find a contact email so bringing the discussion to this thread.
@JacobLindelof Hello, I know you developed [the original plugin this is based on ](https://github.com/JacobLindelof/global-consciousness-plugin), but do not seem to be interested in maintaining, would it be alright by you if I maintain my iteration of the concept and credit you for the original idea? Thanks!

**Comment by Nightfirecat** [comment]
FYI you can find their email from their commits, eg. <https://github.com/JacobLindelof/global-consciousness-plugin/commit/977f4c5b63d6deb89cd6fa590d522ddfa161b293.patch>

**Comment by YeahImRose** [comment]
> FYI you can find their email from their commits, eg. https://github.com/JacobLindelof/global-consciousness-plugin/commit/977f4c5b63d6deb89cd6fa590d522ddfa161b293.patch

Oh true, didn't even cross my mind. I'll send the same message to them on email and link them here. Thanks!

**Comment by YvesW** [comment]
You are adding the overlay twice.

**Comment by YeahImRose** [comment]
> You are adding the overlay twice.

Oops, thanks for the heads up!

**Comment by YeahImRose** [comment]
Done with features, just waiting on permission since I still haven't back from the creator of global consciousness. If that gets the okay then it should just need a once over review and then be good for publishing.

**Comment by YeahImRose** [comment]
Well, it's been over a month since I reached out to the creator of the original plug-in, and still no response. They're clearly still around since they've made commits to a private repo since I've tried to contact them, just not responding.

Is there a way to check what was said to them before their plug-in originally got removed? I assume they were contacted to update it once it broke but clearly they didn't bother, so can we consider it abandoned yet?

**Pull request merged**
