### PR TITLE
update varlamore-house-thieving to v1.4.0

### PR DESCRIPTION
**Pull request by sololegends**
# Release v1.4.0

Added time since bonus chest and other minor changes

- Added overlay option for time since last bonus chest
- Added option to turn off the flashing of the distracted citizen icon
- Added option to turn off distracted icon whilst in a house
- Bettered the owner left overlay rest detection
- Resolved some edge cases for distraction notifications re-emitting when not needed

Implements Issue: https://github.com/sololegends/runelite-varlamore-house-thieving/issues/10
Resolves Issue: https://github.com/sololegends/runelite-varlamore-house-thieving/issues/9

### CODE REVIEW

**Review by iProdigy — APPROVED** [review]
Please close this InputStream (ImageIO doesn't close it for you): https://github.com/sololegends/runelite-varlamore-house-thieving/blob/5dd7c6dd18e998abb4774fe9310037dc6d8ee777/src/main/java/com/sololegends/runelite/VarlamoreHouseThievingPlugin.java#L139

**Comment by sololegends** [comment]
Damn, what a rookie mistake. Thanks for pointing it out! Fixing it now.

**Comment by sololegends** [comment]
Resolved!

**Review by iProdigy — APPROVED** [review]

**Comment by iProdigy** [comment]
> Edit: can I not have the spot bugs in there? that is a development aspect not a runtime dependency.

Since it's a gradle plugin, it has more scope than the test classpath, so it must pass dependency verification too

**Pull request merged**
