### PR TITLE
collection-log-shout

### PR DESCRIPTION
**Pull request by Torchrr**
Tedious (https://www.youtube.com/c/TediousRS) shouts "collection log" every time you open the collection log.

### CODE REVIEW

**Comment by Nightfirecat** [comment]
1. This isn't your plugin, why are you trying to publish it?
2. Do you (or the plugin author) have permission from Tedious to use his voice clip for this plugin?

**Comment by Torchrr** [comment]
> 1. This isn't your plugin, why are you trying to publish it?
> 2. Do you (or the plugin author) have permission from Tedious to use his voice clip for this plugin?

Hi Nightfirecat! Sorry for any trouble this has caused.
I went and asked explicitly if I could use Tedious' voice.
image

As for the ownership of the plugin, this project was a joint effort between myself and fidgetymosue18, who are both contributors, despite him being the owner of the repository. If it makes it easier for the runelite team and/or the automated submissions, I can get him to create a new pull request.

**Comment by FidgetyMouse18** [comment]
> > 1. This isn't your plugin, why are you trying to publish it?
> > 2. Do you (or the plugin author) have permission from Tedious to use his voice clip for this plugin?
> 
> Hi Nightfirecat! Sorry for any trouble this has caused. I went and asked explicitly if I could use Tedious' voice. image
> 
> As for the ownership of the plugin, this project was a joint effort between myself and fidgetymosue18, who are both contributors, despite him being the owner of the repository. If it makes it easier for the runelite team and/or the automated submissions, I can get him to create a new pull request.

As Torchrr has said it is a joint repository. However, I can submit a pull request myself if it is required.

**Review by Nightfirecat — CHANGES_REQUESTED** [review]
The file created in this repository should be lowercased. I recommend renaming it `plugins/collection-log-shout` or `plugins/collectionlogshout`

**Pull request merged**
