### PR TITLE
Create Style-Alert

### PR DESCRIPTION
**Pull request by Varietyz**
Added a plugin that allows users to configure uninterupted screen flashen whilest a combat style is selected that the user configured to be warned about. Also provides the option to change its speed, opacity and wether or not a notification sound should be played on every flash.

This was requested by 1 Def pures.

### CODE REVIEW

**Comment by Varietyz** [comment]
image

**Comment by MESLewis** [comment]
Congratulations, this idea has actually [now been implemented](https://github.com/runelite/runelite/commit/9a66502736582e7093bbf47615b741e0a071c540) in the core client attack styles plugin and will be available when runelite next updates.

**Comment by MESLewis** [comment]
Sorry, I have been informed that this plugin isn't completely replaced by the new core functionality so its now open again.

**Comment by Varietyz** [comment]
> Sorry, I have been informed that this plugin isn't completely replaced by the new core functionality so its now open again.

Hello, Yes i decided to not go for a rework on the default, but rather add an extension that co-operates with it it :)

**Comment by YvesW** [comment]
Could you come up with a more descriptive name? E.g. ``style warner/notifier/notification spammer`` or something like that? (I suck at coming up with good names)

**Comment by Varietyz** [comment]
> Could you come up with a more descriptive name? E.g. `style warner/notifier/notification spammer` or something like that? (I suck at coming up with good names)

Do you mean for the folder structure? or the plugin name on its own?
i think the name right now speaks for itself if seen in a hub, its an indicator for the attack styles.

i could be misunderstanding you, could you elaborate a little more on what exactly you expect or referring to?

i'm willing to co-operate, but i dont see the issue at first glance with the name.

**Comment by raiyni** [comment]
The name of the plug-in. We mostly want to stray from the better/improved names now.

**Comment by Varietyz** [comment]
> The name of the plug-in. We mostly want to stray from the better/improved names now.

Thank you for the response, i'll try to come up with a new name for it! :)

**Comment by Varietyz** [comment]
@YvesW @raiyni 
I went with **Style Alert**

**Comment by Varietyz** [comment]
Since there is an notification alert system present in the Attack styles now, i feel like this is now deemed unnecessary.

**Pull request closed without merging**
