### PR TITLE
Transfer Ownership of Normal-Ancient-Teleports

### PR DESCRIPTION
**Pull request by zoltander**
image

The purpose of this plugin is to sensibly rename the teleports of the ancient spellbook to their map/p.o.i. locations, similarly to Nexus Menu Map.

### CODE REVIEW

**Comment by YvesW** [comment]
Does this plugin significantly differ from https://runelite.net/plugin-hub/show/normal-ancient-teleports?

**Comment by zoltander** [comment]
> Does this plugin differ significantly from https://runelite.net/plugin-hub/show/normal-ancient-teleports?

That plugin is broken for spellbook unfortunately, same idea though.

**Comment by YvesW** [comment]
Could you contribute your fix to their repo? We strongly prefer it if people contribute to existing plugins, since that results in the already existing userbase also benefitting from your fixes, your code having an immediate bigger install base, and it prevents pluginhub clutter and/or fragmentation. <https://github.com/runelite/plugin-hub?tab=readme-ov-file#contribute-to-existing-plugins>

**Comment by zoltander** [comment]
I did try opening an issue about it but I don't think it is being maintained.

https://github.com/IdylRS/runelite-plugins/issues/6

**Comment by YvesW** [comment]
You should open a PR with the fix, and potentially ask if you can be added as a contributor in case Idyl does not want to maintain the plugin anymore.
If that fails, there are steps to transfer the plugin if needed, but we greatly prefer it if a PR gets merged or people get added as contributor.

**Comment by zoltander** [comment]
> You should open a PR with the fix, and potentially ask if you can be added as a contributor in case Idyl does not want to maintain the plugin anymore. If that fails, there are steps to transfer the plugin if needed, but we greatly prefer it if a PR gets merged or people get added as contributor.

Thanks for the advice. I made a PR here: https://github.com/IdylRS/runelite-plugins/pull/7
Let's see how it goes.

**Comment by zoltander** [comment]
Given that I opened an initial issue on Aug 6th and I submitted a PR with the fix 3 weeks ago and IdylRS has no activity on GitHub since July 2023, I think it is safe to say the original plugin is abandoned.

I have updated this pull request to instead point the plugin toward my fork assuming that is the correct way to transfer ownership of it. Please take a look and let me know if anything else needs to be done.

**Comment by YvesW** [comment]
I recommend re-opening your PR, so Idyl still has time to look at it.
@IdylRS would you be fine with adding this person as contributor to your repo, or looking at their proposed changes?

If you want to transfer ownership, we require receipts of contacting Idyl in any way possible with the specific request to be added as contributor, and that if he fails to respond, his repo will be transferred. Since Idyl is a content creator, you'll be able to contact him via quite a couple of ways.
- Via issues/PR: I recommend re-opening the PR and adding that you'd like to be added as contributor, and that if he fails to respond, the repo will be transfer.
- Discord. He might have a discord server or handle on his yt or video description. @ him in the RL Discord if he's in there.
- Email. You can very likely get this from his commits. Alternatively, he also has an email on his yt (maybe a different one).
- Other socials he has on his github, youtube channel, or yt vids.

**Comment by hash-cloud-dev** [comment]
Can we please get this fixed anyone?

**Comment by cdfisher** [comment]
> Can we please get this fixed anyone?

Generally a transfer of ownership won't happen in under a month unless there's a response from the plugin's current owner. Since Yves only reached out two weeks ago, it will probably be a few weeks.

**Comment by YvesW** [comment]
Additionally, I also don't see any receipts of email messages, twitter posts, youtube comments etc. (see my previous message). Idyl probably also has his own Discord. He's a content creator, so there should be many ways to reach him to ask to be added as contributor.

**Comment by evilgenious448** [comment]
Could it possibly be PR'd into Llemonduck's Easy Teleports plugin? That plugin currently doesn't include spellbooks, but based on the description of the plugin it would be suitable:

> Replaces difficult-to-remember teleport options in-game with custom values, defaulting to more sensible values.

Perhaps that would be quicker and less troublesome solution than getting a response from Idyl?

**Comment by zoltander** [comment]
> Additionally, I also don't see any receipts of email messages, twitter posts, youtube comments etc. (see my previous message). Idyl probably also has his own Discord. He's a content creator, so there should be many ways to reach him to ask to be added as contributor.

IMG_3346
IMG_3347

It appears he is not in the RuneLite discord server, so I dm’d him on twitter. I might need to comment on one of his posts on twitter or youtube because I have not heard back. I believe his discord server is patreon only.

**Comment by YvesW** [comment]
@IdylRS Could you add Zoltander to your nornal-ancient-teleports repo as collaborator, or at least reply? If you fail to reply within 2 weeks, your plugin will be transferred to him.

**Comment by LlemonDuck** [comment]
@zoltander We can transfer this plugin ownership to you now. Please fork the repo and make two separate PRs to make our lives easier: the first changes the repository URL, and the second (after the first is merged) changes the commit hash.

**Comment by zoltander** [comment]
> @zoltander We can transfer this plugin ownership to you now. Please fork the repo and make two separate PRs to make our lives easier: the first changes the repository URL, and the second (after the first is merged) changes the commit hash.

First PR here: https://github.com/runelite/plugin-hub/pull/6850

**Pull request closed without merging**
