### PR TITLE
Update Pet the capybara

### PR DESCRIPTION
**Pull request by Droei**
Changed to check by name rather than ID's to prevent updates from breaking the plugin.

### CODE REVIEW

**Comment by pajlada** [comment]
You have branch conflicts, making it look like you're making a new plugin rather than updating your current plugin. You can resolve this by merging runelite's `master` branch onto your `Pet-The-Capybara` branch, resolving the merge conflict, then pushing the changes

**Review by pajlada — APPROVED** [review]
The changes seem good, just checking: Is it expected that you character exclaims "Omg a capy I want to get closer to pet it!!!!!" when hovering over a Capybara?

**Comment by Droei** [comment]
Yes that's correct, it prompts it to make sure the user understands they have to get close to it to pet the capy.

**Review by iProdigy — APPROVED** [review]
your logic may also trigger on players named `Capybara` or `Capybara pup`, but not a blocker for merging

**Comment by Droei** [comment]
If I ever see someone named Capybara I'll make sure to pet them hahaha

**Pull request merged**
