### PR TITLE
Add multicolor-highlights

### PR DESCRIPTION
**Pull request by sgfost**
NPC highlighting plugin with (currently) very simple functionality, but allows for multiple (up to 5) colors for different NPCs.

### CODE REVIEW

**Comment by oeg91** [comment]
Does this plugin works for tob nylocas room when the spiders/crabs does switch styles? i mean, when the Nylocas Ischyros switch to Nylocas Toxobolos, the color change aswell?

**Comment by Hydrox6** [comment]
Considering that would be against the rules, no. That would also make it ineligible to be in the client.

**Comment by oeg91** [comment]
I see, had no idea, thanks for let me know.

**Comment by Nightfirecat** [comment]
@sgfost Apparently you've deleted or privated your repo, is that intentional?

**Comment by sgfost** [comment]
Intentional, yes. Thoughtful, no. Forgot how this was set up. Unsure if it even worked and no one seemed interested in forking it. What do you typically do with abandoned plugins?

**Comment by Nightfirecat** [comment]
We can disable it in the hub so it isn't included in builds

**Comment by stormvansoldt** [comment]
@sgfost I was actually looking into forking this plugin to add some more functionality to it, would it be possible to make the source available again? I'd really appreciate it :)

**Comment by stormvansoldt** [comment]
Just wanted to give a shout to @sgfost for making the source available. Already forked it and have a few updates in the works.

**Pull request merged**
