### PR TITLE
Create Leagues Filter plugin

### PR DESCRIPTION
**Pull request by NathanCollaert**
Simply remove all the Leagues broadcasts messages from your clan chat

### CODE REVIEW

**Comment by andreasx23** [comment]
This feature has been added to my existing filter plugin: https://github.com/runelite/plugin-hub/pull/7088

**Comment by Felanbird** [comment]
Closing since this feature will be added... by you... to `Clan Spam Filter`

**Comment by NathanCollaert** [comment]
> Closing since this feature will be added... by you... to `Clan Spam Filter`

In my defense, I thought the developer of the clan chat filter plugin was inactive. And I wanted the feature asap!

**Comment by andreasx23** [comment]
> > Closing since this feature will be added... by you... to `Clan Spam Filter`
> 
> In my defense, I thought the developer of the clan chat filter plugin was inactive. And I wanted the feature asap! That being said, he is active and PR has been approved so this can indeed be closed as duplicate.

Hehe no worries sir 😊

**Pull request closed without merging**
