### PR TITLE
adding lowest xp plugin

### PR DESCRIPTION
**Pull request by HoustonBass**
new plugin!
shows the difference in xp between your lowest skill and all the others
Helpful for planning around your Tears of Guthix weekly

### CODE REVIEW

**Comment by CreativeTechGuy** [comment]
It looks like your repo is missing a lot of the metadata. For example:

* You didn't fill out the `group` or `version` in your `build.gradle` file
* Your README has no information about your plugin and is currently incorrect
* Your `settings.gradle` is unedited
* Your plugin description is different between the `runelite-plugin.properties` and the `LowestExperiencePlugin.java` file
* Your plugin name is different in every place it appears, you should make them all consistent and ensure that the name which appears in your `runelite-plugin.properties` file is the friendly formatted name and not kebab-case.

This is all super important for when users are trying to find your plugin to understand what it does and also to ensure that everything works and is consistent across every place it is used.

**Comment by Nightfirecat** [comment]
[Do not use `"example"` as your config group.](https://github.com/HoustonBass/lowestSkill4Tears/blob/7a2851a7797f30c9afbf8aeee129a81e09a24b2a/src/main/java/com/lowestLevel/LowestExperienceConfig.java#L8)
[Don't use `loadWhenOutdated = true`](https://github.com/HoustonBass/lowestSkill4Tears/blob/7a2851a7797f30c9afbf8aeee129a81e09a24b2a/src/main/java/com/lowestLevel/LowestExperiencePlugin.java#L33) as that is reserved for plugins which can run without access to `Client`.

**Comment by LlemonDuck** [comment]
Is this plugin's use case covered by [tog-indicator](https://runelite.net/plugin-hub/show/tog-indicator)?

**Comment by HoustonBass** [comment]
> It looks like your repo is missing a lot of the metadata. For example:
> 
> * You didn't fill out the `group` or `version` in your `build.gradle` file
> * Your README has no information about your plugin and is currently incorrect
> * Your `settings.gradle` is unedited
> * Your plugin description is different between the `runelite-plugin.properties` and the `LowestExperiencePlugin.java` file
> * Your plugin name is different in every place it appears, you should make them all consistent and ensure that the name which appears in your `runelite-plugin.properties` file is the friendly formatted name and not kebab-case.
> 
> This is all super important for when users are trying to find your plugin to understand what it does and also to ensure that everything works and is consistent across every place it is used.

fixed

**Comment by HoustonBass** [comment]
> [Do not use `"example"` as your config group.](https://github.com/HoustonBass/lowestSkill4Tears/blob/7a2851a7797f30c9afbf8aeee129a81e09a24b2a/src/main/java/com/lowestLevel/LowestExperienceConfig.java#L8) [Don't use `loadWhenOutdated = true`](https://github.com/HoustonBass/lowestSkill4Tears/blob/7a2851a7797f30c9afbf8aeee129a81e09a24b2a/src/main/java/com/lowestLevel/LowestExperiencePlugin.java#L33) as that is reserved for plugins which can run without access to `Client`.

fixed

**Comment by HoustonBass** [comment]
> Is this plugin's use case covered by [tog-indicator](https://runelite.net/plugin-hub/show/tog-indicator)?

yes and no.
For me, i want to 
know exactly how much xp i need in the skills.
The tog-indicator plugin is great but it only shows my my lowest skill.
I want to see how much xp i need to make it my not lowest skill, or better yet something like this 

how-to

**Comment by CreativeTechGuy** [comment]
@HoustonBass it looks like the metadata is there! Nice. (I'm not a reviewer so I cannot do much more than say that, sorry!)

**Pull request merged**
