### PR TITLE
Add Fun Reminders

### PR DESCRIPTION
**Pull request by erversteeg**
Fun reminders are configurable and each reminder can be stylized differently.

### CODE REVIEW

**Comment by raiyni** [comment]
It would greatly improve the user experience and our time looking at your plugin if you used `ConfigManager::setConfiguration` instead of  generating a massive config file with python.

**Comment by erversteeg** [comment]
So the issue I'm running into is if someone wasn't comfortable with json and wanted to create more than a few prompts, I can't see a way for them to do this without having the items already setup in the config. I can look into switching over to setConfiguration but I'm not seeing a way to create sections or add configurations to a specific section this way.

**Comment by erversteeg** [comment]
Was just thinking if you all need a quick way to verify the integrity of the large config then grab the first 93 lines (everything before "Prompt 1" section) from the config file. Then run the updated copy of config.py and add the output onto the end. Finally do a diff between the file you created and the config file and they will come out the same. This way you know what is defined for each prompt section in config.py is the same and isn't all that different than doing a bunch of setConfiguration calls in a loop.

**Comment by raiyni** [comment]
We aren't going to run a python script to verify your plugin isn't harmful.

**Comment by erversteeg** [comment]
I updated the number of reminders to 10 and renamed the plugin to Fun Reminders.

**Pull request merged**
