### PR TITLE
Add RuneSync

### PR DESCRIPTION
**Pull request by skillingdev**
Adds the plugin companion for [RuneSync](https://www.runesync.com)

Last leagues I was frustrated by the hiscores only being a current snapshot of an account (rather than a time series), and hiscores not tracking collection log items.

For now, this plugin sends loot to the RuneSync API, which allows RuneSync to display users' unique drops. In the future I'd like to display which tasks they have completed, what zones they unlocked, etc. See https://www.runesync.com/users/mid%20packs for an example (except imagine that stats are changing over time, and the loot shown are only collection log items)

### CODE REVIEW

**Comment by skillingdev** [comment]
My original commit hash broke a build.gradle lint rule - I've fixed that with the latest commit hash

**Comment by Adam-** [comment]
Your plugin depends on `SessionManager`. For security reasons, we do not allow plugins to depend on or use it. Additionally, you need to set a warning such as `This plugin shares your IP and username with a 3rd party server not controlled or verified by the RuneLite Developers.`

**Comment by skillingdev** [comment]
Thanks for the review :)

I didn't realize about `SessionManager` - luckily (or not luckily, since it was my mistake for leaving it in) this was unused.

I'll remove the `SessionManager`, and add a warning as well.

**Comment by Nightfirecat** [comment]
The `warning` field should be added to the file in this PR, [not in your runelite-plugin.properties file](https://github.com/skillingdev/runesync-plugin/blob/c12fff4e9c6af1f512117b1538e4c909c335152d/runelite-plugin.properties#L6)

**Comment by skillingdev** [comment]
Gah, ok! Thanks for the pointer. Done

**Pull request closed without merging**
