### PR TITLE
Create forestrycc

### PR DESCRIPTION
**Pull request by rangdevelopment**
A plugin for tracking forestry events in a CC such as roots, mulch, and saps. When users type messages in chat, this plugin creates/destroys timers.

### CODE REVIEW

**Comment by rangdevelopment** [comment]
how do I push an update?

**Comment by Nightfirecat** [comment]
Push a new commit to your `forestrycc` branch of the plugin-hub repository

**Comment by rangdevelopment** [comment]
thanks! done. Looks like it worked. workflow is awaiting approval again.

**Comment by rangdevelopment** [comment]
submitted the wrong update, here is the correct one ^

**Pull request merged**
