### PR TITLE
Create prayer-clock

### PR DESCRIPTION
**Pull request by FionnODoc**
Creates an infobox that begins counting ticks from activation of prayer that can be configured to flash at X amount of ticks.

Example use cases are at the Alchemical Hydra it's attack style changes after every 3 attacks, but this attack change animation can be overridden with it's other animations causing the player to take damage if not paying attention. With this plugin for hydra on a 6 tick attack cycle that means if we set the threshold for the infobox to flash to 18 ticks having to count just incase we miss the animation is no longer necessary.

https://i.imgur.com/pkwN6d5.gif

### CODE REVIEW

**Comment by cdfisher** [comment]
Don't open new pull requests, just push new commits to the existing branch.

**Comment by iProdigy** [comment]
This plugin in its current form seems to violate the third-party guidelines: `Any features which aid any boss fights by doing any of the following are prohibited [...] Prayer switching indicators` https://secure.runescape.com/m=news/third-party-client-guidelines?oldschool=1

Have you considered using an existing tick counter hub plugin to approximate this functionality (with a bit more human effort): https://runelite.net/plugin-hub/show/visual-metronome for example

**Comment by LlemonDuck** [comment]
Marking as draft for now. Please make the requested changes, then mark the plugin as ready for review.

**Comment by MESLewis** [comment]
Closed for inactivity, you can reopen this if you would like to make the requested changes.

**Pull request closed without merging**
