### PR TITLE
Create maxhitalert

### PR DESCRIPTION
**Pull request by doppy2023**
This plugin allows you to receive discord notification whenever the player gets a max hit. You can set the discord webhook url in the plugin settings.

### CODE REVIEW

**Review by raiyni — CHANGES_REQUESTED** [review]
1. Use okhttp to send the request
2. Change your config group to `maxhitalert`
3. Remove calls to `log.info`

**Comment by raiyni** [comment]
1. Inject our okhttp client instead of making your own
2. Use enqueue instead of execute

See https://github.com/Adam-/runelite-plugins/blob/discord-loot-logger/src/main/java/info/sigterm/plugins/discordlootlogger/DiscordLootLoggerPlugin.java for reference

**Comment by raiyni** [comment]
Use clientThread invokeLater to wrap your addMessage call on https://github.com/doppy2023/maxhitalert/blob/5e8362e93c993918fe03157250fe9df1c0a477b9/src/main/java/com/maxhitalert/MaxHitAlertPlugin.java#L86 and it will be good

https://github.com/raiyni/example-plugin/blob/bank-screenshot/src/main/java/io/ryoung/bankscreenshot/BankScreenshotPlugin.java#L75

**Comment by doppy2023** [comment]
thank you for your patience boss

**Pull request merged**
