### PR TITLE
Create gim-buddy

### PR DESCRIPTION
**Pull request by fNudz**
Created gim-buddy

### CODE REVIEW

**Comment by YvesW** [comment]
@GarrettJhnsn https://github.com/runelite/plugin-hub/pull/6330#issuecomment-2238010494

**Comment by iProdigy** [comment]
`ImageIO.read(new File("src/main/resources/icon.png"))` would not work in production as explained here: https://github.com/runelite/plugin-hub?tab=readme-ov-file#plugin-resources

(you should switch to `ImageUtil.loadImageResource`)

**Comment by LlemonDuck** [comment]
You should gitignore the bin/ folder which appears to contain the compiled project (which isn't the default gradle build location, so I'm not sure how you ended up with it there anyway)

Make sure you also remove it after adding it to the gitignore
```
git rm -rf --cached bin
```

**Comment by Unmoon** [comment]
I think you need to add a warning like [this](https://github.com/runelite/plugin-hub/blob/master/plugins/tts) since it's possible to configure the plugin to send data outside your computer.

**Comment by MESLewis** [comment]
Marking as draft for now. Please make the requested changes, then mark the plugin as ready for review.

**Comment by LlemonDuck** [comment]
closing as the above comments have not been resolved yet. feel free to resubmit when they are

**Pull request closed without merging**
