### PR TITLE
Plank Alerts Plugin

### PR DESCRIPTION
**Pull request by ANWAQ**
Plugin to screenshot deaths during COX / TOB raids and post them to a discord webhook.

### CODE REVIEW

**Comment by Adam-** [comment]
You should be using the provided okhttp client via `@Inject OkHttpClient client` instead of making your own.

**Comment by ANWAQ** [comment]
> You should be using the provided okhttp client via `@Inject OkHttpClient client` instead of making your own.

Thanks! First time contributing, let me know if that looks good.

**Comment by raiyni** [comment]
This exists as `discord-death-notifications` already?

**Comment by ANWAQ** [comment]
I didn't know about that plugin, and I did my research on this as well, as I mention in my plugins readme there already exists a `raidshamer` plugin that does something similar but that project seems to be abandoned and lacks lots of functionality.

My plugin differs from `discord-death-notifications` in that it:

- Is specific to raids
- Captures deaths of any person in your raid, not just your own character
- Adds additional data about what room in the raid the death occurred

I have plans of updating it to keep track of how many points each death lost the group as well, and possibly other changes and raids 3 integration in the future. I can agree there shouldn't be 3 separate discord webhook death notifiers in the plugin hub, I think `discord-death-notifications` can maintain it's role as a generic, runescape wide death notifier, but my plugin would now supersede `raidshamer` and make it obsolete (I wouldn't mind just submitting my updates into raidshamer where they rightfully belong, but there is already a year old stagnant PR to just add COX support).

**Comment by raiyni** [comment]
This would be a good candidate to merge into/take over `raidshamer` I think. They have a small established user base of ~2k people.

**Comment by ANWAQ** [comment]
Totally agree with you, are you suggesting I rename this plugin to raidshamer so any future downloads go to my repo instead of the old one, or how would such a change be implemented?

**Comment by ANWAQ** [comment]
@raiyni Any updates on this?

**Comment by Nightfirecat** [comment]
His suggestion is that you submit this feature as a change to https://github.com/ejedev/raidshamer, and ejedev would push that as an update to the available hub plugin to be included for users who already have that plugin installed.

**Comment by ANWAQ** [comment]
> His suggestion is that you submit this feature as a change to https://github.com/ejedev/raidshamer, and ejedev would push that as an update to the available hub plugin to be included for users who already have that plugin installed.

That project has been abandoned, as I said above.

**Comment by Nightfirecat** [comment]
They seem to be active on GitHub, just not on that repository. I'd be fine with you taking ownership of that plugin with their permission. @ejedev, are you fine with that?

**Comment by ejedev** [comment]
@Nightfirecat Apologies for the delay, that is fine with me. I unfortunately don't have time to maintain it anymore.

**Comment by jack0lantern** [comment]
Bumping this thread since I'm looking to add TOA support to this plugin. @ANWAQ are you still looking to take over the plugin?

**Comment by jack0lantern** [comment]
@Nightfirecat I've been in conversation with @ejedev and he said it'd be cool for me to take over if @ANWAQ isn't able to

**Comment by Nightfirecat** [comment]
Raidshamer has been updated by @jack0lantern to include TOA, so this is effectively done in my eyes.

**Pull request closed without merging**
