### PR TITLE
Create hide-and-seek-tracker

### PR DESCRIPTION
**Pull request by jeromkiller**
This plugin is to be used by the hiders during the Hide and Seek (GieliGuessr) events hosted on the official osrs discord server.

Hiders setup their tracking area around them, enter the list of participants and hide somewhere.

Hint images are sent out over discord every couple of minutes

when participants find the hider and enter the tracking area their placement and number of hints posted will be logged.
The placement of players and their amount of hints used can be coppied to the clipboard for easy sharing with the host

afbeelding

afbeelding

### CODE REVIEW

**Comment by jeromkiller** [comment]
Added a button to export the names of players in the capture area to the clipboard. So its easier to make and share the participant list

**Comment by raiyni** [comment]
Looks g2g after log.info calls are removed

**Comment by jeromkiller** [comment]
Removed the log.info calls when starting and stopping 👍

**Comment by jeromkiller** [comment]
Thank you so much for the review and merge!
Our hosts used the plugin during our previous event last sunday and were very pleased with the plugin.
I'm very eager to develop the plugin further 👍

**Pull request merged**
