### PR TITLE
Add "ABC Alchemy" plugin. 

### PR DESCRIPTION
**Pull request by vartan**
This plugin includes 2 major features:

1. An overlay that highlights the intersection between the alchemy spell and the optimal inventory slot.
2. A sidebar panel that shows the most profitable items to alch. All prices use RuneLite APIs.

### CODE REVIEW

**Review by majed08 — APPROVED** [review]

**Comment by Nightfirecat** [comment]
[Your panel icon is too large](https://github.com/vartan/abc-alch/blob/2d95b078a5d90ea78387ed0ce5f302e5d67bc81f/src/main/resources/icon.png). Although it is resized visually for the sidebar button, it takes up memory per pixel when read by Java. Please scale it down.
Code LGTM otherwise

**Comment by vartan** [comment]
Done! thanks for taking the time to review :)

**Comment by Nightfirecat** [comment]
You resized the wrong icon. You resized [assets/icon.png](https://github.com/vartan/abc-alch/blob/master/assets/icon.png) which isn't packaged with your plugin. [src/main/resources/icon.png](https://github.com/vartan/abc-alch/blob/master/src/main/resources/icon.png), which is actually shipped with your code, remains too large.

**Comment by vartan** [comment]
you are correct, sorry.

**Pull request merged**
