### PR TITLE
Update blue-prox-chat to 2.0

### PR DESCRIPTION
**Pull request by ThatGamerBlue**
long time no see i forgot most of this already

### CODE REVIEW

**Comment by Nightfirecat** [comment]
Can you not do this please? [ThatGamerBlue/osrs-prox-chat@`57012d8dec844bcd26eb07b4a18535c32b0b7e7b...ThatGamerBlue:5aa57d4fe6cda42113efe0b1934ed39de4df540d`#diff-559e52ec20](https://github.com/ThatGamerBlue/osrs-prox-chat/compare/57012d8dec844bcd26eb07b4a18535c32b0b7e7b...ThatGamerBlue:5aa57d4fe6cda42113efe0b1934ed39de4df540d#diff-559e52ec200dc4bf223730ed1352ec1ead5fe9c96014383a9a990b4c7d52072dR81)>

**Comment by ThatGamerBlue** [comment]
> Can you not do this please? [ThatGamerBlue/osrs-prox-chat@`57012d8dec844bcd26eb07b4a18535c32b0b7e7b...ThatGamerBlue:5aa57d4fe6cda42113efe0b1934ed39de4df540d`#diff-559e52ec20](https://github.com/ThatGamerBlue/osrs-prox-chat/compare/57012d8dec844bcd26eb07b4a18535c32b0b7e7b...ThatGamerBlue:5aa57d4fe6cda42113efe0b1934ed39de4df540d#diff-559e52ec200dc4bf223730ed1352ec1ead5fe9c96014383a9a990b4c7d52072dR81)>

That only runs on the server side where there is no other instance of gson to get from the injector

**Comment by LlemonDuck** [comment]
This code is still going to be included in the jar distributed on the plugin hub. You should separate these into two projects if they are unrelated.

**Comment by ThatGamerBlue** [comment]
> This code is still going to be included in the jar distributed on the plugin hub. You should separate these into two projects if they are unrelated.

Splitting into 2 projects: I'd have to set up a maven repo to host the client side because shared code would have to go in there otherwise you can't build the server, so if you want to host that or pay for it, be my guest.

Splitting into 3 projects: same issue as 2 projects, and it'd require a new repo added to the hub, so not happening either.

Ignore the CI: Get complained at that it fails CI.

This: get complained at that there's reflection.

What you want me to do?

**Comment by iProdigy** [comment]
Consider using multi-project gradle builds and jitpack to separate server & client code without incurring financial costs

**Comment by MESLewis** [comment]
Git submodules will let you include the client code in your server code without putting any server code in the jar. Or you can use the free tier of GitHub packages.

**Comment by ThatGamerBlue** [comment]
i made it not run the server build if its compiling for the plugin hub i hope this is ok

**Pull request merged**
