### PR TITLE
Add Group Ironmen Tracker plugin

### PR DESCRIPTION
**Pull request by christoabrown**
Sends character information for group ironmen where other members can view. Groups will need to go to the site to create a new group and are provided with credentials for login and sending the data.

[groupiron.men](https://groupiron.men/)  
Demo of what it looks like logged in is also available: [Demo](https://groupiron.men/demo)

This version sends the following information, all of it is encrypted before being stored:
* Inventory, bank, equipment, and shared bank
* HP, prayer, energy, and world
* World position
* Skill XP
* Quest states  

Source code for the server and frontend is here:
[https://github.com/christoabrown/group-ironmen](https://github.com/christoabrown/group-ironmen)

It seems somewhat similar to the other tracker plugins, although I believe having a public server with a DB and login credentials sets it apart. I do also intend to add more features like more inventories, achievement diaries, etc.

### CODE REVIEW

**Comment by Nightfirecat** [comment]
As far as I'm concerned, the `warning` you've added isn't needed--no requests are sent without making configuration changes.

You should set a unique user agent for this plugin for requests it submits.

**Comment by christoabrown** [comment]
I removed the warning and included the custom user agent.

**Comment by Nightfirecat** [comment]
You don't need to make a whole new Okhttp client, just add `.header("User-Agent", USER_AGENT)` in your request builders.

**Comment by christoabrown** [comment]
That's what I tried at first, but wherever this client is being built it is adding its own user-agent header before sending the request. I am not super familiar with the runelite code, but I am guessing it is here the interceptor is added which overrides the header:
https://github.com/runelite/runelite/blob/master/runelite-client/src/main/java/net/runelite/client/RuneLite.java#L439

**Comment by Adam-** [comment]
> That's what I tried at first, but wherever this client is being built it is adding its own user-agent header before sending the request. I am not super familiar with the runelite code, but I am guessing it is here the interceptor is added which overrides the header: https://github.com/runelite/runelite/blob/master/runelite-client/src/main/java/net/runelite/client/RuneLite.java#L439

This is a bug which I've fixed https://github.com/runelite/runelite/commit/c40b33a1e988b344f3e59ff2659cf26cfb752422

**Comment by christoabrown** [comment]
Thanks for the fix. I changed it so it now uses @Nightfirecat's suggestion with setHeader which I expect will start working in a future runelite release.

**Pull request merged**
