### PR TITLE
Create ruby-bolt-spec-counter

### PR DESCRIPTION
**Pull request by yototheg**

### CODE REVIEW

**Comment by cdfisher** [comment]
Does this do anything that the existing plugin "Bolt proc counter" doesn't already do?

**Comment by yototheg** [comment]
> Does this do anything that the existing plugin "Bolt proc counter" doesn't already do?
Didn't know that there was one, but this only specifically does Ruby bolts

**Comment by raiyni** [comment]
That doesn't really answer the question.

**Comment by MESLewis** [comment]
<https://runelite.net/plugin-hub/show/ruby-counter> seems to already cover this functionality. If there is functionality missing then that should be PR'ed to the Bolt Proc Counter plugin repo.

**Pull request closed without merging**
