### PR TITLE
My mommy dom plugin

### PR DESCRIPTION
**Pull request by Rain-Gayming**
A silly plugin i made to praise you

### CODE REVIEW

**Comment by Rain-Gayming** [comment]
I added a description

**Review by Rain-Gayming — COMMENTED** [review]
Added description

**Comment by LlemonDuck** [comment]
_Sigh..._ This is pretty low effort and niche, so I can't say we'll merge it if you fix this, but plugin.properties' `plugins` needs to point to your plugin class. 
```
plugins=com.mommy.MommyPlugin
```

**Comment by raiyni** [comment]
I don't think we would want to add an overtly sexual plugin like this. There are other plugins you can use to reword NPCs iirc

**Comment by iProdigy** [comment]
You could replicate this plugin using [Watchdog](https://runelite.net/plugin-hub/show/watchdog) and (optionally) submit the configuration to their [Alert hub](https://github.com/adamk33n3r/runelite-watchdog?tab=readme-ov-file#alert-hub) for others to use

**Pull request closed without merging**
