### PR TITLE
 Update world-finder

### PR DESCRIPTION
**Pull request by Conrad33**
Fixed 'Plugin is incompatible and requires its author to update' error that was caused by breaking change of WORLDHOPPER_FAVORITE_1 and WORLDHOPPER_FAVORITE_2

### CODE REVIEW

**Comment by Cgende** [comment]
Ah I see it failed, I'll fix soon and reopen

**Comment by YvesW** [comment]
FYI you don't have to close your PRs. If it's failing the checks, it won't be merged. If you want to, you can mark your PR as draft though.

**Comment by Cgende** [comment]
OK, I'll keep it open. Thanks for the info!

**Comment by Conrad33** [comment]
It says 'non-author plugin change' but I am the author, I assume its because I changed my github account name

**Comment by Felanbird** [comment]
Correct, if you update the repo link to your new name that will go away

**Pull request merged**
