### PR TITLE
Add visible wealth plugin

### PR DESCRIPTION
**Pull request by Emmsii**

### CODE REVIEW

**Comment by Nightfirecat** [comment]
I'm concerned that this plugin would be used by scammers or lurers to scout potential targets.

**Comment by Emmsii** [comment]
Is it not similar to the [equipment inspector plugin](https://runelite.net/plugin-hub/show/equipment-inspector) which allows you to see and value the equipment individual players are wearing?

For example
image

**Comment by Felanbird** [comment]
Being able to see someones wealth and immediately being told when a rich person walks by, are 2 completely different things.

**Comment by Emmsii** [comment]
Ah that's very true. Fair enough

**Pull request closed without merging**
