### PR TITLE
Skills Generator

### PR DESCRIPTION
**Pull request by MakingStan**
A plug-in that gives you tasks to do. An excellent plug-in when you have nothing to do.

Overlay
Schermafbeelding 2021-11-03 om 14 23 56

Panel
Schermafbeelding 2021-11-03 om 14 08 33

### CODE REVIEW

**Comment by LlemonDuck** [comment]
Your branch here isn't rebased and has conflicts

**Comment by MakingStan** [comment]
I don't have the option to fetch my BoredGenerator branch. Can this have something to do while its in a pull request? Or is there another easy way to rebase by branch? 
Sorry if these are noobie questions. Not that familiar with github.

**Comment by Nightfirecat** [comment]
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/about-merge-conflicts

**Comment by MakingStan** [comment]
Thanks I read that but my conflicted file is the new commit hash and the new repository url. So I don't understand what's wrong.

**Comment by LlemonDuck** [comment]
First add the runelite repo as a remote to your local repo. If it says it already exists during add that's fine, fetch to update your references:
```
git remote add upstream https://github.com/runelite/plugin-hub.git
git fetch upstream
```

Now either do the correct, or quick-and-dirty fix:

"Correct" fix by going through the merge process:
```
git rebase -i upstream
# walk through the prompts until it tells you there are conflicts
# resolve the plugins/boredgenerator file to the intended version
git rebase --continue
git push --force # need --force since this is overwriting remote history
```

Quick-and-dirty fix via discarding your changes, rebasing, and redoing your changes:
```
git reset --hard upstream/master
# edit plugins/boredgenerator to intended values
git add plugins/boredgenerator
git commit -m "your commit msg here"
git push --force # need --force since this is overwriting remote history
```

**Comment by MakingStan** [comment]
Sorry i think i am here at the wrong place because i just want to update my plug-in.

**Pull request merged**
