### PR TITLE
Add Rasta HUD plugin

### PR DESCRIPTION
**Pull request by Beardedrasta**
I changed the error that was being displayed to the updated code.

### CODE REVIEW

**Comment by raiyni** [comment]
Don't open new pr's in the future, commit to the same branch.

**Comment by Beardedrasta** [comment]
Ok ill make note of that. How will i know when it gets added. I cant currently use it because i use a jagex account and cant login to my client to use the plugin?

**Comment by geheur** [comment]
https://github.com/runelite/runelite/wiki/Using-Jagex-Accounts

**Comment by Beardedrasta** [comment]
Thank you ill go and check that out and use that. This first time ive ever done this thanks for the responses. Will it ever become usable by others. Or is there a way i can let my mate use it?

**Comment by AbusiveTuna** [comment]
> Thank you ill go and check that out and use that. This first time ive ever done this thanks for the responses. Will it ever become usable by others. Or is there a way i can let my mate use it?

Once/if your plugin is approved it is available to everyone using runelite. You would simply install it from the plugin-hub like any other plugin-hub plugin. (Quest helper, 117HD, etc.). Usually takes a few weeks to get reviewed and approved.

**Comment by Beardedrasta** [comment]
Updated RastaHUD with a ton of new features and fixes.

**Pull request merged**
