### PR TITLE
Create pet-the-capybara

### PR DESCRIPTION
**Pull request by Droei**
Simple plugin making it possible for users to pet a capybara and say a cute message on the client side.

### CODE REVIEW

**Comment by Droei** [comment]
Its my first time working with these checks, I'll close and retry with a fix for the error!

**Comment by Nightfirecat** [comment]
FYI you do not need to close this PR; just push updated commits which fix the errors, and we'll review it once it's passing CI

**Comment by Droei** [comment]
Alright I'll keep trying, thanks a lot! (Sorry if this is giving notifications)

**Comment by raiyni** [comment]
This can be reduced to use `MenuEntryAdded` if you care enough.

**Comment by Droei** [comment]
I'd be up to improve the code anytime, its a big learning curve for me!
Do you by any chance know a plugin that uses the constructor so I can look into it?

**Comment by YvesW** [comment]
It's generally best to clone core and check out some core plugins. Ctrl+shift+f in IJ

**Comment by raiyni** [comment]
My first comment is still valid.

**Comment by Droei** [comment]
Ooh I'll look into that tomorrow, I kinda have an idea what you mean but not completely!
If you could clarify what you mean that would help a lot!

**Comment by cdfisher** [comment]
> Ooh I'll look into that tomorrow, I kinda have an idea what you mean but not completely! If you could clarify what you mean that would help a lot!

Your package should be called something like `com.droei.petthecapybara`

**Pull request merged**
