### PR TITLE
Create loot-splitter

### PR DESCRIPTION
**Pull request by LanaDelSlay**
Plugin to display how many items/GP value to split when bossing!

### CODE REVIEW

**Comment by raiyni** [comment]
You should convert your Sysout and info logs into debug logs. And FWIW, you can use regex to parse the text instead of what you are doing.

**Comment by LanaDelSlay** [comment]
I just fixed those, and changed the commit number inside the plugins folder, do I need to create a new pull request now, or can I keep this one. lol regex seems like a way simpler solution, I'll implement it a bit later :)

**Comment by raiyni** [comment]
No, if you push the new commit hash--the bot will update it's comment.

**Review by raiyni — APPROVED** [review]

**Comment by LanaDelSlay** [comment]
Awesome, thank you!!

**Comment by raiyni** [comment]
I wanted the runner to execute but I don't think my status counts. You need a license file too.

**Comment by LanaDelSlay** [comment]
I think it has a license already, does this look correct?

https://github.com/LanaDelSlay/LootSplit/blob/main/LICENSE

**Comment by raiyni** [comment]
That's good yes, I missed it on my files.

**Pull request merged**
