### PR TITLE
Add Spec Jingle plugin

### PR DESCRIPTION
**Pull request by Servilabs**
Notifies user when special attack energy regenerates to a threshold within a user specified list.

### CODE REVIEW

**Comment by Bram91** [comment]
Keep pushing changes to the same branch to fix your build errors, you don't need to open new PRs or close/reopen them.

**Comment by Servilabs** [comment]
the branch of the plugin hub or of my original repo ?

**Comment by Bram91** [comment]
The plugin hub branch, if you update the commit hash in plugins/spec-jingle it will get picked up here

**Comment by Servilabs** [comment]
oh right, thanks!

**Pull request merged**
