### PR TITLE
Update ba-minigame to v1.42

### PR DESCRIPTION
**Pull request by BegOsrs**
- Change chat command to use lookup + submit
- ~~Disable chat commands until support is not merged into runelite master: https://github.com/runelite/runelite/pull/14029~~
Migrating chat command to the chat commands plugin

### CODE REVIEW

**Comment by raiyni** [comment]
This commit just comments out a bunch of code, is that the one you meant to use?

**Comment by BegOsrs** [comment]
I commented it because its not working properly. I was going to wait a merge request to be accepted on runelite master which i needed to fix it. But i've decided to try to get the chat command approved there aswell. 
I'll remove all commented code.

**Comment by raiyni** [comment]
That's not what I'm asking. You left a note, `Change chat command to use lookup + submit` and there is no code change for that

**Comment by BegOsrs** [comment]
That change was on the commented code. I couldn't implement it yet without this commit https://github.com/runelite/runelite/pull/14029/commits/891066757337e0eeafde7f630c247d4d8bf893d1 merged into runelite master.
But now that i've decided to try to get the chat command merged there too, i've removed all code related to it on this plugin

**Pull request merged**
