### PR TITLE
DiscordThreads plugin addition

### PR DESCRIPTION
**Pull request by RumbleCrumbleRS**
DiscordThreads is a achievement discord plugin that will through Webhook submit an achievment such as Level-Up, Collection Log, Combat Achievement, etc. 

The big difference between any of the others is this plugin is capable of posting the achievement to a Discord Threads/Forum, additionally you can specify tags both on the header and per achievement in which they can automatically be tagged.

This first image shows what they look like when the achievement is posted to a threads/forum
RLPlugin1

Second image shows what it looks like when you click into one of the threads
RLPlugin2

Third image shows off the tagging system
RLPlugin3

### CODE REVIEW

**Comment by cdfisher** [comment]
I'm fairly certain you can post to threads with any of the other Discord webhook plugins if you add the thread ID to the URL.

**Comment by RumbleCrumbleRS** [comment]
> I'm fairly certain you can post to threads with any of the other Discord webhook plugins if you add the thread ID to the URL.
This CREATES a thread not just posts to an existing thread with ?thread_id=
Additionally has functionality since its creating a thread to also associated the created thread with tags.

**Comment by raiyni** [comment]
If this doesn't exist in dink, it's better to add it there.

**Comment by iProdigy** [comment]
> This CREATES a thread not just posts to an existing thread

[Dink](https://runelite.net/plugin-hub/show/dink) can also do this by specifying `?forum` - we'd also be willing to add `applied_tags` support

**Comment by Felanbird** [comment]
Fwiw the reason we don't have thread tagging in Dink is because Discord did not have it documented as an available feature when it was last requested (August 2023)

**Comment by RumbleCrumbleRS** [comment]
> Fwiw the reason we don't have thread tagging in Dink is because Discord did not have it documented as an available feature when it was last requested (August 2023)

I push through custom_json including thread_name as well as applied_tags.

**Comment by iProdigy** [comment]
Yes, Dink is purely webhook and automatically populates `thread_name` when necessary - we're willing to add `applied_tags` support (or are open to PRs)

**Comment by RumbleCrumbleRS** [comment]
> Yes, Dink is purely webhook and automatically populates `thread_name` when necessary - we're willing to add `applied_tags` support (or are open to PRs)

As a user I dont have to get a dink bot on our discord server in order to use the webhook correct? Also I dont see a dink plugin on runelite?

**Comment by iProdigy** [comment]
> As a user I dont have to get a dink bot on our discord server in order to use the webhook correct? 

Correct

> Also I dont see a dink plugin on runelite?

https://runelite.net/plugin-hub/show/dink

**Comment by RumbleCrumbleRS** [comment]
So what this plug-in offers is the ability to have tags working as of today
it sounds like.

**Comment by raiyni** [comment]
This feature is being added to dink and will supersede this plugin.

**Pull request closed without merging**
