### PR TITLE
Create tickcounter

### PR DESCRIPTION
**Pull request by Pojken-Arn**
Adds a visual customisable tick counter.
Can help keep track of ticks and help you with prayer-flicking.

### CODE REVIEW

**Comment by YvesW** [comment]
Any reason you did not contribute to https://github.com/NathanQuayle/visual-ticks ?

**Comment by Pojken-Arn** [comment]
@YvesW Well I don't mind contributing to https://github.com/NathanQuayle/visual-ticks, I just had some ideas for features and more customisble settings and didn't wanna clutter an already existing plugin, espacially when I hope to implements some more features in the near future aswell. If you think it would be better for me to contribute an already exsisting plugin then I don' t mind it.

**Comment by YvesW** [comment]
If possible, we generally recommend people to contribute to already existing plugins as to not end up with the 10 discord plugins situation that we have right now, and because that plugin already has a userbase. Thus, more people might use your improvements. It's just that you might have to be a bit more conservative with enabling stuff by default if you already got a bigger install base.

**Comment by Pojken-Arn** [comment]
@YvesW Okay sounds good 👍

**Pull request closed without merging**
