### PR TITLE
Create highlight-stackable-items

### PR DESCRIPTION
**Pull request by horse4lunch**
Highlights any drops you get that can be stacked with items in your inventory
Example. If you have fire runes in your inventory and get a fire rune drop they will be highlighted.

### CODE REVIEW

**Comment by raiyni** [comment]
You need to move your file into the plugins for

**Comment by horse4lunch** [comment]
> You need to move your file into the plugins folder

Damn sorry, Got it fixed now I think.

**Comment by Nightfirecat** [comment]
Please don't [check spawned items and config values every client tick](https://github.com/horse4lunch/highlight-stackable-items/blob/b2fb024ab4963fb7b7c0aba6e71c7e61d5c9b14b/src/main/java/com/HighlightStackables/HighlightStackablesPlugin.java#L92), run this code on game ticks instead.

Also it looks to me like this plugin will leave the ground items plugin's configuration in an incorrect state if you close your client, since `shutDown()` will not be called. You should take care to reset it on ClientShutdown as well as plugin shutDown.

**Comment by horse4lunch** [comment]
> Please don't [check spawned items and config values every client tick](https://github.com/horse4lunch/highlight-stackable-items/blob/b2fb024ab4963fb7b7c0aba6e71c7e61d5c9b14b/src/main/java/com/HighlightStackables/HighlightStackablesPlugin.java#L92), run this code on game ticks instead.
> 
> Also it looks to me like this plugin will leave the ground items plugin's configuration in an incorrect state if you close your client, since `shutDown()` will not be called. You should take care to reset it on ClientShutdown as well as plugin shutDown.

Made the needed changes and added a loop to remove items from Uniquelist. Should be good to go now.

**Pull request merged**
