### PR TITLE
[New Plugin] - What Pet is that Anyway - v1.0.0 - Sololegends

### PR DESCRIPTION
**Pull request by sololegends**
# What Pet is that Anyway

Adds an on-hover tooltip for everyone's `!pets` command so you can see what the heck those little icons actually are.

### CODE REVIEW

**Comment by LlemonDuck** [comment]
This seems like a good contribution to core if you have not already PR'd it there.

**Comment by sololegends** [comment]
I was going to, but it seemed some build reqs locked behind a repo I didn't have access to.

**Comment by LlemonDuck** [comment]
The core client can be built just fine off the runelite/runelite repository.

https://github.com/runelite/runelite/wiki/Developer-Guide

**Comment by sololegends** [comment]
I'll try to work through it again, I went through that doc and during the maven build it tried to access a maven repo which kept returning a 403.

**Comment by sololegends** [comment]
Submitted a pr with this just in the chat commands core plugin 

https://github.com/runelite/runelite/pull/18442

**Comment by LlemonDuck** [comment]
@sololegends We can go ahead and merge the hub plugin version here for now if you want to pull your recent changes back over, and if the core PR gets renewed attention later then that can be separate.

**Comment by sololegends** [comment]
I publish every jar by ci to a central repo I control as an easy way for me to pull down whatever I need easily. I do this for every project I create.  

I'll rip it out tomorrow, I'll just have a different upstream.

**Comment by raiyni** [comment]
You can already do that with an action you make on your repository

**Pull request merged**
