### PR TITLE
Added Splitter plugin

### PR DESCRIPTION
**Pull request by gustav901**
Splitter adds a chat command to get the split amount of the gold (coins or platinum) in the players inventory or by searching by item.
Functionallity does NOT overlap with Loot Splitter.

### CODE REVIEW

**Comment by Enriath** [comment]
Given that chat commands are for sharing information, and this doesn't share information, this should be a `::command`. if you intended it to share information, you've not done that correctly.

**Comment by gustav901** [comment]
> Given that chat commands are for sharing information, and this doesn't share information, this should be a `::command`. if you intended it to share information, you've not done that correctly.

I did not consider if it should be shared or private information. Personally I would only use it for personal information but I could see how it might be good to have it as public information.
Could you point me in the right direction to read more about `::command`?

**Comment by Enriath** [comment]
I mentioned it since quite often, newer devs will make `!commands` either for things that are just for the local player, which spams up chat, or they assume that it'll magically share to other clients despite them not implementing a server component for it.

`::commands` are awesome since they never even get into the chatbox, let alone to other clients; perfect for what you want to do.
Have a look at usage of the `CommandExecuted` event in the core client. Notable plugins that use it are Devtools and Clue Scroll, who both have dev commands that are *somewhat* simple.

**Comment by gustav901** [comment]
> I mentioned it since quite often, newer devs will make `!commands` either for things that are just for the local player, which spams up chat, or they assume that it'll magically share to other clients despite them not implementing a server component for it.
> 
> `::commands` are awesome since they never even get into the chatbox, let alone to other clients; perfect for what you want to do. Have a look at usage of the `CommandExecuted` event in the core client. Notable plugins that use it are Devtools and Clue Scroll, who both have dev commands that are _somewhat_ simple.

Alright, thanks! I'll look into and update it to use `::commands`.

**Comment by gustav901** [comment]
Changed from "!command" to "::command".

Only other change was to add an error message if no item was found (instead of having the message simply diappear).

**Comment by raiyni** [comment]
You need to change your config group and remove `log.info` calls

**Pull request merged**
