### PR TITLE
Create xp-grapher

### PR DESCRIPTION
**Pull request by cosmicquahog**
Adds a real time XP graph of the selected skill.

### CODE REVIEW

**Comment by cosmicquahog** [comment]
image

**Comment by cosmicquahog** [comment]
https://imgur.com/a/yXtiC66

**Comment by Nightfirecat** [comment]
According to someone who tested this, it apparently doesn't respect the overlay position when Alt+dragging it? Regardless, the code looks fine so I'll merge this.

**Comment by cosmicquahog** [comment]
> According to someone who tested this, it apparently doesn't respect the overlay position when Alt+dragging it? Regardless, the code looks fine so I'll merge this.

I have heard of people having issues with positioning but I cannot replicate them. Any screenshots would be greatly appreciated.

**Pull request merged**
