### PR TITLE
Update nature-runecraft-utilities

### PR DESCRIPTION
**Pull request by alex-macm**
fixed + added Sir Rebral option

### CODE REVIEW

**Comment by iProdigy** [comment]
you probably want to move the `teleportIdx == -1` check before `menuEntries[teleportIdx]` to avoid a `IndexOutOfBoundsException`: https://github.com/alex-macm/Nature-Runecrafting-Util/blob/97000c0b548af6de03b69dfa91fcf3f325afdf28/src/main/java/com/NatureRCUtil/NatureRCUtilPlugin.java#L87-L93

similarly, you don't have a bounds check on `jarrIdx`: https://github.com/alex-macm/Nature-Runecrafting-Util/blob/97000c0b548af6de03b69dfa91fcf3f325afdf28/src/main/java/com/NatureRCUtil/NatureRCUtilPlugin.java#L95

lastly you may want to `break;` here as a performance optimization: https://github.com/alex-macm/Nature-Runecrafting-Util/blob/97000c0b548af6de03b69dfa91fcf3f325afdf28/src/main/java/com/NatureRCUtil/NatureRCUtilPlugin.java#L112

**Review by iProdigy — APPROVED** [review]

**Review by geheur — APPROVED** [review]

**Comment by geheur** [comment]
Does this work with menu entry swapper? You are accessing menuentries.length - 2 which is static and may be different when you are in postmenusort, as you are now using an event that is after menu entry swapper has swapped menus.

**Comment by FredP1** [comment]
It doesn't work when swapping teleport to the top using MES. It's designed to function when the top value is set to Kaleb in the sub-menu teleport.

**Comment by halo145** [comment]
Not fixed yet as of 22 AUG 2024 at 18:12 hrs. EST.

**Comment by alex-macm** [comment]
> Not fixed yet as of 22 AUG 2024 at 18:12 hrs. EST.

I've just tested it in game and it is fixed. Open a ticket on the plugin repo with more info and i will investigate when i get the chance.

**Pull request merged**
