### PR TITLE
Add Essence Running Plugin

### PR DESCRIPTION
**Pull request by AaronPoon**
Change the default shift option that is displayed when hovering over objects associated with essence running

### CODE REVIEW

**Comment by Nightfirecat** [comment]
Does this swap menu entries of teleport jewellery only in the inventory? I didn't see anything in the plugin code which would block that swapping from happening on the equipment tab.

**Comment by AaronPoon** [comment]
Yes it only does it in inventory. The user can configure what they want shift+click to be directly in the UI. The options available are an enum in: EssenceRunningItemShiftClick.java
Essentially only the options available while the items are in your inventory.

Swapping options while equipped are different (ex. Glory would should Edgeville, Draynor VIllage, etc).

**Comment by AaronPoon** [comment]
I did some more testing since your comment got me thinking for the case of Crafting Cape where in both Inventory & Equipped, it is called "Teleport". I did a print and found out that, the format for equipped menuEntries on a equipped item is different than an item in the inventory:

Equipped
option: examine, identifier: 10, type: 1007
option: teleport, identifier: 3, type: 57
option: boost, identifier: 2, type: 57
option: remove, identifier: 1, type: 57

Inventory
option: use, identifier: 9781, type: 38
option: teleport, identifier: 9781, type: 35
option: wear, identifier: 9781, type: 34
option: drop, identifier: 9781, type: 37
option: examine, identifier: 9781, type: 1005

My code relies on the fact that the default entry for an item in Inventory is always the one before the "examine", hence my swapPrevious() code. However, for an Equipped item, it seems the examine will always be the first entry. Thus, swapPrevious will always do nothing since the entry before "examine" is nothing.

**Comment by abextm** [comment]
You should add an explicit check to block that anyway

**Comment by AaronPoon** [comment]
I can add the priority check for the type since it looks like the same logic as swapBankOp. Unless you know of some other way to check if an item is in inventory vs equipped.

**Comment by AaronPoon** [comment]
Updated so rather than checking
`option.equals("examine")`, it now checks
`menuEntry.getType() == MenuAction.EXAMINE_ITEM.getId()`
which guarantees the MenuAction is from within the inventory.

**Pull request merged**
