### PR TITLE
Create goblin-scape-clan-plugin

### PR DESCRIPTION
**Pull request by s0lved**
Plugin used to track clan activities for Goblin Scape Clan Members. This currently tracks clan members world map locations and then sends the data to our website on a virtual world map. We will be using this website for clan events throughout leagues and other upcoming events.

### CODE REVIEW

**Comment by Felanbird** [comment]
Don't open new pull requests if you run into a build error, just resolve it with a new commit to this PR

**Comment by s0lved** [comment]
> Don't open new pull requests if you run into a build error, just resolve it with a new commit to this PR

Is there a build error?

**Comment by Felanbird** [comment]
**_if_** - I didn't check the reason for the :x: on the previous PR, that's the most common reason why people randomly make new PRs.

I guess in your case I could have said "You can edit the PR description without requiring a new PR"

**Comment by YvesW** [comment]
1. What does this plugin do that other clan/clan activity/clan events plugins don't do? Does this plugin differ significantly?
2. Why is it clan specific? It's not that great to get 30 clan plugins that only work for 1 clan

**Comment by s0lved** [comment]
> 1. What does this plugin do that other clan/clan activity/clan events plugins don't do? Does this plugin differ significantly?
> 2. Why is it clan specific? It's not that great to get 30 clan plugins that only work for 1 clan

1. I haven't seen any other clan plugins that track clan members world map locations and then allows this data to be sent through an API? The only other one I've seen is for GIMs, however this plugin is limited to 5 members and is tailored to GIM accounts. I'm also planning to do a treasure hunt event with my clan, which would make major use of this plugin if a clan member reaches a certain title in the world, etc. 

Screenshot 2024-11-24 at 4 07 22 pm

2. I asked a few weeks ago in the discord if there would be an issue in building a clan specific plugin, I was told that this would be okay. It is clan specific as the API has been set up for my clan's server and website, however I'm happy to rename it to something more generic like "Clan World Map Locations". The only thing is clans will need to build their own API and website if they want to make use of it.

**Comment by s0lved** [comment]
Just checking in regards to my last comment, will i need to rename this plugin to something more generic with a disclaimer that an API is required to access the data? Or am I okay to leave it as it is? Thanks :)

**Comment by s0lved** [comment]
@Felanbird  @YvesW Just checking in regards to my last comment, will i need to rename this plugin to something more generic with a disclaimer that an API is required to access the data? Or am I okay to leave it as it is? Thanks :)

**Comment by s0lved** [comment]
> It's fine to leave it as is, we just prefer people contribute to existing plugins if possible.

Thanks @LlemonDuck that makes sense. When I have some more time on my hands, I'm happy to eventually create a public server for this plugin that other clans can use.

**Comment by YvesW** [comment]
@s0lved 
I asked my first question as I was wondering if this should be part of another plugin indeed, as I was wondering how much it differed from the already existing ``live location sharing`` plugin that it (and/or the web server) is forked of.

Regarding my second question, I personally think that it's really bad to make plugins that are clan specific. It causes pluginhub clutter with every clan creating their own plugin, and locks out cool functionality for other people for no apparent reason. Additionally, all those clan plugins could probably be consolidated in 1-2 plugins which could be improved by collaboration.
I imagine this is also nice for the plugin authors - you want people to install your plugin and benefit from it. For example the ``Clan events`` plugin started out as elysium-events; only to be used by 1 clan. It currently got about 64k active installs(!).
This is not meant as flame or whatever, as you invested time and made something that looks cool, but I do highly encourage you to make it configurable. Obviously the install base might not be as big as the ``clan events`` plugin as someone needs to host the server on a VPS, but other people might really enjoy using your plugin.

**Pull request merged**
