### PR TITLE
Drop Sounds plugin

### PR DESCRIPTION
**Pull request by MitzDK**
The drop sound plugin reads chat messages, specifically system messages, GIM messages or Clan messages, to determine if the player for a valuable drop (if it shows up in the chat), or whether they get an "Untradeable drop", that meets the list in the config. 
This plugin was heavily based off of m0bile btw's plugin, C Engineer, and I've had contanct with him and have had plenty help from his side, to develop this. :)

### CODE REVIEW

**Comment by LlemonDuck** [comment]
Your build is failing since the FQDN specified in runelite-plugin.properties (`com.github.mitzdk.dropsounds.DropSoundsCompletedPlugin`) doesn't match your actual plugin class (`com.github.MitzDK.DropSoundsCompletedPlugin`)

**Comment by MitzDK** [comment]
> Your build is failing since the FQDN specified in runelite-plugin.properties (`com.github.mitzdk.dropsounds.DropSoundsCompletedPlugin`) doesn't match your actual plugin class (`com.github.MitzDK.DropSoundsCompletedPlugin`)

Ty! I've tried fixing that now :) I had totally missed this

**Comment by Nightfirecat** [comment]
This plugin probably should not use C Engineer's logo as its icon, especially since it's not the C Engineer plugin

**Comment by MitzDK** [comment]
> This plugin probably should not use C Engineer's logo as its icon, especially since it's not the C Engineer plugin

Very good shout.. Ill fix that, another thing I totally blanked on. Will fix it immediatly.

**Comment by Nightfirecat** [comment]
[Change your config group as well](https://github.com/MitzDK/DropSounds/blob/037ec6f7b810664a622ce28f2026a3b50597d43a/src/main/java/com/github/MitzDK/DropSoundsConfig.java#L11)

**Pull request merged**
