### PR TITLE
Updated Emote Clue Items to v4.1.0.

### PR DESCRIPTION
**Pull request by larsvansoest**
This update features an update to the collection panel, which now allows marking STASH unit locations on the map and highlights construction-level requirements. What's more, highlights can now be toggled for each emote clue difficulty.

highlighting-a-stash-unit-location-on-the-map

This update of Emote Clue Items features the following updates.
* Added configuration options to toggle item highlighting for each emote clue difficulty.  (see [emote-clue-items#81](https://github.com/larsvansoest/emote-clue-items/issues/81))
* Added _mark map_ button to show STASH locations on the map. (see [emote-clue-items/pull83](https://github.com/larsvansoest/emote-clue-items/pull/83))
* The plugin panel now features a header instead of a footer (see [emote-clue-items/pull84](https://github.com/larsvansoest/emote-clue-items/pull/84))
* Updated to RuneLite version 1.9.9. (see [emote-clue-items/pull85](https://github.com/larsvansoest/emote-clue-items/pull/85))

### CODE REVIEW

**Comment by larsvansoest** [comment]
Closing pull request in advance for future patch.

**Comment by Felanbird** [comment]
> Closing pull request in advance for future patch.

What's stopping you from just turning this PR into the `Update Emote Clue Items to v4.1.1` PR? (or whatever version you choose)

**Comment by larsvansoest** [comment]
Not much, I just didn't want to spam the pull requests list. However, you are right, I will reopen the PR :)

**Comment by larsvansoest** [comment]
About to update this PR because it shipped a small bug.

**Comment by larsvansoest** [comment]
After thoroughly testing, the bug appeared to be no longer there.

**Comment by larsvansoest** [comment]
I have reopened the PR, it now also contains the following new feature:
* The plugin panel now features a header instead of a footer (see [emote-clue-items/pull84](https://github.com/larsvansoest/emote-clue-items/pull/84))

**Comment by larsvansoest** [comment]
* Updated to RuneLite version 1.9.9. (see [emote-clue-items/pull85](https://github.com/larsvansoest/emote-clue-items/pull/85))

**Comment by larsvansoest** [comment]
This version is now final, and ready to be merged

**Comment by LlemonDuck** [comment]
Please remove any WorldMapPoints in your plugin's shutDown https://github.com/larsvansoest/emote-clue-items/compare/8f71eb21731aa02b32b62a710be0b4c5eb9000bc...larsvansoest:bebf1a0f4ab5947d86b039c79db15d315fc51aa5#diff-a867371294abf71c2829504b1e7ac2248735fa672b209496a9e0e036d1d20e67R92

**Comment by larsvansoest** [comment]
@LlemonDuck Thanks for pointing that out! I just fixed this issue and included the commit in this PR.

**Pull request merged**
