### PR TITLE
Create crosshair-cursor

### PR DESCRIPTION
**Pull request by Thomas-gonzalez**
Minimal plugin that switches your OS' cursor type to crosshair.

### CODE REVIEW

**Comment by raiyni** [comment]
Custom Cursor already accepts custom images?

**Comment by Thomas-gonzalez** [comment]
But not cursor files, Custom Cursor only works with pngs.

**Comment by Thomas-gonzalez** [comment]
> Custom Cursor already accepts custom images?

And with images you are restricted to top-left click alignment, which doesn't work for something like a crosshair.

**Comment by iProdigy** [comment]
Avoid using `example` as your config group: https://github.com/Thomas-gonzalez/crosshair-cursor/blob/1a8c5da7e40a78beb307829a6c3bb0511ee38ceb/src/main/java/com/crosshaircursor/CrosshairCursorConfig.java#L7

**Pull request merged**
