### PR TITLE
Add Koivel Stat Tracking Dashboard Plugin 

### PR DESCRIPTION
**Pull request by koivel-admin**
A pretty simple plugin that tracks XP changes and sends them to our server. We then create dashboards tracking this data. This is really a V1 intended for testing and user feedback. In the future, we hope to add more trackers to allow for more complex graphs/stats. If you have any questions let me know, thanks for your time!

Site:
https://koivel.com

Demo:
https://koivel.com/dashboard/runelite-demo?userId=627e904615e08aef07420879

image
image
image
image
image
image
image

Public api:
https://app.swaggerhub.com/apis/koivel/koivel-api/1.0.0#/

### CODE REVIEW

**Comment by LlemonDuck** [comment]
Your plugin source compatibility should target Java 8

**Comment by koivel-admin** [comment]
> Your plugin source compatibility should target Java 8

Ah, thanks. Changed source and target compatibility to 1,8!

**Comment by zach-herridge** [comment]
If possible could someone approve the workflow so I can confirm it passes? Thanks!

**Comment by brerose** [comment]
are these graphs just going to be for personal use or will they be shareable?

**Comment by koivel-admin** [comment]
> are these graphs just going to be for personal use or will they be shareable?

Yeah, once the plugin is released you'll be able to generate shareable links to let your friends/whoever look at your dashboards. https://koivel.com/dashboard/runelite-demo?userId=627e904615e08aef07420879 is an example of a link for my RS accounts.

**Comment by koivel-admin** [comment]
switched the HTTP client based on feedback from other PRs

**Comment by koivel-admin** [comment]
Could someone approve the workflow again? Thank you! Also is there a general timeline of when new plugins get reviewed?

**Comment by koivel-admin** [comment]
Could someone approve the workfkow again. Thanks

**Comment by koivel-admin** [comment]
Would kind of prefer to add trackers as smaller PRs to limit the size of reviews but the cycle seems pretty long so will get those in from feedback.

**Comment by Nightfirecat** [comment]
LGTM. I recommend adding an `authors` tag to your plugin file to avoid having future PRs tagged with `[non-author-plugin-change]`.

**Comment by koivel-admin** [comment]
> LGTM. I recommend adding an `authors` tag to your plugin file to avoid having future PRs tagged with `[non-author-plugin-change]`.

Thanks a lot for taking a look! `author=koivel-admin` I added this in but it was after the bot added the tag so I don't think it went back and removed it.

**Comment by Nightfirecat** [comment]
The bot will remove the tag if you add `authors=koivel-admin` to the plugin file.

**Comment by koivel-admin** [comment]
hmm do I have it right on that commit? https://github.com/koivel/runelite-plugin/commit/c933a4b8daf8a4177354dcfee68fd73634dda0b0

**Comment by koivel-admin** [comment]
Sorry about that confused where you were directing me. Makes sense now!

**Pull request merged**
