### PR TITLE
Add fullscreentoggle plugin

### PR DESCRIPTION
**Pull request by willthehuman**
Add a plugin to toggle fullscreen mode.

### CODE REVIEW

**Comment by raiyni** [comment]
What's the difference in this plugin and the one that exists already?

**Comment by willthehuman** [comment]
You can toggle it via the sidebar, and it works on my steam deck. The existing one is buggy and you have to disable the custom chrome frame.

**Comment by Nightfirecat** [comment]
I'd recommend you not use Ctrl + F11 as your hotkey of choice, as that's already in use by the RuneLite configuration as the default sidebar toggle key.

**Comment by Nightfirecat** [comment]
Closing due to inactivity

**Pull request closed without merging**
