### PR TITLE
Add Magic Secateurs plugin

### PR DESCRIPTION
**Pull request by Ryanbarker0**
The plugin adds a notification when the magic secateurs are in inventory and not equipped. Acts as a reminder to equip them before harvesting crops on farm runs to maximize yield and XP.

### CODE REVIEW

**Comment by abextm** [comment]
its highly recommended to not set `enabledByDefault = false` on external plugins; it confuses people because they install the plugin and it does nothing by defaultt

**Comment by raiyni** [comment]
Fwiw, you can use the inventory changed event to see if secateurs are in the inventory instead of checking every render.

**Comment by basicDamen** [comment]
You can also utilize ItemId to grab the item’s id instead of hardcoding the value.

**Comment by Nightfirecat** [comment]
I'll echo what the others have said as well. We don't mind much the quality of the code in general, but removing `enabledByDefault = false` [and adding a LICENSE to the repo](https://github.com/runelite/plugin-hub#licensing-your-repository) should be done before we merge it.

**Pull request merged**
