### PR TITLE
Fix slash swapper

### PR DESCRIPTION
**Pull request by JZomDev**
Apparently the original owner left the project.

### CODE REVIEW

**Comment by Nightfirecat** [comment]
@pwatts6060 I know you said as much in #3752, but I assume you're cool with Zom taking ownership of this plugin? From what I see here, it'll be with an entirely fresh codebase

**Comment by pwatts6060** [comment]
> Provided it works yes that is fine

**Comment by pwatts6060** [comment]
Tested it now and it works well. Haven't tested for group ironman though who may have slightly different behavior.

**Comment by JZomDev** [comment]
1.9.8 is now out, so this is ready for release.

**Pull request merged**
