### PR TITLE
RuneLite Wilderness Plugin

### PR DESCRIPTION
**Pull request by ItsRemer**
A plugin for the wilderness

### CODE REVIEW

**Comment by YvesW** [comment]
1. Please don't close and open new prs. You can push your updated hash to your current branch and the bot will pick it up plus checks will run.
2. Level-based PvP player indicators / flashing / scout plugins are part of the declined features https://github.com/runelite/runelite/wiki/Rejected-or-Rolled-Back-Features 
3.  Any reason you did not collaborate with https://runelite.net/plugin-hub/show/wilderness-player-alarm ? The plugin does exactly the same, minus the banned features AFAIK.

**Comment by ItsRemer** [comment]
Thank you for bringing up the "Wilderness Player Alarm" plugin. My plugin, "Wilderness Alerts," differs primarily in that it specifically notifies players only if another player can actually attack them in the wilderness, based on combat levels and wilderness depth. This focus on relevant threats reduces false alarms and provides targeted alerts. While I didn’t collaborate on the existing plugin, I aimed to fill a small group of players needs based on what they requested.

and yeah after closing the first one I noticed that pushing makes the bot run the check,

**Comment by YvesW** [comment]
> Thank you for bringing up the "Wilderness Player Alarm" plugin. My plugin, "Wilderness Alerts," differs primarily in that it specifically notifies players only if another player can actually attack them in the wilderness, based on combat levels and wilderness depth. This focus on relevant threats reduces false alarms and provides targeted alerts. While I didn’t collaborate on the existing plugin, I aimed to fill a small group of players needs based on what they requested.
> 
> And yeah after closing the first one I noticed that pushing makes the bot run the check,

Yes, the difference between your plugins is indeed that one has banned features and the other one does not.

**Comment by ItsRemer** [comment]
Initially, I understood RuneLite's guideline against "Level-based PvP player indicators" to prohibit highlighting individual players based on level. My plugin, however, only reduces screen flashing, alerting only when a PvP threat within a relevant level range is near, without specifically targeting any players. This is intended to maintain game balance. If this approach still conflicts with the rules and community standards, I am willing to take the plugin down.

**Comment by Nightfirecat** [comment]
"Alerting only when a PvP thread is within a relevant level range" is covered on our rejected features page, quoted below, so we won't be accepting this plugin, sorry.

> Level-based PvP player indicators (eg. highlighting players who can be attacked, or are within X levels range)

**Pull request closed without merging**
