### PR TITLE
Create boostnotifier

### PR DESCRIPTION
**Pull request by rikbreukers**
Boost Notifier is a handy RuneLite plugin designed to keep track of your skill boosts. You can set up customizable level thresholds for different skills, and the plugin will send you alerts — even email notifications

### CODE REVIEW

**Comment by cdfisher** [comment]
Please don't close PRs and open new ones if there's an issue. Just push commits to the same branch.

Additionally, if I'm reading it correctly, this would store the user's email password in plaintext in their config, which would be a not-insignificant security concern.

**Comment by YvesW** [comment]
Additionally, could you remove your log.info calls, or replace them with log.debug calls? That way we won't have to read logs with a ton of spam in it.

**Comment by LlemonDuck** [comment]
What possible use case is there for email? It's not real-time, and I don't feel comfortable introducing that form of external communication.

**Comment by LlemonDuck** [comment]
closing as the above comments have not been resolved yet. feel free to resubmit when they are

**Pull request closed without merging**
