### PR TITLE
Add extended-api plugin

### PR DESCRIPTION
**Pull request by manmademagic**
This is a slightly more advanced version of  [Adam-'s HTTP Server Plugin](https://github.com/Adam-/runelite-plugins/tree/http-plugin)

It allows for changing ports, as well as exposing some extra data.

### CODE REVIEW

**Comment by Nightfirecat** [comment]
Is there any reason this isn't an update to that plugin instead of a completely separate plugin?

**Comment by manmademagic** [comment]
> 
> 
> Is there any reason this isn't an update to that plugin instead of a completely separate plugin?

No, not really, I was just following the wiki instructions for submitting.
I'm not super versed with doing pull requests, so my apologies if this was the wrong way.

What would be the best way to handle updating the current one?
Just changing [plugin-hub/plugins/http-server](https://github.com/runelite/plugin-hub/blob/master/plugins/http-server) to use my repo's details?

**Comment by Nightfirecat** [comment]
I would recommend forking adam's repository, making the changes you want to contribute, then opening a PR against his repository, which he can then accept and update his plugin's record on this repository to use that updated code. There's not necessarily any problems with having multiple plugins which have similar functions, but if this is literally just the same as another one with a few enhancements, it would overall be better to then keep it to that one plugin.

**Comment by manmademagic** [comment]
Yep, that's a fair call

Feel free to reject this one then, and I'll go through and fork through Adam's repo

**Pull request closed without merging**
