### PR TITLE
add plugin last-recall-lock

### PR DESCRIPTION
**Pull request by pelletier2017**
Add last-recall-lock plugin to hide teleports when the teleport would override your last recall.

### CODE REVIEW

**Comment by Nightfirecat** [comment]
[The mouse listener you register here](https://github.com/pelletier2017/runelite-last-recall-lock/blob/284d50e1569e41670ee10000d891963eea9ec8a7/src/main/java/com/recall/LastRecallLockPlugin.java#L78) is never unregistered when the plugin is shut down
Also [what the heck is going on here](https://github.com/pelletier2017/runelite-last-recall-lock/blob/284d50e1569e41670ee10000d891963eea9ec8a7/src/main/java/com/recall/LastRecallLockPlugin.java#L80-82)? And [here](https://github.com/pelletier2017/runelite-last-recall-lock/blob/284d50e1569e41670ee10000d891963eea9ec8a7/src/main/java/com/recall/LastRecallLockPlugin.java#L96)? And [why do you update overlays on _all config changes to any plugin_](https://github.com/pelletier2017/runelite-last-recall-lock/blob/284d50e1569e41670ee10000d891963eea9ec8a7/src/main/java/com/recall/LastRecallLockPlugin.java#L107)?

**Comment by pelletier2017** [comment]
> [The mouse listener you register here](https://github.com/pelletier2017/runelite-last-recall-lock/blob/284d50e1569e41670ee10000d891963eea9ec8a7/src/main/java/com/recall/LastRecallLockPlugin.java#L78) is never unregistered when the plugin is shut down Also [what the heck is going on here](https://github.com/pelletier2017/runelite-last-recall-lock/blob/284d50e1569e41670ee10000d891963eea9ec8a7/src/main/java/com/recall/LastRecallLockPlugin.java#L80-82)? And [here](https://github.com/pelletier2017/runelite-last-recall-lock/blob/284d50e1569e41670ee10000d891963eea9ec8a7/src/main/java/com/recall/LastRecallLockPlugin.java#L96)? And [why do you update overlays on _all config changes to any plugin_](https://github.com/pelletier2017/runelite-last-recall-lock/blob/284d50e1569e41670ee10000d891963eea9ec8a7/src/main/java/com/recall/LastRecallLockPlugin.java#L107)?

Thanks for the feedback. I'll unregister the mouse listener and remove the onConfigChanged because I don't even have config options anymore.

```
 // effectively restart stretched mode to fix hitbox on overlay
client.setStretchedEnabled(false);
client.invalidateStretching(true);
```
This was an ugly workaround to fix an issue where the overlay I created had a hitbox that was not sizing correctly. Restarting the stretched mode plugin fixes it so I looked into that plugin and found some steps that fix the hitbox.

**Comment by Alexsuperfly** [comment]
The league has ended, are you still wanting to pursue adding this plugin to the hub even though its a league only mechanic?

**Comment by Nightfirecat** [comment]
Hi, sorry for the late re-review of this plugin. Per Alex's comment, leagues has ended so I'm closing this PR for now. If last recall is re-introduced in a future league or other game mode, I encourage you to re-submit this plugin. (and reference this closed PR so we can try to get to it more quickly next time--sorry again for that)

**Pull request closed without merging**
