### PR TITLE
Update clan-chat-webhook

### PR DESCRIPTION
**Pull request by pascalla**

### CODE REVIEW

**Comment by raiyni** [comment]
Remove `log.info` calls

**Comment by pascalla** [comment]
> It's not possible to add a warning to an existing plugin and retroactively warn users who have already installed it.

reverted this change

**Comment by iProdigy** [comment]
Warning would still be useful for new installs, or are you implying a new plugin should be created because retroactive warn isn't possible?

**Comment by Nightfirecat** [comment]
The issue isn't that this plugin shouldn't have a warning--if it were submitted as a new plugin today with its current code, it would require one. The issue is that we cannot retroactively add one. I recommend updating your code so that it does not make calls to 3rd party servers by default, [such as by changing this code to early return if  `config.secretKey()` is null or empty](https://github.com/pascalla/clan-chat-webhook/blob/d50900ba53a6dd208569540c9d8b7fa4c1928b8b/src/main/java/com/clanchatwebhook/ClanChatWebhookPlugin.java#L190), for instance.

**Comment by pascalla** [comment]
Now early returning on empty webhook/secret

**Pull request merged**
