### PR TITLE
Create DT2PerfectBossNotifier

### PR DESCRIPTION
**Pull request by DominickCobb-rs**
Add DT2PerfectBossNotifer as requested by https://github.com/runelite/runelite/discussions/17345

### CODE REVIEW

**Comment by YvesW** [comment]
Please pick a unique config group instead of ``example``.

**Comment by DominickCobb-rs** [comment]
This plugin is no longer needed with the addition of the DT2 CAs.

**Comment by Infinitay** [comment]
Could you still release this as a plugin? Personally I would like to know when my perfect kill is ruined or not during the fight, and in other cases I'm curious to know if the loot I received was from a perfect kill or not.

**Comment by DominickCobb-rs** [comment]
No. I don't want to have to sort the problems that come with the plugin, and Jagex can notify you mid kill regardless if you've completed the CA or not. You're welcome to fork the repo, maintain and submit it yourself though.

Also please don't respond to this comment, the PR is closed and this isn't a discussion. If you want to open a discussion, do so on the [repository](https://github.com/DominickCobb-rs/DT2-Boss-Failure/issues).

**Pull request closed without merging**
