### PR TITLE
Add chunk-tasks plugin

### PR DESCRIPTION
**Pull request by nathanreidok**
Plugin for one-chunk accounts to track tasks imported from the chunk picker site. Player will be notified with a collection log style popup when a task is either auto-detected as complete or manually checked off.

### CODE REVIEW

**Comment by Felanbird** [comment]
quick review: You can't use [example](https://github.com/nathanreidok/chunk-tasks/blob/8977584dd96c77c6420501047f05a9a516f321d0/src/main/java/com/chunktasks/ChunkTasksConfig.java#L7) as your config group, and there's a [couple other example's](https://github.com/search?q=repo%3Anathanreidok%2Fchunk-tasks%20example&type=code) as well

**Comment by nathanreidok** [comment]
@Felanbird thanks for the review. Replace all the "example"s

**Comment by YvesW** [comment]
I've not done an extensive review, but make sure to remove the NavButton on plugin shutdown.

**Comment by nathanreidok** [comment]
@YvesW updated to remove NavButton on shutdown

**Comment by Bram91** [comment]
We don't allow reflection on the hub

**Comment by nathanreidok** [comment]
@Bram91 - good to know! Removed reflection from the plugin.

**Comment by LlemonDuck** [comment]
https://github.com/nathanreidok/chunk-tasks/blob/50872f225a2b8377b7c80750f3af3c34a5fd993d/src/main/java/com/chunktasks/panel/ChunkTasksPanel.java#L347-L350

https://github.com/nathanreidok/chunk-tasks/blob/50872f225a2b8377b7c80750f3af3c34a5fd993d/src/main/java/com/chunktasks/managers/ChunkTasksManager.java#L37-L39

Use `ChunkTasksPanel.getResourceAsStream` and `ChunkTasksManager.getResourceAsStream`, respectively

**Comment by nathanreidok** [comment]
@LlemonDuck removed one `getResourceAsStream` that wasn't needed and updated the other.

**Pull request merged**
