### PR TITLE
Add bank value history tracker

### PR DESCRIPTION
**Pull request by AdrianLeeElder**
Adds a new panel in the right-hand menu for tracking bank value over time. 

Current features:
- Automatic, periodic tracking of the current bank value (can be disabled, so only manual entries are added
- Data is tracked based on bank tab numbers, so you can filter data by bank tabs. 
- Graph displaying current bank value over time
- Simple time selection ranges (Today, 24 hours, 6 months) or an advanced time selection using a date/time picker.
- Ability to open in a new window

More information/images located on the repo [readme](https://github.com/AdrianLeeElder/runelite-bank-history-plugin).

### CODE REVIEW

**Comment by loldudester** [comment]
You need to set up your runelite-plugin.properties file. Especially the `plugins=` line.

**Comment by AdrianLeeElder** [comment]
Is that build failure something I can fix on my end?

**Comment by abextm** [comment]
Please add the [gradle witness plugin](https://github.com/signalapp/gradle-witness) to your build to verify the shasums of the 2 non-runelite dependencies you added.

**Comment by AdrianLeeElder** [comment]
This is my first time using the `gradle-witness` plugin. It worked locally using gradle `4.10.2`, but when trying locally using the version of travis (5.1.1) it complains about:

` Could not find method dependencyVerification() for arguments`

The readme for the plugin said to put `dependencyVerification` directly below dependencies, but it doesn't recognize it there.

**Comment by abextm** [comment]
So apparently the witness plugin doesn't support gradle 5, and doesn't actually work correctly. So now we use gradle nightly, follow the steps here <https://github.com/runelite/plugin-hub#third-party-dependencies>

**Comment by abextm** [comment]
Do not store date in `~/.runelite/cache` that you expect to persist.

**Comment by abextm** [comment]
`~/.runelite/plugins` is also not the right place; Files in it get removed if they are not the jar for a currently running plugin. You should put your stuff in `~/.runelite/bank-value-tracker`

**Comment by abextm** [comment]
You put the wrong commit sha in here

**Pull request merged**
