### PR TITLE
Update distraction-reducer

### PR DESCRIPTION
**Pull request by Car-Role**
# Changes

## Bug Fixes
* Added support for gem cutting animation (ID: 888)
* Added support for battlestaff crafting animation (ID: 7531)
* Added TOA instance and region check to prevent overlay during Akkha mining puzzle while maintaining functionality in TOA bank

## New Features
* Added new Magic Toggles configuration section
* Added support for various magic processing spells:
  - Plank Make
  - added some Enchant Jewelry
  - Charge Orb
  - Bake Pie
  - String Jewelry

## Technical Changes
* Added TOA region IDs and instance-checking logic
* Added new animation ID sets for magic spells
* Added isInToaBank() helper method to properly handle TOA bank area
* Updated plugin tags to include magic category

### CODE REVIEW

**Comment by iProdigy** [comment]
For your toa region checks, you'll want to account for the location being instanced: `WorldPoint.fromLocalInstance(client, actor.getLocalLocation())` instead of `actor.getWorldLocation()`

**Comment by Car-Role** [comment]
> For your toa region checks, you'll want to account for the location being instanced: `WorldPoint.fromLocalInstance(client, actor.getLocalLocation())` instead of `actor.getWorldLocation()`

Thank you for the call out, I switched the method

**Comment by iProdigy** [comment]
I think you'll also want to update `isInToaBank`

**Comment by Car-Role** [comment]
Toa bank isn't instanced though right? or am i misunderstanding the
functionality

**Review by iProdigy — APPROVED** [review]

**Comment by iProdigy** [comment]
you're correct, was thinking of something else

**Pull request merged**
