### PR TITLE
New plugin: auto kick

### PR DESCRIPTION
**Pull request by solowanna**
Auto kicks people onJoin in the friendschat.

### CODE REVIEW

**Comment by solowanna** [comment]
I don't know the state of this pull request, but atleast i changed the runelite version to the latest one (1.8.17)

**Comment by pwatts6060** [comment]
> I don't know the state of this pull request, but atleast i changed the runelite version to the latest one (1.8.17)

At the moment the code isn't compiling. There's an issue with line 77/line 78 if you click on the first "Details" link in the checker. Possibly the import for FriendsChatManager isn't correct.

**Comment by Nightfirecat** [comment]
We denied another plugin which does this in #360. I don't know of any way this plugin could be changed to still do "auto-kicking" and be allowed.

**Comment by solowanna** [comment]
I kinda figured as much.
I will close the PR then. Thanks for the info @Nightfirecat :)

**Pull request closed without merging**
