### PR TITLE
Add modern tick counter to plugin registry

### PR DESCRIPTION
**Pull request by Shawneh**
Looking to revive the dead Tick Counter plugin by updating it with the missing weapons.

### CODE REVIEW

**Comment by Nightfirecat** [comment]
Please don't close and open new PRs if you encounter CI errors, just push new commits to your existing PR

**Comment by Shawneh** [comment]
My apologies, I messed up the branch on a rebase and closed it too soon. Will not do that in the future.

**Comment by Shawneh** [comment]
I submitted an MR to the original repository as well. I am not getting my hopes up as it has not seen action in over 2 years.
https://github.com/winterdaze/tick-counter/pull/13

What is the procedure for situations like this?

**Comment by Shawneh** [comment]
Closing MR as I was able to get in contact with the original plugin owner. They opened a PR to update the existing commit here - https://github.com/runelite/plugin-hub/pull/4415

**Pull request closed without merging**
