### PR TITLE
Custom Currency plugin v0.01

### PR DESCRIPTION
**Pull request by anexoticllama**
Currently adds functionality that checks a player's collection logs slots and allows them to earn a "custom currency" that they can then use the plugin config menu to "spend." Functionality provides for a simple currency payout per slot filled, or a more complex "tiered" reward structure.

### CODE REVIEW

**Comment by anexoticllama** [comment]
Marked this as ready for review despite the unsuccessful check as it appears the check must be performed by a plugin-hub maintainer rather than myself. If this is incorrect, please let me know.

**Comment by cdfisher** [comment]
> Marked this as ready for review despite the unsuccessful check as it appears the check must be performed by a plugin-hub maintainer rather than myself. If this is incorrect, please let me know.

Your build was successful so you're all set, it's just that the failing check is just that it hasn't been checked by hub reviewers yet. The hub submission process changed relatively recently to include that.

**Comment by raiyni** [comment]
What exactly is different? A quick skim seems to suggest it's nearly the same.

**Comment by anexoticllama** [comment]
The plugin

**Comment by anexoticllama** [comment]
@raiyni Can you clarify your question? The plugin itself would be a new addition to the plugin hub.

**Comment by raiyni** [comment]
Compared to the personal currency plugin. What is different about it?

**Comment by anexoticllama** [comment]
There are two primary differences:

1) Personal Currency Tracker uses a static "balance" that users input via the config and is incremented by the plugin
2) Personal Currency Tracker only provides static configuration for increments, so 1 "currency" per 1 action, or 2:1, 3:1, etc.

My plugin provides the following extended/modified functionality:

1) Currency balance is based on a Player's data, dynamically pulled from client, and users instead input how much they've "spent" of that balance
2) Configuration can remain static, but also is optionally configurable in a tiered structure. E.g. the first 100 Collection Log slots are worth 1 currency, 101-200 are worth 2 currency, etc.

**Comment by raiyni** [comment]
Those seem like they would be valuable additions to personal currency tracker.

**Comment by anexoticllama** [comment]
I have not been able to get in touch with CWorldEnder, the creator of Personal Currency Tracker, which means that it is not possible to fork->push to master->push to plugin hub. It has also not been updated in quite a while, so may just be a stale project.

**Comment by YvesW** [comment]
You've not even created a PR to his repo... 

https://github.com/runelite/plugin-hub?tab=readme-ov-file#contribute-to-existing-plugins

PR it to his repo, potentially ping him on Discord. If he then does not respond for a while, you can contact him in any possible way to ask to be added as contributor and to the hub file, and mention that if he fails to respond, his plugin will likely be transferred to you. If that fails, after approx 4 weeks we can technically give the repo to you if you show the appropriate receipts, but we strongly prefer people to be added as contributor to the original repo.

This is from one of my previous comments regarding contacting a hub author:

> We prefer that you contribute to existing plugins rather than create a new one, to prevent pluginhub bloat and so users can benefit from your updates and fixes. Please contact the original author via any way possible so they can add you as contributor.

> You should:
> - Create a PR with these changes in their repo and ask to be added as contributor to the repo.
> - Contact the author via any way possible:
>   - @ them in the RL discord if you know their discord name and ask to be added as contributor
>   - Check their GH for contact info and use that to ask them if you can be added as contributor
>   - Check their commits for their email so you can ask them via email if you can be added as contributor
>   - Create an issue as well asking to be added to the repo as contributor

**Comment by anexoticllama** [comment]
If you look at the open issues on that plugin, #2 and #3 are directly addressed by some of the extended functionality I've added or am working on. When you do that, take a look at the age of those open issues.

I can go spend another few hours adding my code into a fork of their repo and then wait 4 weeks to not hear back if that's truly what's preferred.

If the concern is bloat, let's take a little stroll on over to the shooting star plugins where there are at least 2 plugins that are duplicates of others.

**Comment by YvesW** [comment]
We've often seen hub authors wo do accept PRs, even if their repo might look stale. We do want you to follow what I described before. Regarding our reasoning, please refer to my previous message or the link that I included.

Regarding the star plugins: I can also point you to all the crappy discord plugins that should not exist because Dink exists. Nowadays we would not accept these plugins since they're duplicates.

**Comment by cdfisher** [comment]
The focus on minimizing hub bloat hasn't always been the priority, but it's definitely something that's been a priority more recently. It's bad UX to just remove existing plugins from the hub, so it hasn't really been applied retroactively, but new plugins typically have to do things that wouldn't be better off as functionality added to existing plugins.

Just because CWorldEnder hasn't put the time into implementing fixes to open issues doesn't mean that a PR fixing them wouldn't be merged, and as Yves has said, generally the preference would be to hand ownership of an existing plugin over to a new maintainer rather than adding an entirely new plugin.

**Comment by MESLewis** [comment]
As Yves described, this functionality should be added to the existing plugin. If the author is unresponsive to pull requests we can transfer ownership to you if you would still like to pursue this.

**Pull request closed without merging**
