### PR TITLE
Update Bank Tag Layouts to v1.1

### PR DESCRIPTION
**Pull request by geheur**
* Adds importing/exporting of layout-ed tag tabs.
* Adds layout placeholders to indicate when an item is in the layout but not in your bank. You can right click these to remove them from the layout.
* Adds "Enable layout by default" config option. You can still disable the layout for individual tabs even when this option is enabled.
* Prints tutorial message when you drag an item on a tab and you don't have any layout-ed tag tabs yet.
* Prints warning message when you might have unintentionally reordered your actual bank instead of a layout.
* Bug fixes.

### CODE REVIEW

**Comment by abextm** [comment]
we disallow reflection in most cases for hub plugins

**Comment by geheur** [comment]
Does this mean it was a mistake that 1.0 was accepted? It also had some reflection in it.

**Comment by abextm** [comment]
Yes, I wouldn't have accepted that

**Comment by geheur** [comment]
Updated this to remove the reflective stuff. Hope it's ok now.

**Pull request merged**
