### PR TITLE
[New Plugin] - Max-Hit Sounds - v1.0.0 - Sololegends

### PR DESCRIPTION
**Pull request by sololegends**
# Max-Hit Sounds
Add a special sound for when you hit max hit

- Set sound effects per range, mage, and or melee hits. 
- Whitelist only certain items to trigger the sounds (Looking at p2 wardens dds deafening you)

### CODE REVIEW

**Comment by DominickCobb-rs** [comment]
This may sound silly, but I have a similar plugin that is half baked. Have you looked at Attack Sound Notifications? A poorly named plugin that also can achieve this

**Comment by sololegends** [comment]
> This may sound silly, but I have a similar plugin that is half baked. Have you looked at Attack Sound Notifications? A poorly named plugin that also can achieve this

I didn't see that one in my searching for something that could do this. The main thing I wanted to have that I did find, and yours also doesn't seem to do this either, is to use in-game sounds and not sounds the user would have to load in themselves. 

There are a bunch of plugins that allow people to load in sounds from files, but not use in-game sounds which is where this ones comes in.

**Comment by DominickCobb-rs** [comment]
I could definitely make a small change to the panel to accommodate this. A toggle between an external sound and a sound ID is not a significant change

**Comment by sololegends** [comment]
That sounds fine to me. 

Would you also make it handle when you manual cast magic with the weapon and the hitsplat isn't directly tied to the weapon being held? That is something I'm working on today as as addition to this proposed plugin as I ran into that issue this morning. 

Additionally a categorical setting for all mage weapons / all melee / all mage would be nice.

**Comment by DominickCobb-rs** [comment]
I'll be honest, I don't have the time or will to expand the scope beyond the initially mentioned panel changes on mine. Apologies for bringing it up. :)

**Comment by sololegends** [comment]
> I'll be honest, I don't have the time or will to expand the scope beyond the initially mentioned panel changes on mine. Apologies for bringing it up. :)

No worries, it is always good to make sure there isn't a bunch of plugins doing the exact same thing on there

**Comment by sololegends** [comment]
This getting looked at maybe?

**Comment by iProdigy** [comment]
To avoid plugin proliferation:
@sololegends would you be willing to contribute your changes to the existing plugin?
and @DominickCobb-rs would you be willing to add them as a collaborator on the repo?

**Comment by DominickCobb-rs** [comment]
I'm willing to give full access/ownership of my existing plugin, but the way it sounded before is that this would supercede mine and cover the use case.

**Comment by LlemonDuck** [comment]
Even still, it would be better to add it to the existing plugin so that current users are maintained instead of needing to find a new plugin, and new users aren't required to determine which one supercedes the other. 

@sololegends Can you move your code into @DominickCobb-rs's repo?

**Comment by LlemonDuck** [comment]
closing as the above comments have not been resolved yet. feel free to resubmit when they are

**Pull request closed without merging**
