### PR TITLE
Create xt-security-plugin

### PR DESCRIPTION
**Pull request by YehiaHelal**
This plugin talks to an https server to retrieve runescape login details and randomly takes screenshots every couple of minutes

I tried to add a pull request before but i got this error "This plugin requires a review from a Plugin Hub maintainer. The reviewer will request any additional changes if needed."

### CODE REVIEW

**Comment by YehiaHelal** [comment]
"Requires maintainer review." How can i get it checked by a maintainer ?

**Comment by Adam-** [comment]
We aren't interested in adding this plugin because it is clearly just for running a gold farm.

**Comment by cdfisher** [comment]
> "Requires maintainer review." How can i get it checked by a maintainer ?

Maintainers have already closed your pull requests twice. I would take that as a sign that this isn't something that would be considered for inclusion on the hub.

**Comment by YehiaHelal** [comment]
> We aren't interested in adding this plugin because it is clearly just for running a gold farm.

what the plugin does is just to retrieve runescape login details for more secure login without giving the email and pass and take a screenshot of the client every 10min, it's meant to not expose the login details and keep track of the account progress

**Pull request closed without merging**
