### PR TITLE
Update tilemanmode

### PR DESCRIPTION
**Pull request by sram1337**
ConorLeckey/Tileman-Mode#48

The plugin was currently using a few terminally deprecated APIs that had to be updated for the plugin hub build to succeed. I also fixed some of the non-terminally deprecated APIs and removed some unused co

ConorLeckey/Tileman-Mode#47

> Skipped tiles when running instead of walking are currently incorrectly interpolated when doing L-shaped movement around an object. This fix allows the filled in tiles to be correct for all cardinal directions (both negative and positive delta x- and y-movement).

### CODE REVIEW

**Comment by YvesW** [comment]
https://github.com/runelite/plugin-hub/pull/6298#issuecomment-2227518329 Also, that previous PR hasn't even been merged yet.

**Comment by Alexsuperfly** [comment]
it looks like you have merge privileges to the tilemanmode repo so just add your name to the authors field so the bot removes the non author tag

**Comment by Alexsuperfly** [comment]
not in the plugin itself but the manifest here, for example the [authors field for 117HD](https://github.com/runelite/plugin-hub/blob/master/plugins/117hd#L3)

**Comment by MESLewis** [comment]
Marking as draft for now. Please make the requested changes, then mark the plugin as ready for review.

**Comment by LlemonDuck** [comment]
closing as the above comments have not been resolved yet. feel free to resubmit when they are

**Pull request closed without merging**
