### PR TITLE
Update taskjingle

### PR DESCRIPTION
**Pull request by maximonster**
Added functionality to play level up music

### CODE REVIEW

**Comment by Nightfirecat** [comment]
I'm not sure if you meant to add more changes here... this PR only updates the project's README. Does the plugin already support level up jingles, but didn't have info indicating that in its README?

**Comment by maximonster** [comment]
No the level up jingle functionality is new as per commit 823789838ec1fa2c937abd2fc24aaca5b47a119f

I updated the readme afterwards making that the most recent commit

**Comment by Felanbird** [comment]
I'm unsure why you would say "no" after being told what you've done does was incorrect, you almost certainly forgot to update your master branch with these changes last week and had to push them today.

If you type `git checkout 9d00dbc0ebfe462a93007ceef6c62f0888aeb580`, which is what the update to your plugin will do, you will get a branch without these changes just as NFC said. If you want to update the plugin with the changes, you'll need to update this pr to `e2a55f6130d16ed2dd9b1d440c45cc01c3c51880`, the merge commit that you pushed today that fixed up your issue.

**Comment by maximonster** [comment]
Thanks for the help!

**Comment by Nightfirecat** [comment]
[We're not going to be able to distribute the Final Fantasy 7 victory theme](https://github.com/maximonster/TaskJingle/blob/e2a55f6130d16ed2dd9b1d440c45cc01c3c51880/src/main/resources/lvlup.mp3), and for that matter, [the existing task-jingle.mp3 file is the GTA San Andreas mission passed theme](https://github.com/maximonster/TaskJingle/blob/e2a55f6130d16ed2dd9b1d440c45cc01c3c51880/src/main/resources/task-jingle.mp3) which we also should not be distributing. Please change or remove those files from distribution. (if you want, you can host the files separately and have the plugin download them on startup, like many other plugins such as the C Engineer plugin do)

This change LGTM otherwise.

**Comment by maximonster** [comment]
I've replaced the problematic mp3s with original jingles inspired by the previous ones. 
I've made lvlup.mp3 myself and task-jingle.mp3 is made by a friend specifically for the plugin. 
Please let me know if this is a suitable solution.

**Comment by Nightfirecat** [comment]
Thanks, I'll double check on that today

**Pull request merged**
