### PR TITLE
Add item-reminders plugin

### PR DESCRIPTION
**Pull request by CalumMagee**
This plugin takes ZoneID,ItemID pairs in the config and sends constant notifications if the player is in that zone without that item. It is intended to help you remember to take items into certain bosses and raids.

### CODE REVIEW

**Comment by raiyni** [comment]
Rename the file in this pr please

**Comment by CalumMagee** [comment]
How do I do that? Delete the commit from the other repo?

**Comment by CalumMagee** [comment]
How do I do that? Not sure what you mean

**Comment by Felanbird** [comment]
> How do I do that? Not sure what you mean

The exact same way to changed it from `repositoryURL` to `repositoryurl`, change it to `item-reminders`

**Pull request merged**
