### PR TITLE
Add Tileman Mode Plugin

### PR DESCRIPTION
**Pull request by ConorLeckey**
My plugin draws any tiles the player walks on.

It counts how many tiles they have used displays it, and uses the same value to calculate the 'remaining tiles'.

Created for the 'Tileman Mode' series on youtube, and I'd like to have it here for easy access for anyone who wants to play the game mode.

### CODE REVIEW

**Comment by Nightfirecat** [comment]
Seeing as this is a WIP merge request, I am converting this to a draft PR. Please coonvert it to a normal PR once it is ready for review.

**Comment by ConorLeckey** [comment]
Moved out of draft, ready for review.

**Comment by dekvall** [comment]
You should remove the `Installing` Part from the README as it's not needed.

**Comment by ConorLeckey** [comment]
> You should remove the `Installing` Part from the README as it's not needed.

Done 👍

**Pull request merged**
