### PR TITLE
Added a plugin file for Another Bronzeman Mode.

### PR DESCRIPTION
**Pull request by CodePanter**
This plugin is another implementation of the Bronzeman gamemode.
This plugin:
- tracks what items you have unlocked
- blocks all other items on the grand exchange from being bought
- has a 'screenshot every unlock' function and allows the user to specify a list of usernames that should receive a bronzeman chat icon.

### CODE REVIEW

**Comment by abextm** [comment]
Your license is too restrictive for us to distribute. Please use a more free license, such as the MIT or BSD licenses.

**Comment by CodePanter** [comment]
You are right; I sadly missed that entirely. I might be able to recreate the plugin from scratch this weekend with a BSD 2-Clause instead; and will update this pull request accordingly.

**Comment by CodePanter** [comment]
What does it mean that the travis-ci check has failed? I have thoroughly tested this release and it works without any problems on my computer.

Regarding this new version; I have started anew in a new repository, where I kept all my own code and rewrote most of the pre-existing code.
I have also ported over functionality from Robin Withes and Dekvall's bronzeman plugins.
This has added the following features to the plugin:
- The user now has a setting to get a message in chat for every unlock. (Dekvall)
- The user can also set this message to be a notification. (Dekvall)
- The plugin now has a 'unlock count' command. (Dekvall)
- The user now has a setting to enable a 'reset' command, which deletes the unlocked items. (Withes)
- The plugin now has a 'backup'  command that allows the user to backup the unlocked items list. (Withes)

**Comment by Adam-** [comment]
I think it expects the repository to end in `.git`

**Comment by CodePanter** [comment]
Thanks Adam, that indeed was why I couldn't make sense of the error message. I have now also fixed an actual issue in my code.

**Comment by CodePanter** [comment]
I'm sorry, I need to do one more commit to make it work without getting in the way of the other plugins.

**Pull request merged**
