### PR TITLE
Bank Quantities plugin config

### PR DESCRIPTION
**Pull request by CubeLuke**
This plugin will add a new tooltip to items in player inventory to show the current quantity amount that they have in their bank. Useful for if you get a drop and want to know how much of that item you already have banked.  

Example Screenshots:

### CODE REVIEW

**Comment by raiyni** [comment]
You need to submit the commit hash from your actual plugin, not the plugin-hub branch.

**Comment by raiyni** [comment]
Your plugin class should be `com.cubeluke.BankQuantitiesPlugin`

**Comment by CubeLuke** [comment]
My mistake on the incorrect has and the url being wrong, it was late so I thought I had put the correct one. Updated the plugin as well for the package name to be the full `com.cubeluke.BankQuantitiesPlugin` as mentioned above.

**Comment by Nightfirecat** [comment]
Closing this PR as it is inactive.

**Pull request closed without merging**
