### PR TITLE
Create slsnowglobe

### PR DESCRIPTION
**Pull request by snarLox**
Swaps snowglobe menu

### CODE REVIEW

**Comment by snarLox** [comment]
Hey, sorry never done this before; Let me know if there's anything I need to fix up:)

**Comment by Nightfirecat** [comment]
At a glance this looks fine. For what it's worth, I think this would be better as a contribution to the menu-swapper-extended hub plugin for instance, as that plugin already offers numerous more niche swaps, and has the code framework to easily add more.

**Comment by raiyni** [comment]
Config file is unnecessary

**Comment by snarLox** [comment]
> At a glance this looks fine. For what it's worth, I think this would be better as a contribution to the menu-swapper-extended hub plugin for instance, as that plugin already offers numerous more niche swaps, and has the code framework to easily add more.

This is how I'd prefer to have it. If you're able to give me some insight as too how; I'd be more than happy too

**Comment by raiyni** [comment]
PR to [https://github.com/raiyni/menu-swapper-extended](https://github.com/raiyni/menu-swapper-extended)

**Comment by snarLox** [comment]
Okay, PR'd to menu-swapper-extended. Thanks

**Pull request closed without merging**
