### PR TITLE
Submit Vorkath Helper plugin

### PR DESCRIPTION
**Pull request by SupahSoftware**
Audio queues for Vorkath, when he launches Fireballs and special attacks

### CODE REVIEW

**Comment by hex-agon** [comment]
This plugin breaches the official statement: https://secure.runescape.com/m=news/another-message-about-unofficial-clients?oldschool=1

**Comment by SupahSoftware** [comment]
> This plugin breaches the official statement: https://secure.runescape.com/m=news/another-message-about-unofficial-clients?oldschool=1

How is this any different than the gauntlet plugin that goes "2, 1, mage" "2, 1, range"?

**Comment by SupahSoftware** [comment]
It also doesn't 'predict' anything, it doesn't predict landing locations of any projects. It only announces information that can be known to the player already

**Comment by LlemonDuck** [comment]
The gauntlet plugin does not read game information and relies on player input to start the timers. Functionally, it's equivalent to having a website open beside the game that just provides clock functionality.

Similar to the zulrah plugin as well, which requires the player to input what rotations have happened while doing the fight, and does not automatically check zulrah's rotation.

**Pull request closed without merging**
