### PR TITLE
add alch-blocker plugin

### PR DESCRIPTION
**Pull request by robrichardson13**
# Alch Blocker
##### A plugin for [RuneLite](https://runelite.net/)

Allows you to block items from being alched

## Notes
- The plugin just checks the list of items configured and hides the item widgets when alching. It then unhides them after the alch cancels or completes.
- Adds quality of life (especially for UIM players), who always have near full inventories.
- This plugin can be used as a safeguard to ensure you never alch specific items. (The warning dialog doesn't have the fine controls to warn in all cases, where this plugin solves that.)

## Preview

Demo

### CODE REVIEW

**Comment by Nightfirecat** [comment]
This plugin should reset the inventory's state if on `shutDown()` so that inventory items don't remain hidden

**Comment by robrichardson13** [comment]
> This plugin should reset the inventory's state if on `shutDown()` so that inventory items don't remain hidden

Good catch.

New commit I implemented the `shutDown()` method and changed the string comparing to use `Text.removeTags()`.

**Comment by robrichardson13** [comment]
- Implemented startUp and onConfigChanged methods
- Moved hiding widgets to after the inventory is drawn to solve race condition
- Using string list to search blocked items instead of for loop

**Comment by pwatts6060** [comment]
I'd move the blockedItems list creation outside of the loop. Otherwise, you recreate it the list every loop iteration. I'd also consider using a Set instead of a List for constant time contains calls.

Additionally, you could keep only update the blockedItems set when the player changes the config. 
https://github.com/robrichardson13/alch-blocker/blob/fef10c3ce52ba9316c927798f8b0450ec476872b/src/main/java/io/robrichardson/alchblocker/AlchBlockerPlugin.java#L97

**Comment by robrichardson13** [comment]
> I'd move the blockedItems list creation outside of the loop. Otherwise, you recreate the list every loop iteration. I'd also consider using a Set instead of a List for constant time contains calls.
> 
> Additionally, you could store the blockedItems set as a field in the plugin and only update the set when the player changes the config. https://github.com/robrichardson13/alch-blocker/blob/fef10c3ce52ba9316c927798f8b0450ec476872b/src/main/java/io/robrichardson/alchblocker/AlchBlockerPlugin.java#L97

- Changed ArrayLists to HashSets
- Sets `blockedItems` on `startUp` and `configChanged`

**Comment by pwatts6060** [comment]
With the recent change of hiddenItems from List to Set. I believe there will be a subtle bug now in the loop in the showBlockedItems method. 

```
for (Widget inventoryItem : Objects.requireNonNull(inventory.getChildren())) {
	if(inventoryItem.isHidden() && hiddenItems.contains(inventoryItem.getItemId())) {
		inventoryItem.setHidden(false);
		hiddenItems.remove((Integer) inventoryItem.getItemId());
	}
}

hiddenItems.clear();
```

There's only one occurence of items in a set so if there are 2 items hidden, the set will only have the id once and in the first occurence of that item in the loop it will remove it entirely from the set. Then on the next occurence of it in the loop the hiddenItems.contains will return false and you won't do setHidden(false) on that item.
Right after the loop you clear the hiddenItems set anyway though, so you can fix this by removing the hiddenItems.remove line inside the loop.

**Comment by robrichardson13** [comment]
> With the recent change of hiddenItems from List to Set. I believe there will be a subtle bug now in the loop in the showBlockedItems method.
> 
> ```
> for (Widget inventoryItem : Objects.requireNonNull(inventory.getChildren())) {
> 	if(inventoryItem.isHidden() && hiddenItems.contains(inventoryItem.getItemId())) {
> 		inventoryItem.setHidden(false);
> 		hiddenItems.remove((Integer) inventoryItem.getItemId());
> 	}
> }
> 
> hiddenItems.clear();
> ```
> 
> There's only one occurence of items in a set so if there are 2 items hidden, the set will only have the id once and in the first occurence of that item in the loop it will remove it entirely from the set. Then on the next occurence of it in the loop the hiddenItems.contains will return false and you won't do setHidden(false) on that item. Right after the loop you clear the hiddenItems set anyway though, so you can fix this by removing the hiddenItems.remove line inside the loop.

Removed!

**Pull request merged**
