### PR TITLE
Create escape-crystal-notify

### PR DESCRIPTION
**Pull request by Xylot**
Notifies you when you do not have an active escape crystal

Useful for HCIM

### CODE REVIEW

**Comment by YvesW** [comment]
Please change your config group to something unique, instead of ``example``.

**Comment by Xylot** [comment]
> Please change your config group to something unique, instead of `example`.

Fixed! Thank you for pointing that out!

**Comment by Xylot** [comment]
Added option to display time left before triggering the inactivity teleport

**Comment by Felanbird** [comment]
The two images you just added are enormous, please scale them down otherwise java will be very upset.

**Comment by Xylot** [comment]
> The two images you just added are enormous, please scale them down otherwise java will be very upset.

They get scaled down by a factor of 15 in memory and cached before they are drawn to the screen. I had them large to improve fidelity when scaled up by the user. Is that enough or should I prioritize a certain size as the base image?

**Comment by Nightfirecat** [comment]
The loaded images will be kept in memory by Java, so it doesn't matter that you scale them down after the fact. You should be able to make them substantially smaller without impacting user experience.

**Comment by Xylot** [comment]
@Felanbird @Nightfirecat I have reduced the size of the two images! Let me know if the new sizes are acceptable or if there are any further modifications required!

**Pull request merged**
