### PR TITLE
Add Music Mask plugin

### PR DESCRIPTION
**Pull request by lequietriot**
Allows the user to play higher quality MIDI music over the Old School RuneScape game. This plugin supports SoundFont (.sf2) files and features an upgraded RuneScape sound engine for playback.

### CODE REVIEW

**Comment by Nightfirecat** [comment]
Is [the source in `com.musicmask.musicsystem`](https://github.com/lequietriot/music-mask/tree/234945ca252f4eea77d1d872e9dccadb7642fc71/src/main/java/com/musicmask/musicsystem) your own, or is it from some other package? It does not have any attribution currently, but looks like library code.

**Comment by lequietriot** [comment]
> Is [the source in `com.musicmask.musicsystem`](https://github.com/lequietriot/music-mask/tree/234945ca252f4eea77d1d872e9dccadb7642fc71/src/main/java/com/musicmask/musicsystem) your own, or is it from some other package? It does not have any attribution currently, but looks like library code.

Most of that code comes from https://github.com/lequietriot/RuneScape-MIDI-Player-Suite (Another package) which is based on the OSRS sound engine. Some of the imports are from a package com.sun.media.sound to support SoundFont 2 files.

**Comment by Nightfirecat** [comment]
I guess more specifically, is that all code that you wrote and own, and have license to publish? Is it _based on_, or _ripped from_ the osrs sound engine? (we likely can't publish the latter, but the former should be fine)

**Comment by lequietriot** [comment]
> I guess more specifically, is that all code that you wrote and own, and have license to publish? Is it _based on_, or _ripped from_ the osrs sound engine? (we likely can't publish the latter, but the former should be fine)

Most of the code in the musicsystem source is based on the osrs sound engine. I could probably create an alternate sound engine code if needed for publishing, although it would still be based on the old runescape way of handling midi music.

**Comment by Nightfirecat** [comment]
FYI all the code in `com.sun.media.sound` is licensed under GPL2, which requires work containing or derived from it also be licensed under GPL2; [your license is currently the BSD-2 Clause "Simplified" license](https://github.com/lequietriot/music-mask/blob/db3c132d137746d5e89407244d611ed6243eac40/LICENSE).

**Pull request merged**
