### PR TITLE
Update Bot Detector to V1.3

### PR DESCRIPTION
**Pull request by Ferrariic**
**A Complete Beautiful Refactor of the Bot Detector Plugin**

- Everything has been refactored. 
- Treat this as if it were a new plugin, because the commit diff is very messy.
- Changed the warning because we do not log chat at this time (Maybe in the future)
- Some functionality was removed (Removed beta tile markings, removed built-in beta heatmap)
- Updated the UI to be more intuitive
- Overall functionality improved and is now more stable.

### CODE REVIEW

**Comment by Cyborger1** [comment]
Just putting this here, we've picked up a few bugs we need to fix before this PR is accepted. Please hold off on accepting this for now.

**Review by Ferrariic — COMMENTED** [review]
Fixed HTTP Class

Thank you! All is good now.

**Review by Ferrariic — COMMENTED** [review]
Updated info box

**Review by Ferrariic — COMMENTED** [review]
- Reverted right-click menu entry to older method due to fix in 1.7.7
- API stability changes

**Pull request merged**
