### PR TITLE
Create weapon-charges

### PR DESCRIPTION
**Pull request by ZemyCode**
This is a plugin which tracks a player's weapon charges. This applies to most weapons which consume charges such as a Trident or Scythe of Vitur. This was made by modifying files from the official plugin "item charges". Currently is functional and should be working, sorry if I am incorrectly doing this pull request, this is my first time submitting an external plugin. Thanks.

### CODE REVIEW

**Comment by Nightfirecat** [comment]
Move the added file to `plugins/weapon-charges`

**Comment by abextm** [comment]
You can't use the same config group as the core item charges plugin

**Comment by ZemyCode** [comment]
> You can't use the same config group as the core item charges plugin

Changed it to weaponcharges just now, thanks.

**Comment by abextm** [comment]
You haven't pushed a change

**Pull request merged**
