### PR TITLE
Create graardor-kc

### PR DESCRIPTION
**Pull request by Gavin-TC**
Small plugin that adds counter boxes to the screen to see Bandos KC. Mostly useful with groups where you're not always getting the kill and would like to see how many kills you're getting per trip.

### CODE REVIEW

**Comment by DominickCobb-rs** [comment]
Could this not be achieved by looking at "Current Session Data" in the Loot Logger plugin or at the individual data in the Loot Tracker? It would require a client restart between trips if you're more worried about the separation of multiple trips in one go.

**Comment by Gavin-TC** [comment]
> Could this not be achieved by looking at "Current Session Data" in the Loot Logger plugin or at the individual data in the Loot Tracker? It would require a client restart between trips if you're more worried about the separation of multiple trips in one go.

I suppose it could if it shows info from kills made by people in your group. I haven't used the plugin before, so I'm not sure.

**Comment by umer-rs** [comment]
I believe `boost-performance` would do what you want. It tracks kills (at whitelisted bosses, bandos is included), regardless if you were the one getting kill credit.

**Comment by Gavin-TC** [comment]
> I believe `boost-performance` would do what you want. It tracks kills (at whitelisted bosses, bandos is included), regardless if you were the one getting kill credit.

Ahh, alright. Should I close the PR then since my plugin doesn't really add anything?

**Pull request closed without merging**
