### PR TITLE
Create dice

### PR DESCRIPTION
**Pull request by bogstandard**
Adds plugin to introduce on-screen dice rolls to the game for a table-top like experience.

### CODE REVIEW

**Comment by LlemonDuck** [comment]
This does not truly remove the widget from the parent: https://github.com/bogstandard/dice/blob/5841a593b16937fa087c0b2517ff74a7354a4857/src/main/java/com/dice/DicePlugin.java#L101

**Comment by LlemonDuck** [comment]
You can use Widget#getChildren -> copy the array without your widget -> Widget#setChildren

**Comment by abextm** [comment]
just `parent.getChildren()[child.getIndex()] = null;`

**Comment by bogstandard** [comment]
Thanks both, hopefully that's done it? I assumed that the arrays were working by reference to their child objects, so nullifying the child would in-turn cause the reference within the array to be nullified too.

**Comment by LlemonDuck** [comment]
> I assumed that the arrays were working by reference to their child objects, so nullifying the child would in-turn cause the reference within the array to be nullified too.

fwiw, java objects are "by-reference" but those references are not shared, so setting some variable/field to null will not also null out other references to the object i.e. in an array somewhere or in another variable

**Pull request merged**
