### PR TITLE
Create Player-List-Indicators

### PR DESCRIPTION
**Pull request by Coltonbranker**
Based on Player Indicators. Allows the user to add players names to lists. These lists are then used to highlight the name of those players in different colours over their heads, on the minimap and in right click menu boxes.

### CODE REVIEW

**Comment by Adam-** [comment]
I believe the plugin file names must be lowercase, so try renaming it to eg `plugins/player-list-indicators`

**Comment by Hydrox6** [comment]
This is [Rejected](https://github.com/runelite/runelite/wiki/Rejected-or-Rolled-Back-Features):
> Highlighting "Offline" Friends (and generic player highlighting): Not included to respect players with their messaging mode set to Private and to avoid harassing players (see runelite/runelite#951)

**Comment by Coltonbranker** [comment]
@Adam-  sorry I'm kind of new to all this, how would I go about editing it to lowercase without removing this pull request and making another.

@Hydrox6 the plugin that this is based off of, Player Indicators which is a main plugin (not via pluginhub) has an option to highlight all other players, this would just be highlighting specific ones instead of every one, I don't believe thats any different than the original

**Comment by Hydrox6** [comment]
> I don't believe thats any different than the original

It's very different. Highlighting everyone doesn't allow you to easily pick off specific targets for ragging/harassment. It's why the rejected line exists.

**Comment by Coltonbranker** [comment]
alright thank you for the clarification

**Pull request closed without merging**
