### PR TITLE
Create attack-ranges

### PR DESCRIPTION
**Pull request by tylerwgrass**
Displays the player's attack range for their currently equipped weapon.

This is similar to some of the other line of sight plugins/settings but automatically renders on weapon or attack style changes. I did a best-effort attempt to catalog all weapons but I am sure I missed some and I have not done extensive testing.

I tested:
- Bowfa
- Rune cbow
- magic shortbow (i)
- Red chin
- Dragon knife/thrownaxe
- Air battlestaff
- Dorgeshuun cbow

The general idea was given an OK, but will call out anyways that I could see this potentially violating the following Jagex guideline:

> Anything that automatically indicates where to stand, or not to stand. This applies to only automatic indicators, and not tiles which have been manually marked.

I plan to extend this to NPCs at some point, but decided to prune out what I had in progress for now, so there might be some remnants of that that work in the current case, but might not exactly look right in the current state (e.g. the tile visibility check).

### CODE REVIEW

**Comment by Felanbird** [comment]
You can still host your images on your repo, just don't put them in `src/`

**Review by aHooder — APPROVED** [review]
Not a blocker, but I would call `getVisiblePoints` once per game tick instead of every frame where the overlay is drawn. I also think your current tile marking method will break in POH and the Gauntlet, since those are assembled from non-contiguous chunks. Maybe also in Chambers of Xeric.

**Comment by tylerwgrass** [comment]
I'll update `getVisiblePoints`.

Gauntlet seems fine, unless there's something I'm missing:


Also CoX seem okay from the first few rooms (I have yet to do the raid), and PoH works but will probably just disable it there

**Comment by aHooder** [comment]
Hmm, it actually works better than I had expected :eyes: I see now that you're using world coords without mapping from instances to template chunks, so this should actually work quite nicely even in assembled instances.

**Comment by aHooder** [comment]
Incidentally, I just ran into an NPE which you might want to fix. It's possible for `Perspective.getCanvasTilePoly(client, lp)` to return null, so it requires a null check.

**Comment by tylerwgrass** [comment]
I've fixed the NPE and moved the point calculations to `onGameTick`.

Also, here's a screenshot in the POH checking across rooms of the same type (it was brought up in discord):

**Review by aHooder — APPROVED** [review]

**Review by iProdigy — APPROVED** [review]

**Pull request merged**
