### PR TITLE
add bats-locator plugin

### PR DESCRIPTION
**Pull request by chestnut1693**
This plugin will help locate bats at the thieving room inside Chambers of Xeric. See [original post](https://github.com/runelite/runelite/pull/10540).

### CODE REVIEW

**Comment by chestnut1693** [comment]
I would prefer some opinions before this makes it through.

**Comment by Trevor159** [comment]
> I would prefer some opinions before this makes it through.

Opinions on what? We normally do not code review external plugins other than making sure they are not malicious. Like I said on your PR to the main repo you can come in the discord and ask if you have any specific questions. This LGTM otherwise.

**Comment by chestnut1693** [comment]
I said I'm leaving it as it is but i want to add some minor changes.

**Comment by Adam-** [comment]
We can merge this now if you want, or do you prefer if we waited?

**Pull request closed without merging**
