### PR TITLE
Create drop-simulator

### PR DESCRIPTION
**Pull request by mxp190009**
This drop simulator plugin allows for the simulation of any number of trials of most NPCs with a drop table. Uses the [osrsbox-api](https://api.osrsbox.com/index.html) to gather an NPC's drop data. Drops are then simulated and displayed in the plugin panel. Hovering over a drop will display the name, quantity, and value of the item stack.

### CODE REVIEW

**Comment by Nightfirecat** [comment]
The bot doesn't seem to like your username I suppose... I'll post a diff link here in a minute.

**Comment by Nightfirecat** [comment]
New plugin `drop-simulator`: https://github.com/mxp190009/drop-simulator/tree/013d53487565a82f8e02f304016ae560e4e51876

**Review by Nightfirecat — CHANGES_REQUESTED** [review]
The [author field of runelite-plugin.properties](https://github.com/mxp190009/drop-simulator/blob/b642297ab9246142fe03aec456753d69c93d18b0/runelite-plugin.properties#L2) should be a human-readable string, not a git-author style string. This is what is shown in the plugin hub panel [and on the plugin-hub page of our website](https://runelite.net/plugin-hub). You should be able to change that to just "Marshall" and it'll be fine.

Please [don't fake a user agent when scraping from the wiki here](https://github.com/mxp190009/drop-simulator/blob/b642297ab9246142fe03aec456753d69c93d18b0/src/main/java/com/DropSimulator/DropTable.java#L67) or [here](https://github.com/mxp190009/drop-simulator/blob/b642297ab9246142fe03aec456753d69c93d18b0/src/main/java/com/DropSimulator/ApiParser.java#L90) or [when accessing OSRSBox's API here](https://github.com/mxp190009/drop-simulator/blob/b642297ab9246142fe03aec456753d69c93d18b0/src/main/java/com/DropSimulator/ApiParser.java#L57) or [here](https://github.com/mxp190009/drop-simulator/blob/b642297ab9246142fe03aec456753d69c93d18b0/src/main/java/com/DropSimulator/ApiParser.java#L102). The user agent should include "RuneLite" and the name of this plugin.

[Don't use `ImageIO` directly to load images.](https://github.com/mxp190009/drop-simulator/blob/b642297ab9246142fe03aec456753d69c93d18b0/src/main/java/com/DropSimulator/DropSimulatorPlugin.java#L73) Use [`ImageUtil.loadResource(Class<?> c, String path)`](http://static.runelite.net/api/runelite-client/net/runelite/client/util/ImageUtil.html#loadImageResource(java.lang.Class,java.lang.String)) instead. (you can refer to the main client for usage examples)

The [nav button added by your plugin](https://github.com/mxp190009/drop-simulator/blob/b642297ab9246142fe03aec456753d69c93d18b0/src/main/java/com/DropSimulator/DropSimulatorPlugin.java#L190) should also be removed from the client toolbar on shutdown.

Your dependencies on miglayout-swing and miglayout-core should be available via Maven central. [(1)](https://mvnrepository.com/artifact/com.miglayout/miglayout-swing/5.2) [(2)](https://mvnrepository.com/artifact/com.miglayout/miglayout-core/5.2) You can add those dependencies to your build.gradle file and [add dependency verification via these steps in our README](https://github.com/runelite/plugin-hub#third-party-dependencies).

**Comment by mxp190009** [comment]
accidentally closed this request, changes should be committed

**Comment by Nightfirecat** [comment]
You'll need to re-push your `drop-simulator` branch and reopen this PR, then update the reference commit to point at your latest changes

**Pull request closed without merging**
