### PR TITLE
Add combat-indicators

### PR DESCRIPTION
**Pull request by dekuScrub731**
Show highlight of Player and NPCs when in combat

### CODE REVIEW

**Comment by LeikvollE** [comment]
In violation of "Indicates which player an NPC is focused on"? Otherwise this could be merged with the interaction highlighter?

**Comment by dekuScrub731** [comment]
@LeikvollE - Yeah, I did consider that text before I started with this plugin. I ended up interpreting the spirit of that guidance as not allowing an NPC to show highlighting to various players (including players other than local). If the consensus is that this violates Jagex guidance, I can rework to only show what the local player is targeting.

I also saw the Interaction Highlighter plugin PR yesterday right before I submitted this pull request. I agree, it makes sense to group similar highlighting functionality together, so I'm ok with it being merged.

**Comment by LeikvollE** [comment]
@dekuScrub731 I don't know if you have read the discord discussion about the interaction highlighter, but it will be included in core and Adam has added functionality somewhat similar to this plugin.

**Comment by dekuScrub731** [comment]
Closing this PR as most of "player initiated" actions are covered under interaction highlighter changes. NPC initiated highlighting may be a gray area in terms of Jagex permitted actions.

**Pull request closed without merging**
