### PR TITLE
Update toa-mistake-tracker to v1.5

### PR DESCRIPTION
**Pull request by QuestingPet**
Fix visual glitch with new sidebar panel

### CODE REVIEW

**Comment by Adam-** [comment]
Is `com/toamistaketracker/crondis-example.png` required at its full resolution? It is almost 2mb.

**Comment by QuestingPet** [comment]
> Is com/toamistaketracker/crondis-example.png required at its full resolution? It is almost 2mb.

Where are you seeing that? I'm seeing it as 219 KB both locally and in the GitHub repo. In any case, it's used in the readme as an example/teaser of the plugin. It's not *required* to be of any size, and can be changed if needed, though probably can be separate from this fix I'd think.

**Comment by Adam-** [comment]
Java explodes images to their full resolution when you load it into memory, so it is 1,888,224 bytes (length * width * 4) in memory

**Comment by QuestingPet** [comment]
I can crop it to 690 x 380. Which puts it down to 1MB. Does that work, or do you require a new (lower-res) photo altogether?

**Comment by CreativeTechGuy** [comment]
@QuestingPet I highly recommend running all of your images through [Squoosh](https://squoosh.app/). You can easily compress your images to 30% of the size (or smaller) without any noticeable visual quality loss. You just need to play around with the compression settings and visually compare to find what works best for each image. Just the default settings (MozJPEG, 75% quality) for the `crondis-example.png` took it down to 32kb. If you also resize it you could easily get below 25kb.

**Comment by Nightfirecat** [comment]
@CreativeTechGuy We're not talking about compressed size, we're strictly talking about image dimensions, as that is what causes large in-memory size when loaded by Java.

For the image Adam referenced, it looks like it's only use is to be shown in the README. In that case, you can remove it from your resources directory (you could move it to the project root, or something outside of the `src/` directory) and it would be fine as it would no longer be shipped in the jar.

**Comment by QuestingPet** [comment]
Are we blocking merging this bug-fix on improving the image bloat (which is not modified in this PR)? Does everything else look fine?

**Comment by Felanbird** [comment]
I'm not sure if Adam looked at the actual code you changed when he made his request, but yes we would like you to make the change to the existing file.

**Comment by Nightfirecat** [comment]
Yes, we would like the image size issue addressed. We ask that hub plugin authors update their plugins in line with review guidelines at the time of review.

**Comment by QuestingPet** [comment]
I have moved the README photos out of `src/`

**Pull request merged**
