### PR TITLE
region-locker: Change repo

### PR DESCRIPTION
**Pull request by slaytostay**
Change the region locker repo to take it out of dekvall's hands
Adds plugin icon

### CODE REVIEW

**Comment by Adam-** [comment]
WIthout consent of the original plugin owner, we don't allow just forcibly taking over other users plugins. Maybe @dekvall is fine with this? If not, it should just be added as a second plugin (see how eg. there are two bronzeman plugins currently).

Also your plugin description appears to be advertising another client "ChunkLite"?

**Comment by dekvall** [comment]
He's the original plugin author and i asked him if he wanted to maintain it, so this is ok with me.

**Comment by Adam-** [comment]
Okay. Can you update the plugin description?

**Comment by slaytostay** [comment]
Yeah maybe I should have clarified that, devkall did ask me to replace his repo.
ChunkLite was just RuneLite with this plugin added and some changes to the client for shading and other chunk features, I will not be maintaining the client any longer because of the external plugin. But since original users of the client know the name I thought it would be appropriate as a tag.

**Comment by Adam-** [comment]
The tag is probably fine, I mean this: https://github.com/slaytostay/region-locker/blob/region-locker/src/main/java/com/regionlocker/RegionLockerPlugin.java#L67

**Comment by slaytostay** [comment]
Oh of course, I forgot that that was still there. On it.

**Pull request merged**
