### PR TITLE
Add PvP Kill Sounds plugin

### PR DESCRIPTION
**Pull request by slyt**
Play custom sounds when you kill another player or get a killstreak in PvP.

More details in the repo [README](https://github.com/slyt/kill-sounds/#readme).

### CODE REVIEW

**Comment by Nightfirecat** [comment]
1. The way you've included your sound resources is not correct; when shipped as a jar, this plugin will not load the default sounds. See: https://github.com/runelite/plugin-hub#plugin-resources. (You should be able to create a shadow jar for your plugin, move that jar to any directory, and have it load the sound resources from the jar, rather than from your filesystem)
2. We're not comfortable distributing some of the more aggressive sounds ("get fucked", "eat shit and die" primarily), please remove and/or replace them as needed. Thanks!

**Comment by slyt** [comment]
@Nightfirecat I removed the profane sounds (https://github.com/slyt/kill-sounds/commit/eb8263b946fd157d2b21bd0918baebc30588abbd). I'm still figuring out how to generate a shadow jar.

For some reason I was hit with a botting temp ban last night when I booted up my client to work on this. When I first loaded the client I was warned that it was out of date. I wasn't sure how to update it in the context of developing my addon. Could an out out of date client have caused my account to be flagged? I'm scared to continue developing this due to the threat of a perma ban on my 20+ year old account...

**Comment by slyt** [comment]
I reached out on Discord for help but nobody seemed to know what could be the cause of the ban and people were understandably suspicious in thinking that I actually botting. So now my goal is the understand the Java build process in more detail and replicate a ban with my build environment on a junk account. Hopefully I can shed some light on the situation to prevent future novice developers from getting false bans.

**Comment by Nightfirecat** [comment]
Sorry for the late response, I've been quite busy this past month. You should be able to follow the steps below to generate a shadow jar:

> Add the following line to your plugins block in build.gradle:
> ```
> id "com.github.johnrengelman.shadow" version "6.1.0"
> ```
> 
> Add this block elsewhere in the file, changing the Main-Class to your plugin's test:
> ```
> shadowJar {
>  from sourceSets.test.output
>  configurations = [project.configurations.testRuntimeClasspath]
>  manifest {
>  attributes "Main-Class": "com.example.ExamplePluginTest"
>  }
> }
> ```
>
> Then run ./gradlew shadowJar and a runnable jar will appear in build/libs/*-all.jar. You can run the jar with java -jar -ea jarName.jar

**Comment by LlemonDuck** [comment]
@slyt are you still hoping for a review on this plugin?

**Comment by Nightfirecat** [comment]
Closing this PR due to inactivity, please feel free to re-open it later if you plan to make the needed changes.

**Pull request closed without merging**
