### PR TITLE
Boost Notifier Plugin

### PR DESCRIPTION
**Pull request by rikbreukers**
### Plugin Overview
****The Boost Notifier plugin allows players to receive notifications when their selected skill's boosted level reaches specified thresholds. The plugin supports multiple threshold levels and offers both in-game and optional email notifications.

### Key Features

- **Skill Monitoring**: Select a skill (e.g., Strength, Attack) to monitor for boost levels.
- **Threshold Notifications**: Set up to 5 different boost thresholds, each with its own notification trigger.
- **Customizable Alerts**: Choose to receive notifications either in-game or via email.
- **Email Notifications**: Configure email settings (SMTP server, email address, app password) to receive alerts when the boost drops to a specified level.
- **Custom Email Subject**: Optional custom subject line for email notifications.

### Configuration Options

1. **Skill to Monitor**: Dropdown to select the skill for boost monitoring.
2. **Boost Thresholds**: Five input fields to set different levels for notifications, each with a corresponding enable/disable checkbox.
3. **Email Notifications**:
- Option to enable email alerts.
- Fields to input recipient and sender email information, SMTP server, port, and sender password.
- Checkbox to enable a custom subject for email notifications.

### Usage
This plugin helps players stay alert when their boosted skill levels are dropping close to their base levels, ensuring timely attention to reapply boosts for effective gameplay.

### Repository Link
The plugin source code can be found [here](https://github.com/rikbreukers/boost-notifier).

Please review this plugin for inclusion in the RuneLite Plugin Hub. Any feedback or suggestions for improvement are welcome!

You can copy and paste this description directly into the pull request, and it will be formatted properly on GitHub! Let me know if you need any modifications.

### CODE REVIEW

**Comment by cdfisher** [comment]
Hub plugins should use the [plugin template](https://github.com/runelite/example-plugin)

From a cursory glance, things like 

> Please review this plugin for inclusion in the RuneLite Plugin Hub. Any feedback or suggestions for improvement are welcome!

> You can copy and paste this description directly into the pull request, and it will be formatted properly on GitHub! Let me know if you need any modifications.

give the impression that this was generated with something with ChatGPT, which frequently gives essentially nonsense code.

**Comment by evilgenious448** [comment]
I am genuinely curious why someone would want email alerts sent to them for when their skills are boosted?

**Comment by rikbreukers** [comment]
> Hub plugins should use the [plugin template](https://github.com/runelite/example-plugin)
> 
> From a cursory glance, things like
> 
> > Please review this plugin for inclusion in the RuneLite Plugin Hub. Any feedback or suggestions for improvement are welcome!
> 
> > You can copy and paste this description directly into the pull request, and it will be formatted properly on GitHub! Let me know if you need any modifications.
> 
> give the impression that this was generated with something like ChatGPT, which frequently gives essentially nonsense code.

Yes I had AI help me to create the readme file, and also had some help and trial and error with AI on the coding part. it is my first plug-in and I really enjoyed making it. I hope it can be accepted as I have spoken with others who would like to use it as well.

If you have any feedback or information on what I can approve I am happy to hear it.

**Comment by cdfisher** [comment]
> > Hub plugins should use the [plugin template](https://github.com/runelite/example-plugin)
> > From a cursory glance, things like
> > > Please review this plugin for inclusion in the RuneLite Plugin Hub. Any feedback or suggestions for improvement are welcome!
> > 
> > 
> > > You can copy and paste this description directly into the pull request, and it will be formatted properly on GitHub! Let me know if you need any modifications.
> > 
> > 
> > give the impression that this was generated with something like ChatGPT, which frequently gives essentially nonsense code.
> 
> Yes I had AI help me to create the readme file, and also had some help and trial and error with AI on the coding part. it is my first plug-in and I really enjoyed making it. I hope it can be accepted as I have spoken with others who would like to use it as well.
> 
> If you have any feedback or information on what I can approve I am happy to hear it.

As I mentioned above, hub plugins need to follow the project structure of the [example plugin](https://github.com/runelite/example-plugin).

A guide on how to create a hub plugin with the appropriate structure can be found in the plugin-hub README [here](https://github.com/runelite/plugin-hub?tab=readme-ov-file#creating-new-plugins)

**Pull request closed without merging**
