### PR TITLE
Twitch emotes

### PR DESCRIPTION
**Pull request by skotizhoe**
sorry I closed my last one, I realized I didn't have the correct link in my repository. Anyway, I created a plugin that uses Twitch emotes in Chat. Thanks

### CODE REVIEW

**Comment by Nightfirecat** [comment]
These images aren't licensed such that we can distribute them

**Comment by jbpratt** [comment]
hey @Nightfirecat, sorry this isn't something that we thought of. The custom made emotes can be licensed CC by the original authors but the ones pulled from global twitch/bttv are going to be difficult/impossible to track down to get licensed. I assume if we moved forward with only images that we have explicitly licensed, there wouldn't be an issue with it?

Thanks for taking a look!

**Comment by raiyni** [comment]
Also, in the future don't close and open new prs. Commit the changes to the same branch and the bot will detect the changes.

**Comment by Nightfirecat** [comment]
Correct. You can search closed hub PRs for other twitch emote plugins; Twitch simply doesn't give permission for those to be used elsewhere. As for custom emotes, any which you're able to obtain permission to reuse and distribute we would be fine with shipping.

**Comment by Adam-** [comment]
Open a new PR if you want to make a version with custom emotes. Otherwise, we cannot use or distribute the twitch emotes.

**Pull request closed without merging**
