### PR TITLE
Update basqh

### PR DESCRIPTION
**Pull request by BA-Services**
removed features:
no longer changes the friends chat panel

added features:
adds new swing panel for queue management
contextual right click management of customers in the queue autofill of names of adding people to queue
right click add to swing panel
online/offline menu
button to directly visit the ranksqueueonline

BASHTTPClient.java handles all IO communication to our backened otherwise its all abstracted so easy to check if we're making suspicious IO calls

### CODE REVIEW

**Comment by iProdigy** [comment]
You'll want to remove this import https://github.com/BA-Services/queue-helper/blob/10e0f5e83388a8b43d3b2b5f8c1c2d4db08a4c22/src/main/java/com/queuehelper/BasQueueRow.java#L44

**Comment by BA-Services** [comment]
should be good now (hopefully) :)

**Comment by Nightfirecat** [comment]
Please [make your panel button logo smaller](https://github.com/BA-Services/queue-helper/compare/30a37133df5a0778aaf7c193385bfcfe7f051a63...BA-Services:5f3666c7b084937728640aacdf4d0f2c3d0438f1#diff-2e12c4236c7e29df2188be70e913a64023d3e9c3cf4f04fb8585152f163caddb); this will take up excessive amounts of memory when loaded by Java because of its large dimensions.

LGTM otherwise

**Comment by BA-Services** [comment]
Just bumping that the image was resized to 64x64 px

**Pull request merged**
