### PR TITLE
Create quiver-buddy

### PR DESCRIPTION
**Pull request by MapleBytes**
A simple plugin made to display the ammo inside your quiver. (I would love C engineer to do a snarky voice comment when entering a raid without ammo) something like "Raids are more fun with ammo in your quiver"

### CODE REVIEW

**Comment by MapleBytes** [comment]
If C Engineer reads this please contact me my discord is the same "MapleBytes" my IGN is MapleBytes please notice me C engineer.

**Comment by YvesW** [comment]
FYI, https://github.com/runelite/runelite/pull/17658 is a thing but still needs to be merged.

**Comment by Felanbird** [comment]
The PR adding this feature to the existing `Ammo` plugin has been merged and will be available in the next RuneLite version, due to that, is this plugin still needed?

**Comment by m0bilebtw** [comment]
> (I would love C engineer to do a snarky voice comment when entering a raid without ammo) something like "Raids are more fun with ammo in your quiver"

Are you happy for this to be a QoL option in C Engineer: Completed? :)

**Comment by MapleBytes** [comment]
As the functionality has been rolled into the existing Ammo plugin, this is no longer needed. Thank you for your considerations.

**Pull request closed without merging**
