### PR TITLE
Adds new Wintertodt-Scouter repo.

### PR DESCRIPTION
**Pull request by Nouser**
This is basically the old Wintertodt Scouter plugin, with a new server and repo backing it.

There were some potential issues with memory leaks posted in the Discord, so I made sure to run the memory profiler while using this for a few hours and didn't notice the memory ticking up over that timeframe.

### CODE REVIEW

**Comment by Felanbird** [comment]
current diff for reviewer since the bot doesn't know the old repo is gone https://github.com/Nouser/wintertodt-scouter/commit/c264e5f3c6a56bcb188538dbf59808046d367135

**Comment by raiyni** [comment]
The author has made their repo public again, can you fork their plugin?

**Comment by Nouser** [comment]
Thank you for your patience! I have now forked the original repo and added a new commit here pointing to the head of that new repo.

Let me know if there's anything you need from me!

**Comment by Nouser** [comment]
The previous code was not working with the new WT widget changes in this week's updates. I changed the IDs and things should be working again.

Please let me know if there's anything you need from me!

**Pull request merged**
