### PR TITLE
Add Dink to the plugin hub

### PR DESCRIPTION
**Pull request by Mm2PL**
This is a fork of UniversalDiscordNotifier (heavily modified and refactored). Unlike UniversalDiscordNotifier, this project isn't fully focused on Discord support. We're making a customized protocol which will have all the event data available easily to the person programming the webhook server.

I am a member of the @pajlads org.

### CODE REVIEW

**Comment by raiyni** [comment]
We don't support kotlin

**Comment by pajlada** [comment]
> We don't support kotlin

@raiyni We only use kotlin for unit tests & kotlin script for our gradle files. The actual plugin is 100% Java.
Would you like us to both convert the unit tests to Java and revert the gradle files to groovy?

**Comment by pajlada** [comment]
We ended up converting the tests to Java, and with some more dependency-massaging we got it to build :tada:

**Comment by Nightfirecat** [comment]
1. Please make your membership of pajlads public so we can verify you're actually a member of it
2. Please add an `authors=` field to the plugin manifest in this PR with a comma-separated list of people who could be anticipated to update the plugin in the future. This will help the bot know not to apply the `non-author plugin change` label to your PRs

**Comment by pajlada** [comment]
Thank you for your review!

I have updated the `authors` field with the four main contributors/maintainers of the plugin, @Mm2PL, @Felanbird, @iProdigy, and myself.

All listed authors (except for @iProdigy who's still sleeping 😴) now have their membership status public for verification.

**Pull request merged**
