### PR TITLE
Add plugin Watchdog

### PR DESCRIPTION
**Pull request by adamk33n3r**
FYI @Bullish53 gave me permission to use his service for the TTS as long as I was able to cache the results so that it's not overwhelming it. This was back in November so if he has an issue with it now, hopefully he can guide me into setting up my own service.

### CODE REVIEW

**Comment by adamk33n3r** [comment]
Oh I forgot, do I need to remove the shadow jar stuff in the build file for plugin hub?

**Comment by adamk33n3r** [comment]
Oh I forgot, do I need to remove the shadow jar stuff in the build file for plugin hub?

**Comment by abextm** [comment]
You need to close resources you open, like `Clip`s, File streams, http connections, etc. see try-with-resources statements. You need to remove your overlay in shutDown. You should not be calling setSelected on your panel in startUp

**Comment by adamk33n3r** [comment]
@abextm thanks for taking a look! :D I have pushed up the changes you requested. Let me know if there's anything else!

**Pull request merged**
