### PR TITLE
grimy animation

### PR DESCRIPTION
**Pull request by truenosus**
adds an animation to cleaning grimy herbs. uses the cutting gems animation.

### CODE REVIEW

**Comment by truenosus** [comment]
i put the license in my repository.. pretty new to this i think its all good now.

**Comment by geheur** [comment]
you deleted the LICENSE file in the plugin-hub repo, undo that (check the files changed section).
Also remove the example package and everything in it, in the plugin repo.

**Comment by truenosus** [comment]
> you deleted the LICENSE file in the plugin-hub repo, undo that (check the files changed section). Also remove the example package and everything in it, in the plugin repo.

thanks. will do

**Comment by geheur** [comment]
you also need to update the `runelite-plugin.properties` file.

**Comment by truenosus** [comment]
> you also need to update the `runelite-plugin.properties` file.

thanks should be done hopefully.

**Comment by geheur** [comment]
You still have changes to the license file, there should be no changes to the license file in the plugin-hub repo, only in the plugin's repo. Sorry if I wasn't clear before.

**Comment by truenosus** [comment]
> You still have changes to the license file, there should be no changes to the license file in the plugin-hub repo, only in the plugin's repo. Sorry if I wasn't clear before.

oh lol, no problem will fix. thanks for the help I am pretty new to runelite plugin making.

**Comment by geheur** [comment]
It still shows the LICENSE file as changed. You probably need to `git reset upstream/master` and then commit only the plugin file.

**Comment by geheur** [comment]
looked good in de4290a, did you mean to force-push instead of merging in the remote branch first?

**Comment by truenosus** [comment]
is it good yet? if not, I might just close and do another clean pull and push tomorrow. GIT confuses the shit out of me lol

**Comment by geheur** [comment]
no, it still shows 2 files changed (at the top of this page).

I would do `git reset --hard de4290a && git push origin master -f` to fix it. And stop merging in the remote branch all the time, you shouldn't ever need to do that unless someone else is working on the same branch (in which case you would want to rebase anyways).

**Comment by truenosus** [comment]
ahh okay i just did that. thanks for all the help i am still a college student! :)

**Pull request merged**
