### PR TITLE
added plugin that handles tracking skills on logout/closing runelite …

### PR DESCRIPTION
**Pull request by Jmaasy**
Added new plugin which will automatically track your progress on either a logout or when you close runelite.

It has the option to track via crystalmathlabs and/or wise old man. It uses the account that is currently logged in.

### CODE REVIEW

**Comment by Hydrox6** [comment]
This is already functionality provided by the core plugin `XP Updater`.

**Comment by Jmaasy** [comment]
Still a bit different, when I looked up XP Updated it showed me the F2P WIki plugin. When looking at F2P Wiki it's different from WOM and CML. This plugin also allows you to select which one you would report to ( or both ). Besides that this also actively updates when you close the client which that one won't do as well.

**Comment by Hydrox6** [comment]
> Still a bit different, when I looked up XP Updated it showed me the F2P WIki plugin. When looking at F2P Wiki it's different from WOM and CML. This plugin also allows you to select which one you would report to ( or both ). Besides that this also actively updates when you close the client which that one won't do as well.

The XP Updater plugin does *all* of this. That's the entire point of the plugin.
image

**Comment by Jmaasy** [comment]
Oh nevermind I'm blind -.-

**Pull request closed without merging**
