### PR TITLE
Update Raid Tracker: added ui and config

### PR DESCRIPTION
**Pull request by CasvM**
datatracker config

### CODE REVIEW

**Comment by abextm** [comment]
when writing to the .runelite you need to chose a name that is easily identifiable as your plugin; `loots` is not specific enough. Preferably use `raid-data-tracker`.

**Comment by CasvM** [comment]
I could do that, I figured I could re-use the folder system from thestonedturtle's loot logger.
You think I should change to raid-data-tracker?

**Comment by abextm** [comment]
unless you need to share data with that other plugin (which should also use a better name) you need to change the name to something identifiable.

**Comment by CasvM** [comment]
Just changed the main directory from loots to raid-data-tracker, thanks for the quick replies!

**Comment by WorstHerp** [comment]
@CasvM Hey, is it possible to add loots you've logged using other sources to your log inside the raid data tracker?

**Comment by CasvM** [comment]
while it is possible, it can't be done automatically. The data tracker tracks the loots by adding a line to the raid_tracker_data.log whenever you finish a raid, there's no way of determining the variables if it's not done from within the raid. 

You can add the variables manually though, simply copy one of the lines in raid_tracker_data.log and put the correct values in there.

**Pull request merged**
