### PR TITLE
Action progress 1.03

### PR DESCRIPTION
**Pull request by CalebWhiting**
1.03
* Rewritten a lot of core components.
* Many actions added/
* Many ingredient checks added, giving more accurate estimations of how many actions can be performed.
* Many customizations added, all actions can be enabled or disabled.
* Option to show skill icons instead of product icons (For example, Herblore icon instead of the potion being made).
* Updated for the latest RuneLite API changes

### CODE REVIEW

**Comment by CalebWhiting** [comment]
Still new to this build system, sorry about the spam, trying to fix dependency verification.

**Comment by CalebWhiting** [comment]
Having trouble getting org.jetbrains:annotations verified.
Is this something that I have the ability to fix, or would someone need to whitelist the library?

**Comment by Adam-** [comment]
I've added it to the verification metadata

**Comment by CalebWhiting** [comment]
> I've added it to the verification metadata

Thank you very much.
That one had me stumped :')

**Pull request merged**
