### PR TITLE
custom-spell-names

### PR DESCRIPTION
**Pull request by JonasDJ1999**
A plugin that makes you say spells from Harry Potter, when casting certain spells.

### CODE REVIEW

**Comment by YvesW** [comment]
Do not close and open new PRs. Push to the same branch.

**Comment by DapperMickie** [comment]
You also might want to change this: https://github.com/JonasDJ1999/Harry-Potter-Spells/blob/Harry-Potter-Spells/build.gradle#L26 to "com.harrypotterspells".

**Comment by JonasDJ1999** [comment]
sorry im very noob....

**Comment by JonasDJ1999** [comment]
> You've added 2 plugin files "harry-potter-spells" and "/plugins/Harry Potter Spells". There should only be 1 file added and it should be in the "plugins" directory.
> 
> Delete the "harry-potter-spells" file you've created and rename the "Harry Potter Spells" file in the "plugins" directory to "harry-potter-spells" because afaik you can't have spaces in the plugin file name.

how do I delete that one specifically?

**Comment by DapperMickie** [comment]
> > You've added 2 plugin files "harry-potter-spells" and "/plugins/Harry Potter Spells". There should only be 1 file added and it should be in the "plugins" directory.
> > Delete the "harry-potter-spells" file you've created and rename the "Harry Potter Spells" file in the "plugins" directory to "harry-potter-spells" because afaik you can't have spaces in the plugin file name.
> 
> how do I delete that one specifically?

If you're using the github website to do it, just navigate to the file and click the button with 3 dots on the top right and click delete.
https://gyazo.com/e099a9b487449454e69d14ede0ebdd10

If you've got the repo cloned to your pc, just delete the file and make a commit.

**Comment by DapperMickie** [comment]
Here is a link to the file that should be deleted: https://github.com/JonasDJ1999/plugin-hub/blob/master/harry-potter-spells

**Comment by JonasDJ1999** [comment]
> Here is a link to the file that should be deleted: https://github.com/JonasDJ1999/plugin-hub/blob/master/harry-potter-spells

okay I deleted that and renamed the other, what now?

**Comment by DapperMickie** [comment]
> > Here is a link to the file that should be deleted: https://github.com/JonasDJ1999/plugin-hub/blob/master/harry-potter-spells
> 
> okay I deleted that and renamed the other, what now?

Commit the changes :)

**Comment by JonasDJ1999** [comment]
> > > Here is a link to the file that should be deleted: https://github.com/JonasDJ1999/plugin-hub/blob/master/harry-potter-spells
> > 
> > 
> > okay I deleted that and renamed the other, what now?
> 
> Commit the changes :)

how do I do that without deleting this entire thread lol?

**Comment by Fiskmans** [comment]
If you did it through the github webpage, there is a button 'commit changes' that appears where the dots were after you press delete.  
If you did it locally on a clone:

```
git commit
git push
```

**Comment by raiyni** [comment]
Spells in Harry Potter are copyrighted material and they have been very diligent in defending their copyright over the years. Thus I don't think this should be added.

**Comment by JonasDJ1999** [comment]
> Spells in Harry Potter are copyrighted material and they have been very diligent in defending their copyright over the years. Thus I don't think this should be added.

yes I was unsure about what extend this was to. to fix this issue Ive just made the spells goofy/memes with a config where you can enter the text you want. hopefully I can later incorporate a way have a list of suggestions. so this is taken care off

**Comment by JonasDJ1999** [comment]
if anyone is curious about the future for this plugin. hopefully I can learn more about plugins and coding and get the following features:
-a picture for the plugin (Kodai Wand maybe hmm).
-cure, heal and ancients spells (couldn't find their casting ID)
-% toggle to be by itself in a different panel

**Comment by cdfisher** [comment]
> > Spells in Harry Potter are copyrighted material and they have been very diligent in defending their copyright over the years. Thus I don't think this should be added.
> 
> can just rename them then if that's needed ^^

I suspect the name of the plugin itself may be an issue.

**Comment by JonasDJ1999** [comment]
> > > Spells in Harry Potter are copyrighted material and they have been very diligent in defending their copyright over the years. Thus I don't think this should be added.
> > 
> > 
> > can just rename them then if that's needed ^^
> 
> I suspect the name of the plugin itself may be an issue.

then I can change it to "Custom Spells". but ya, I will wait and if this gets approved or not first, then Im told to change the name, I must figure out how to do that without ruining everything lmfao

**Comment by cdfisher** [comment]
> > > > Spells in Harry Potter are copyrighted material and they have been very diligent in defending their copyright over the years. Thus I don't think this should be added.
> > > 
> > > 
> > > can just rename them then if that's needed ^^
> > 
> > 
> > I suspect the name of the plugin itself may be an issue.
> 
> then I can change it to "Custom Spells". but ya, I will wait and if this gets approved or not first, then Im told to change the name, I must figure out how to do that without ruining everything lmfao

You can't change the internal name once it's on the hub.

**Comment by JonasDJ1999** [comment]
> > > > > Spells in Harry Potter are copyrighted material and they have been very diligent in defending their copyright over the years. Thus I don't think this should be added.
> > > > 
> > > > 
> > > > can just rename them then if that's needed ^^
> > > 
> > > 
> > > I suspect the name of the plugin itself may be an issue.
> > 
> > 
> > then I can change it to "Custom Spells". but ya, I will wait and if this gets approved or not first, then Im told to change the name, I must figure out how to do that without ruining everything lmfao
> 
> You can't change the internal name once it's on the hub.

ouff what would I have to do then? make a whole new one and copy the code in? lmao

**Comment by JonasDJ1999** [comment]
tf Im pretty sure I wrote it, but I changed the coding, so you input what spells you want yourself so no copyright

**Comment by JonasDJ1999** [comment]
wtf Im pretty sure i commented this 2 times, but I changed the code, so you input spells yourself so there is no copyright issue

**Comment by JonasDJ1999** [comment]
its been a month now lol. if there is any problems, please tell me so I can fix them

**Comment by Felanbird** [comment]
As cdfisher mentioned it's unlikely we would want to accept a plugin explicitly including `Harry Potter` in it's name, so you'll need to change that.

The name of your actual Github repo is not related to the name of the plugin, but if you wanted to do that it can be done in the [repo settings](https://github.com/JonasDJ1999/Harry-Potter-Spells/settings).
The changes we would actually want is the removal of the references from the actual code (e.g. setting names/descriptions) as well as this PR should be replacing your current change of creating the file `harry-potter-spells` and instead creating a file of whatever new name you choose and linking to the new repo name if changed.

**Comment by LlemonDuck** [comment]
Marking as draft for now. Please make the requested changes, then mark the plugin as ready for review.

**Comment by JonasDJ1999** [comment]
@Felanbird sorry for late reply, Ive been on vacation. How do I change the name, like where? and without messing everything up?

**Comment by LlemonDuck** [comment]
Gonna close this as very stale. Feel free to resubmit once you've made the requested changes. 

> How do I change the name, like where? and without messing everything up?

The plugin is not yet released to anyone, so you're free to edit it as much as you want. Nothing will be messed up on our end.

**Pull request closed without merging**
