### PR TITLE
Create boaty-Hype-Man Plugin

### PR DESCRIPTION
**Pull request by Devdeve**
Plugin is similar to CEngineers' completed plugin that plays certain sounds when different actions happen ingame but with the sounds being audio clips from the streamer/youtuber B0aty with the following proccing an audio file

- Level ups
- Quests completed
- Max hits
- When you login to the game
- When you hit a ruby bolt spec
- Get a drop above a value specified in Ground items
- Get a combat task
- Collection log or get a Pet

### CODE REVIEW

**Comment by Nightfirecat** [comment]
Do you have permission from b0aty to use his voice clips for this plugin?

**Comment by Devdeve** [comment]
Yes

https://clips.twitch.tv/OilyTardySageBrokeBack-lALYoBKA5NOweOoI

**Comment by Nightfirecat** [comment]
Code LGTM, but you need to give proper attribution to the C Engineer plugin, as most of your code is straight-up copied from it. Please read the license terms and make the appropriate changes

**Comment by Devdeve** [comment]
Updated to include reference and thanks to the C Engineer Completed plugin

**Pull request merged**
