### PR TITLE
Create disable-wearing

### PR DESCRIPTION
**Pull request by AlbeyAl**
Plugin that will block left clicking to wear an item in inventory. A list is set in the configurations, as well as, default enable/disable of plugin and a hotkey.

### CODE REVIEW

**Comment by raiyni** [comment]
You don't need an  executor to update a variable in your plugin.

**Comment by AlbeyAl** [comment]
Thanks for the information. Removed the executors in favor of calling `reset()` itself.

**Comment by Nightfirecat** [comment]
Please `remove your `log.info()` calls](https://github.com/AlbeyAl/RuneLite-Disable-Wear/blob/da379abcaeeb0d90ca89656929d93a9f63aaabd8/src/main/java/com/disablewearing/DisableWearingPlugin.java#L87) or reduce their visibility to debug, as this will clutter user logs.

**Comment by Nightfirecat** [comment]
Closing due to inactivity.

**Pull request closed without merging**
