### PR TITLE
Create vardorvis-health-tracker

### PR DESCRIPTION
**Pull request by AnuVen**
Tracks the health Vardorvis gains during a fight and displays it during, as well as with a chat message after the fight ends.

### CODE REVIEW

**Comment by damencs** [comment]
Is this not covered in Monster HP Percentage? - https://runelite.net/plugin-hub/show/monster-hp-percentage

**Comment by AnuVen** [comment]
This plugin tracks how much Vardorvis heals, which happens based on how much damage the player takes. That plugin just displays its health % at all times.

I think I should have reworded it better

**Comment by Nightfirecat** [comment]
Your build is failing because you specify in your plugin properties file that your plugin is located at `com.example.VardorvisHealthPlugin`, but it is actually at `com.vardorvishealth.VardorvisHealTrackerPlugin`

**Comment by AnuVen** [comment]
Fixed the issue, sorry!

**Pull request merged**
