### PR TITLE
VM Recolor Added

### PR DESCRIPTION
**Pull request by rtaylor4444**

### CODE REVIEW

**Comment by YvesW** [comment]
Don't use enabledByDefault = false in the plugin descriptor

**Comment by DominickCobb-rs** [comment]
Hey y'all. The VMRecolor is disabled by default so as not to confuse users who just want to download Ultimate Volcanic Mine. Bundled the recolor with this though to reduce clutter and encourage people to use the preferred VM plugin.

**Comment by raiyni** [comment]
Is there a specific reason these are bundled together. It's preferable they are separate plugins.

**Comment by DominickCobb-rs** [comment]
If it's preferred these not be shipped together then I'll submit a PR later this afternoon to add it as its own.

I don't remember where or who told me to ship it with this to reduce plugin hub bloat.

**Comment by Alexsuperfly** [comment]
added in #6751

**Pull request closed without merging**
