### PR TITLE
enhanced-discord-notifications

### PR DESCRIPTION
**Pull request by oliverpatrick**
enhances the discord-notifications plugin to include collection logs and valuable drops.

### CODE REVIEW

**Comment by oliverpatrick** [comment]
Build failure should be fixed with a new issues URL for the repository in the support tab.

**Comment by LlemonDuck** [comment]
Would you be interested in PRing these changes to the discord-notifications plugin rather than creating *yet another* discord webhook plugin?

**Comment by oliverpatrick** [comment]
> Would you be interested in PRing these changes to the discord-notifications plugin rather than creating _yet another_ discord webhook plugin?

Way ahead of you. The PR has been active for a couple of days now. I don’t know the real author as the item has been forked numerous times. I was going to see if could get this plugin merged and if they eventually took the additions in, I’d remove the enhanced addition.

**Comment by Nightfirecat** [comment]
Since the last activity here was several months ago and it's not clear what direction was wanted for this PR, I'm closing it. If this was already merged into another one of the many other Discord notification plugins, then we're all set. If there was still interest in adding this as a standalone plugin on its own, it can be reopened and we can go from there.

**Pull request closed without merging**
