### PR TITLE
Update wikisync to v3 and add jayden/lezed as authors

### PR DESCRIPTION
**Pull request by andmcadams**
@lezed1 could you give a quick summary of the changes here?

### CODE REVIEW

**Comment by lezed1** [comment]
WikiSync now hosts a WebSocket server to allow for a web-based tool pull data directly from the client! This will be used by the [OSRS Wiki DPS Calculator](https://tools.runescape.wiki/osrs-dps) to import your current gear. Here is an example of how the DPS Calculator will be able to use the new feature (I'm logged in to two instances of RL):

image

I tried to enforce that arbitrary websites are not authorized to talk to the WebSocket server. I'm happy to open it up to any site that has a good use case, but it felt wrong to open a server on localhost without an allowlist.

**Comment by lezed1** [comment]
This also includes some copy/pasted code from https://github.com/runelite/runelite/pull/17524. Once that PR is merged into RL core, we can delete our copy. All the copied code is clearly marked, so it will be easy to remove!

**Comment by raiyni** [comment]
Can the `log.info` calls be made `log.debug` ?

**Comment by lezed1** [comment]
@raiyni I pushed a new commit switching the logs from info to debug!

**Pull request merged**
