### PR TITLE
Update Hub Party Panel to v3.3.1

### PR DESCRIPTION
**Pull request by TheStonedTurtle**
Fixes some bugs I introduced in the last release (v3.3)

### CODE REVIEW

**Review by iProdigy — APPROVED** [review]

**Comment by MosheBenZacharia** [comment]
there's some wonky stuff going on in your readme. I think you just want to get rid of the "!" for the non-image links 
image

**Comment by letthiswork1** [comment]
This plugin has been broken since yesterday. I assume since this update

**Comment by cdfisher** [comment]
> This plugin has been broken since yesterday. I assume since this update

This hasn't been merged yet, so it wouldn't be the cause of your issues.

**Comment by letthiswork1** [comment]
> > This plugin has been broken since yesterday. I assume since this update
> 
> This hasn't been merged yet, so it wouldn't be the cause of your issues.

yes sorry, Hopefully this fixes it :)

**Pull request merged**
