### PR TITLE
Update wasted-bank-space

### PR DESCRIPTION
**Pull request by mcgeer**
CAT H and NID added to new WBS. New WBS include blacklisting. See #6498 for previously closed blacklist PR

### CODE REVIEW

**Comment by mcgeer** [comment]
@iProdigy

**Comment by mcgeer** [comment]
Do you want the ScheduledExecutorService modification added prior to approval?

**Comment by iProdigy** [comment]
> Do you want the ScheduledExecutorService modification added prior to approval?

not necessary!

**Review by iProdigy — APPROVED** [review]

**Review by pajlada — APPROVED** [review]
Looks good, you could make the images smaller with some image optimizer like oxipng (I saw size reductions up to 95% on some images) if you'd like but also not a blocker

**Pull request merged**
