### PR TITLE
Bump fixed-mode-hide-chat

### PR DESCRIPTION
**Pull request by deathbeam**

### CODE REVIEW

**Comment by pajlada** [comment]
This updates the "Hotkey used to toggle hiding the chat" config key name, which will make people lose their configs. You might want to revert that key change back to `hideChatHotkey`

**Comment by YvesW** [comment]
Is renaming the config key worth it, since it'll be wiping the value?
Additionally, will this consume everyone's escape key by default? Maybe that will cause some support traffic since it's often used to close the bank or to swap tabs.

Finally, it's replacing the hide chat option with a toggle. Maybe people will complain that the old behaviour is gone, but that's a decision you have to make yourself.

**Comment by deathbeam** [comment]
The config rename doesnt matter and it doesnt consume escape key (as it would also need to consume it in the other handlers i guess). But the current behaviour is kinda annoying as it both closes a bank and the chat at once so /shrug

**Comment by deathbeam** [comment]
Yea I think the new behaviour is too annoying so just gonna revert it.

**Pull request closed without merging**
