### PR TITLE
Create: skull-prevention-reminder

### PR DESCRIPTION
**Pull request by lostcoastwizard**
Draws an overlay to display whether skull prevention is on or off.

I noticed pull request #5012 needed some clean up but was abandoned. 

The changes asked for by @LlemonDuck have been applied along with some minor refactoring.

### CODE REVIEW

**Comment by raiyni** [comment]
original author needs included in the license

**Comment by lostcoastwizard** [comment]
LICENSE updated

**Comment by LlemonDuck** [comment]
You should not be loading the resources every frame during render. Load them once and reuse the images between frames

https://github.com/lostcoastwizard/skull-prevention-reminder/blob/63643e1df317ee322ffbc844a5947b69327e6538/src/main/java/com/SkullPreventionReminder/SkullPreventionReminderOverlay.java#L31-L40

**Comment by lostcoastwizard** [comment]
Updated. Images are no longer loaded every frame.

**Pull request merged**
