### PR TITLE
Reclaiming Profiles plugin

### PR DESCRIPTION
**Pull request by Spedwards**
The Profiles plugin was authored by me in its entirety and uploaded by Gudi with permission from me after I lost interest in the game (#53).

I am reclaiming this plugin and pointing it to my repo as I would like to make improvements to the plugin.

### CODE REVIEW

**Comment by Adam-** [comment]
I've asked Gudi about this and he says it is fine.

**Comment by Nightfirecat** [comment]
It would be really helpful if you could rebase your repo on mlgudi/profiles@e251564 so we can see a diff between your repo's tip and what we're currently building for this plugin.

**Comment by Nightfirecat** [comment]
This change adds password storage to this plugin which might be dangerous. We might want to wait on #159 to add that functionality as users should be warned if plaintext passwords are being stored as a result of using this plugin.

**Comment by Spedwards** [comment]
> This change adds password storage to this plugin which might be dangerous. We might want to wait on #159 to add that functionality as users should be warned if plaintext passwords are being stored as a result of using this plugin.

It will be stored on their local system and it is completely optional, but I had the same thought.

**Comment by Spedwards** [comment]
Changed the commit to use as one before password support was implemented.

**Pull request merged**
