### PR TITLE
Create gim-bank-discord

### PR DESCRIPTION
**Pull request by Boredska**
Plugin to track changes to GIM bank with discord webhook.

image

### CODE REVIEW

**Comment by LlemonDuck** [comment]
see https://github.com/runelite/plugin-hub/pull/3275#issuecomment-1237747800

**Comment by Boredska** [comment]
> see [#3275 (comment)](https://github.com/runelite/plugin-hub/pull/3275#issuecomment-1237747800)

Added

**Comment by LlemonDuck** [comment]
Same for SimpleItem.java...

**Comment by Boredska** [comment]
> Same for SimpleItem.java...

Should be ok now

**Comment by raiyni** [comment]
Can this be added to an existing discord plugin?

**Comment by Boredska** [comment]
> Can this be added to an existing discord plugin?

Which one? There are numerous discord plugins. And I'm not sure what is the SOP for making changes to someone else's plugin.

**Pull request merged**
