### PR TITLE
Update Inventory Setups to v1.10.2

### PR DESCRIPTION
**Pull request by dillydill123**
Bug fix regarding locked rune pouches and some refactoring

### CODE REVIEW

**Comment by dillydill123** [comment]
Build is failing because plugin `id "com.github.johnrengelman.shadow" version "5.2.0"` is in there. Adam discussed potentially adding it and the deps to verification. It is used to create runnable jars. Please let me know if it still being added, else I will remove it from the gradle script.

**Comment by dillydill123** [comment]
Is there any update on this? Should I just remove the the shadow JAR stuff?

**Comment by abextm** [comment]
It is up to you to add a dep if you need it

**Comment by dillydill123** [comment]
Ok, thanks. Do I just need to modify package/verification-template/build.gradle and add a dep there?

**Comment by abextm** [comment]
https://github.com/runelite/plugin-hub#third-party-dependencies

**Comment by dillydill123** [comment]
I just decided to comment out the shadow jar stuff instead.

**Pull request merged**
