### PR TITLE
Update Pathfinder to possible new maintainer and newer version

### PR DESCRIPTION
**Pull request by wqferr**
Original developer hasn't responded to my PR, so I decided to ~hijack it~ take the project into my own hands. I've added the new feature that originally prompted this ~takeover~ change of management.

This is also my first plugin project, sorry if I made any obvious mistakes.

### CODE REVIEW

**Comment by Adam-** [comment]
@Milo-Piazza are you okay with @wqferr taking ownership of this plugin?

**Comment by wqferr** [comment]
I just clicked the link the bot posted, and it still redirects to the previous repository, despite listing the newer commits on the fork. Might want to double check that.

**Comment by wqferr** [comment]
I'm trying to contact them through Discord as well.

**Comment by wqferr** [comment]
I also emailed them about this, and no response from them as well.

**Comment by Adam-** [comment]
Since the author has been unreachable for multiple weeks, we can give ownership of the plugin to you.

**Pull request merged**
