### PR TITLE
Add clan-member-list-sort plugin

### PR DESCRIPTION
**Pull request by jodelahithit**
This plugin adds a sort button to the clan member list.

### CODE REVIEW

**Comment by Adam-** [comment]
The 2nd plugin change doesn't diff because you are both changing commit and repo at once, can you change just the repo?

**Comment by jodelahithit** [comment]
There are no changes to the skilling-notifications plugin. I’m not sure why it’s showing up in this pull request. 
Both plugins are in the same repo but on different branches.

**Comment by Adam-** [comment]
If the commit is changing then there are by definition changes 
image

**Comment by jodelahithit** [comment]
My apologies, I've realized my mistake and will open a new pull request once I've fixed my fork of plugin-hub.

**Pull request closed without merging**
