### PR TITLE
Add ToG Crowdsourcing

### PR DESCRIPTION
**Pull request by jcarbelbide**
Tears of Guthix Crowdsourcing. 

This plugin aims to crowdsource the stream orders for each world. For example "gggbbb". Some stream orders are more efficient to use than others. 

This talks to an external web server created by me. The code for that cane be found [here](https://github.com/jcarbelbide/tog-crowdsourcing-server). 

The server monitors the osrs servers through a JS5 socket connection. When it detects the weekly reset, the database is wiped, and the new week's data must be gathered, The JS5 monitor can be found [here](https://github.com/jcarbelbide/js5-monitor). 

Please let me know if there are any questions or anything I need to change. 

Thank you for your time!

### CODE REVIEW

**Comment by jcarbelbide** [comment]
It looks like the automatic checks were not run during my latest commit, which I was hoping would fix the build issue. Does anyone know why?

**Comment by jcarbelbide** [comment]
Thank you, Adam! It looks like I was finally able to fix the build issue after 1 more commit.

**Comment by Nightfirecat** [comment]
Plugins making requests to external services must include a `warning`, ex: https://github.com/runelite/plugin-hub/blob/master/plugins/shooting-stars
Also, you shouldn't block the client thread in `StreamOrderDetector#submitToAPI()`.

**Comment by jcarbelbide** [comment]
Thank you so much for looking over this, @Nightfirecat! I have added the warning and removed the "synchronized" block from my code. I realized I do not need that since I did not include a data buffer like the Crowdsourcing core plugin and Shooting Stars plugin. Hopefully that is what you were referring to regarding the client blocking code. 

[Link to revised submitToAPI()](https://github.com/jcarbelbide/tog-crowdsourcing/blob/master/src/main/java/com/togcrowdsourcing/StreamOrderDetector.java#L248)

Also snuck in a few other minor fixes. 

I made two commits to the plugin:
[Removal of client thread blocking code](https://github.com/jcarbelbide/tog-crowdsourcing/commit/ad6a9695f11dea073a32a10007fa46980ab39e6f).
[Misc fixes](https://github.com/jcarbelbide/tog-crowdsourcing/commit/d613a4eb37aab98adf9b04c953c36f44b1e4732f).

**Pull request merged**
