### PR TITLE
Camera Points Plugin

### PR DESCRIPTION
**Pull request by NullNameException**
This plugin allows you to save and load camera viewpoints (pitch/yaw/angle).
I took some inspiration form the Screen Markers and other plugins UI to make it more intuitive to use.

### CODE REVIEW

**Comment by abextm** [comment]
This is a rejected feature. Also you don't need to create a new pr every time your build fails.

**Comment by NullNameException** [comment]
Does that mean setting a fixed camera angle is not allowed at all?

Also I'm sorry, I didn't know there was a way to know the build is going to fail before creating the pr.

**Comment by Hydrox6** [comment]
> I didn't know there was a way to know the build is going to fail before creating the pr.

You can just push more commits to the branch and the PR will update, btw

**Comment by abextm** [comment]
> Does that mean setting a fixed camera angle is not allowed at all?

Correct.

**Comment by NullNameException** [comment]
> > I didn't know there was a way to know the build is going to fail before creating the pr.
> 
> You can just push more commits to the branch and the PR will update, btw

Thank you, I will do that in the future


> > Does that mean setting a fixed camera angle is not allowed at all?
> 
> Correct.

Would it be okay to provide a fixed set of some camera angles to load instead of being able to save and load custom ones?
Since both of these features ("North/South/East/West on compass" and "Ctrl to reset zoom") already exist as plugins.

**Comment by abextm** [comment]
Just adjusting the zoom is fine, I don't want pitch/yaw adjustment more granular than just cardinal directions.

**Comment by NullNameException** [comment]
I understand. So if I changed the plugin to only save/load the zoom value it would be fine?

**Comment by abextm** [comment]
Yes. You can push the updated commit to this branch and re-open the pr if you do so.

**Comment by NullNameException** [comment]
Would it also be okay to set one of the cardinal directions (calling the same script as the compass) along with the zoom?
And if yes would I need to modify the script myself if the user does not use the compass plugin or will the modified version still be loaded?

**Comment by NullNameException** [comment]
The plugin now only allows to load cardinal directions (using the compass client script) along with the zoom. If that's still too much I can change it to only the zoom being adjustable.
I hope this works now.

**Pull request merged**
