### PR TITLE
Create tzhaar-ground-hider

### PR DESCRIPTION
**Pull request by JasonDahn**

### CODE REVIEW

**Comment by raiyni** [comment]
We'd prefer using the existing plugin that covers this, considering you said you copied the code from there.

**Comment by JasonDahn** [comment]
@raiyni Thanks for the heads up. One question:

I tried to open a pull request for the NullPointerException bug fix in the original repository but only the author has write access so I could not push a branch. I also cannot fork the repository since it's forked from the example plugin, and I already have a fork of the example plugin for a different plugin. Any advice on proceeding?

**Comment by raiyni** [comment]
I believe you can open the fork with a different name in the GitHub UI after clicking fork

**Comment by JasonDahn** [comment]
I am not seeing any way to have two forks that originate from the same repository in one account =/ I see "No available destinations to fork this repository." and a link to my existing fork. If you know of anything else I can try let me know, either way I appreciate the help!

**Comment by Nightfirecat** [comment]
You'll need to add their repository as a remote unless you remove your fork.
See: https://stackoverflow.com/questions/76845228/github-fork-attempt-says-no-available-destinations-to-fork-this-repository

**Comment by JasonDahn** [comment]
I just saw your response Nightfirecat, thank you for the guidance! I opened https://github.com/dey0/ground-object-hider/pull/1 :)

**Pull request closed without merging**
