### PR TITLE
Create wiki-search-shortcuts

### PR DESCRIPTION
**Pull request by IronCory**
Currently just a configurable hotkey to open the wiki search interface in runelite

### CODE REVIEW

**Comment by IronCory** [comment]
I'm unsure what caused this error or what it even means :(

**Comment by abextm** [comment]
you told it the plugin class is `com.wikishortcuts.WikiShortcutsPlugin` but you didn't provide that class

**Comment by IronCory** [comment]
thanks for you help abex, i forgot to update the plugin class after i changed the plugin name

**Comment by abextm** [comment]
It would probably be fine for this to be an option in the core wiki plugin if you want.

**Comment by IronCory** [comment]
the hotkey being added to the core plugin works for me! I made it as an external plugin only so that I could still have it if it were to be rejected from the core plugin and so I was less likely to break the core wiki plugin.

**Pull request merged**
