### PR TITLE
update Custom Vital Bars to 1.1.0

### PR DESCRIPTION
**Pull request by qt31415926535-femboy**
- attempts to fix a memory leak issue
- moved the outline width option to per-bar setting

### CODE REVIEW

**Comment by qt31415926535-femboy** [comment]
uh oh, I feel like I may have done something wrong here for a little plugin update. I've updated the manifest on my branch for an existing plugin but the bot thinks it's a new plugin?

**Comment by tylerwgrass** [comment]
You need to rebase your plugin branch against master

**Comment by qt31415926535-femboy** [comment]
> You need to rebase your plugin branch against master

sorry, this is not very clear to me. do you mean that I need to create a new branch and put my new code in that new branch? what should I name that new branch?

**Comment by tylerwgrass** [comment]
Your master branch (the one with this commit) is not up to date with `runelite:master` and has conflicts
You need to update your branch first.

I would also recommend making your updates from a branch that is not master.

**Comment by raiyni** [comment]
`git pull --rebase`

Should be fine? In the future it's easier to pull on your master branch and make a new branch from that

**Comment by qt31415926535-femboy** [comment]
> Your master branch (the one with this commit) is not up to date with `runelite:master` and has conflicts You need to update your branch first.
> 
> I would also recommend making your updates from a branch that is not master.

just to clarify before I wade into things - should I begin by updating [my copy of the plugin-hub](https://github.com/qt31415926535-femboy/plugin-hub) to the newest release of the official Plugin Hub code?
then I follow with creating a separate branch for my 1.1.0 update, then putting my new manifest in there with the new plugin-hub source code?

**Comment by LlemonDuck** [comment]
**_This will delete your existing changes_**, but will put you up to date. If it complains about "no refspec upstream/master", run `git remote add upstream https://github.com/runelite/plugin-hub.git`.
```
git checkout -f main
git fetch upstream
git checkout -B custom-vital-bars upstream/master
```
Then make your edits again, and recommit and push.

**Comment by qt31415926535-femboy** [comment]
I get "fatal: not a git repository (or any of the parent directories): .git"

there isn't anywhere this is really documented on the RuneLite project pages so I don't understand the process at all. I don't have a ton of experience with version control software either so I sincerely apologise that I am so utterly lost

**Comment by tylerwgrass** [comment]
The error implies that you did not run the commands from your repository directory.
If you are unfamiliar with the git command line, you can also try syncing your branches in the github UI.
There should be a sync option near the top [here](https://github.com/qt31415926535-femboy/plugin-hub/tree/master)

**Pull request closed without merging**
