### PR TITLE
Update tog-crowdsourcing - Nav icon too large

### PR DESCRIPTION
**Pull request by jcarbelbide**
Fix nav icon too large

Was taking 5MB in memory. Resized to 30x30 px

### CODE REVIEW

**Comment by Adam-** [comment]
It looks like your plugin icon.png is also too large, in addition to the nav button being changed here.

**Comment by jcarbelbide** [comment]
Got it, thank you! Let me fix that as well. Will get to it in a bit

**Comment by jcarbelbide** [comment]
Looks like I need to update some deprecated stuff. I don't have time right now but I can come back to this later

**Comment by jcarbelbide** [comment]
nevermind, it seemed like it was a simple fix

**Comment by jcarbelbide** [comment]
CI passes, but when I run this locally it no longer works. Can we hold off on merging for now? I want to look into this more

**Comment by Nightfirecat** [comment]
You should either close this PR or convert it to a draft in the meantime.

**Comment by jcarbelbide** [comment]
good point, thank you!

**Comment by jcarbelbide** [comment]
turns out the runelite version was just out of date. seems like it works fine after updating the version, so I'm good on my side. Please let me know if there are any other changes I should make. Thanks!

**Pull request merged**
