### PR TITLE
Add Touchscreen Plugin

### PR DESCRIPTION
**Pull request by Notloc**
*Fixes*
- Fixed the dead input bug.
    - (Without this plugin touch inputs will be missed/inaccurate as the mouse position from last frame is used for interacting, but touch inputs teleport the mouse, so that can be a massive difference)

*Features*
* Ability to rotate the camera by dragging on the game view
* Ability to zoom the camera by dragging vertically on the minimap
* Ability to zoom the minimap by dragging horizonally on the minimap
* Ability to scroll various menus by dragging on the menu
* Faster right clicking option
    * Click and hold to open the right click menu as normal on touchscreen, without releasing the click move your finger onto the desired option then release

*Video Examples*
- Before
    - https://www.youtube.com/watch?v=HEus8rMrut0
- After
    - https://www.youtube.com/watch?v=UGWogZZtLlk

### CODE REVIEW

**Comment by Notloc** [comment]
Apologies for the commits post PR opening.
I've cleaned up all the noted issues and added tags.

**Comment by Felanbird** [comment]
we don't care about commits, we'd rather you spam commit than spam open/close PRs every change

**Comment by raiyni** [comment]
My feedback for this pr and the other one that is open is the same. Emulating mouse events, trying to time clicks, and `fixing` events sounds not great maybe in regards to Jagex cheat detection.

**Comment by Notloc** [comment]
Unfortunate.
I don't think there is any way I could achieve a good UX without post-processing the events as I've done.
Even if I somehow managed to receive actual touch events, they would still need to be translated into emulated mouse events.

If that is the final verdict, then I think touchscreen support as a concept is just dead in the water and this PR can be closed.

**Comment by raiyni** [comment]
After discussion, we don't think we can safely support these plugins unfortunately.

**Pull request closed without merging**
