### PR TITLE
Loot table plugin

### PR DESCRIPTION
**Pull request by Sir-Kyle-Richardson**
Plugin to quickly look up loot table's of npc's

### CODE REVIEW

**Comment by Nightfirecat** [comment]
I'd like for us not to be misrepresenting the source of our web traffic to the wiki by using a browser's user agent. I'd rather we used the user agent `RuneLite`, like is done in other plugins. (see the main client's XpUpdaterPlugin)

**Comment by abextm** [comment]
You need to [pin your deps](https://github.com/runelite/plugin-hub#third-party-dependencies)

**Comment by Sir-Kyle-Richardson** [comment]
@abextm after adding the verification xml file and running `./gradlew --write-verification-metadata sha256`, I'm running into an error I can't seem to resolve 
image

Any advice? Sorry if it's obvious, I'm new to using gradle

**Comment by abextm** [comment]
try running `./gradlew wrapper --gradle-version=6.3`

**Pull request merged**
