### PR TITLE
Game tick information

### PR DESCRIPTION
**Pull request by AcolyteOfFire**
Features a number of tools to help track time for tick manipulation skilling methods, lets you track the time spent on the current tile, and display a cycle of game ticks. Also lets you mark tiles as start locations to track 'laps' on any content.

### CODE REVIEW

**Comment by Felanbird** [comment]
Don't open new pull requests to fix issues, just push the changed commit hash to this PR

**Comment by AcolyteOfFire** [comment]
I'm not sure what I've done wrong here, this is my first time trying to contribute code to any project, and I see this failed check which I think is caused by dependency verification. I'm not sure how to resolve this, I only used imports that I saw in other plugins.

**Comment by YvesW** [comment]
Tip: you can actually read the error to see what the problem is and which packages failed dependency verification. You can then remove them from i.a. your build.gradle

**Comment by AcolyteOfFire** [comment]
Thanks, figured out the issue. I also removed the chat commands, I'd just been using them for debugging during development anyway.

**Pull request merged**
