### PR TITLE
Add farming guild overview plugin

### PR DESCRIPTION
**Pull request by wouterrutgers**
This add an overview, when in the farming guild, with all the patches. To quickly see what's empty and what's completed.

image

### CODE REVIEW

**Comment by LlemonDuck** [comment]
In what way is this more useful compared to the core Time Tracking plugin?

**Comment by wouterrutgers** [comment]
I regularly complete my farming contracts and always have all my patches pre-planted. When Jane, in a humble manner, requests a few contracts that I’ve already pre-planted, I continue until she asks for one I can’t do. At that point, I head to the seed vault to grab new seeds, but I always have to fully zoom out and pan around to see which patches are empty.

The core time-tracking plugin doesn’t efficiently show which patches are empty just within the Farming Guild (you have to click all tabs). This plugin is simply a small quality-of-life improvement to quickly check what needs replanting to ensure everything is pre-planted again.

image

**Comment by LlemonDuck** [comment]
Nitpicky then, but I think "Farming Contracts" is a bit of a misnomer, and something like "Farming Guild Overview" would be more descriptive.

**Comment by wouterrutgers** [comment]
That makes sense! I named it that way because I mainly use it to get an overview of what I need to pre-plant for farming contracts. But you're right—it doesn't really say anything about the contracts themselves! I'll go ahead and rename the plugin!

**Comment by wouterrutgers** [comment]
Renamed it! Also made the README.md a bit more descriptive!

**Comment by LlemonDuck** [comment]
The plugin file name here in the hub repo could be changed as well. Other than that, plugin code lgtm!

**Comment by wouterrutgers** [comment]
Ah.. forgot about that one. Fixed!

**Pull request merged**
