### PR TITLE
Create Guardians Of The Rift Extended plugin

### PR DESCRIPTION
**Pull request by NathanCollaert**
The plugin adds the following to the Guardians of the Rift minigame:

### Outlines
* Outline the Deposit Pool when you have runes in your inventory.
* Outline the Great Guardian when you have Guardian Stones in your inventory.
* Outline the Active Guardian Portals / Guardian Portals of which you have the Talisman for.
* Outline the Uncharged Cells Table when you have less than or equal the Uncharged Cells limit in your inventory.
* Outline only the Active Guardian Portals for which you have the sufficient for.
* Outline only the Active Guardian <Elemental/Catalytic/Highest Level/Highest Tier/Highest Profit/Custom> Portal.
### Overlays
* Show Huge Guardian Remains Portal Hint Arrow when one spawns.
* Show Huge Guardian Remains Portal Timer when one spawns.
* Show Active Guardian Portal Timer above portal when activated.
* Show Active Guardian Portal Rune above portal when activated.
* Show Guardian Portal Talisman above portal of which you have the Talisman for.
### Panel
* Show GOTR game start timer.
* Show last Portal spawn timer.
* Show currently saved up elemental/catalytic points.

### CODE REVIEW

**Comment by raiyni** [comment]
The `guardians-of-the-rift-helper` plugin already exists and looks like it does most, if not all, of this.

**Comment by NathanCollaert** [comment]
> The `guardians-of-the-rift-helper` plugin already exists and looks like it does most, if not all, of this. It also looks like you yoinked a lot of code from that plugin without attribution.

Hi there, yes I must admit that this is basically an extension of the already existing Guardians of the Rift Helper plugin. Nonetheless I don't agree with the fact that everything this plugin does is also covered by the GOTR Helper plugin. More so, I also fixed a lot of bugs/problems with the plugin that annoyed me about it and by doing so, also found a lot of performance issues in the plugin that I changed.
Adding to that, this is the first release of the plugin and as I agree with you, the plugin is very close to the GOTR helper plugin, a lot more features can be added later setting it apart more and more!

**Comment by raiyni** [comment]
We would prefer you contact the author of that plugin and submit pull requests to their repositoory.

**Comment by NathanCollaert** [comment]
Thank you for your suggestion, and I understand your preference for me to contact the author of the Guardians of the Rift Helper plugin and submit pull requests. While I respect that approach, I believe there are some valid reasons for creating a separate plugin.

Firstly, by creating this extension, I aimed to address certain bugs and performance issues that were bothering me personally. These modifications were tailored to my specific needs and preferences. While some of the changes may overlap with the existing plugin, there are also distinct improvements and features that I've implemented.

Additionally, by releasing this initial version, I hope to gather feedback and suggestions from the community to further differentiate it from the GOTR Helper plugin. I'm open to incorporating user ideas and expanding its functionality based on those inputs.

That being said, I appreciate your concern, and I'm willing to properly give attribution where it is necessary. In the end, my goal is to enhance the overall experience for users of both plugins.

**Comment by raiyni** [comment]
It's much more confusing for users to have multiple plugins with nearly the same name, nearly the same feature set, and no differentiator than it is for you/another author to contribute to an open source project and make it better.

This is a stance we have taken to help cut down on spam plugins, bloat on the hub, and bandwidth that we have to use to help users when they come into discord confused.

**Comment by Nightfirecat** [comment]
Per [raiyni's earlier comment](https://github.com/runelite/plugin-hub/pull/4421#issuecomment-1568455602), it's clear you've used a good amount of code from [DatBear's Guardians of the Rift Helper plugin](https://github.com/DatBear/Guardians-of-the-Rift-Helper) as a baseline without attribution. Please [provide attribution in line with that codebase's LICENSE](https://github.com/DatBear/Guardians-of-the-Rift-Helper/blob/master/LICENSE).

Also please stop using ChatGPT to write your replies to us.

**Comment by TicTac7x** [comment]
Had similar experience few months ago, the original plugin is kinda buggy. Offered my help, made PR that just stayed there for a month, nothing happened and that was it.

**Comment by LlemonDuck** [comment]
closing as very stale, feel free to reopen if you address Nightfirecat's comment above

**Pull request closed without merging**
