### PR TITLE
Updated afk canafis marks

### PR DESCRIPTION
**Pull request by powerus117**
Made some changes to the afk canafis marks plugin:
- No longer resets on game state changes. This was triggered when "LOADING" was triggered and caused the plugin to reset timings. Removed the game state subscription.
- Made leeway seconds configurable for unaccurate PC timings.
- Added feature request to swap menu entry when plugin suggests to wait to prevent jumping down the course unintentionally. Default disabled

Thanks for checking 🙏

### CODE REVIEW

**Comment by raiyni** [comment]
Don't do this https://github.com/powerus117/RLAfkMarksCanafis/blob/609d38d3be413562e66a801659ea21c13cb2aea7/src/main/java/com/afkmarkscanafis/AfkMarksCanafisPlugin.java#L167-L177 your plugin will no longer receive updates for events after you leave the area

**Comment by TomBMNA** [comment]
But that's the idea no? To prevent unnecessary callbacks when not needed, to save performance. The events are only used for menu entry changes

**Comment by Nightfirecat** [comment]
If your plugin is no longer receiving game tick events, how would it ever re-run that check to re-register to the eventbus?

**Comment by TomBMNA** [comment]
Ah I didn't realize the game update was also tied to this eventbus. I'll remove it thanks

**Pull request merged**
