### PR TITLE
Updated afk marks canifis to marks cooldown

### PR DESCRIPTION
**Pull request by powerus117**
After some feedback on the AFK canifis marks plugin, I have added other courses so it no longer is a canifis specific plugin but rather a general mark of grace cooldown tracker. And that's exactly what it does, while running laps, after finding your first mark, you should see a cooldown for when the next mark could spawn.

There were also previously some issues with computer with their time out of sync, which are now resolved using NTP.

Let me know if I can improve anything or if you have any questions, thanks in advance 🙏

### CODE REVIEW

**Comment by YvesW** [comment]
Not an extensive review but...
- By changing the ConfigGroup, you are wiping people's config. I strongly recommend not changing the config group or migrating config values on startUp and ProfileChanged. The former is the easier option.

**Comment by raiyni** [comment]
We also recommend not changing the plugin file name

**Comment by raiyni** [comment]
Yes, value for configName would be `AfkMarksCanafisPlugin`

**Comment by powerus117** [comment]
Alright thanks, updated 🙏 But when I boot up, I now do see my plugin twice, if I enable 1, the other automatically also enables and vice versa. Is that to be expected?
image

**Comment by YvesW** [comment]
FYI the support link gets ignored nowadays AFAIK. So you can just remove that field from the file.

**Pull request merged**
