### PR TITLE
Update partyreadycheck

### PR DESCRIPTION
**Pull request by scainburger**

### CODE REVIEW

**Comment by Nightfirecat** [comment]
This PR needs to have its merge conflict resolved

**Comment by scainburger** [comment]
> This PR needs to have its merge conflict resolved

Thanks, must've missed that.

**Comment by scainburger** [comment]
Thanks @Nightfirecat, this is resolved now.

**Comment by LlemonDuck** [comment]
You should also try to close the Clip resource even if an error occurs using a `finally` clause: https://github.com/scainburger/partyreadycheck/compare/ed6d42032811888e8378db68657ea853d665db6a...scainburger:7f2dbe19371fc19ee2f7dda1feb0bb4697d489ed#diff-27b24bcdd3d76fec8ce0a2ec9a20f97a3adc79203a49ea1eeb3716e53af6736dR124

**Comment by scainburger** [comment]
Thanks for the heads up @LlemonDuck. I've closed the clip in the `catch` clause as it wasn't behaving properly in the `finally`, please let me know if you forsee any issues with this.

**Pull request merged**
