### PR TITLE
Update world-heatmap

### PR DESCRIPTION
**Pull request by GrandTheftWalrus**
- Enabled automatic uploading of anonymous user heatmap data to osrsworldheatmap.com
- Changed image output filenames for better sorting
- Changed PLACES_SPOKEN_AT to include messages by players other than the local player

### CODE REVIEW

**Comment by cdfisher** [comment]
Your warning is a good start but should include something along the lines of `This plugin submits your IP address to a 3rd party website not controlled or verified by the RuneLite Developers.` as well.

**Comment by GrandTheftWalrus** [comment]
> Your warning is a good start but should include something along the lines of `This plugin submits your IP address to a 3rd party website not controlled or verified by the RuneLite Developers.` as well.

Tanks for the feedback. I added it.

**Comment by LlemonDuck** [comment]
We cannot show warnings to users after they have already installed the plugin. Since you have active users, you'll need to make this off by default and instead add a warning to the now opt-in config option.

**Comment by GrandTheftWalrus** [comment]
@LlemonDuck 
I've changed the data upload to be turned off by default with the warning on the checkbox:
image

**Comment by LlemonDuck** [comment]
don't do your network i/o in onGameTick, and switch it to use the injectable OkHttp client.

**Comment by GrandTheftWalrus** [comment]
> don't do your network i/o in onGameTick, and switch it to use the injectable OkHttp client.

Oopsies. I fixed it now

**Pull request merged**
