### PR TITLE
Update limpwurt-login

### PR DESCRIPTION
**Pull request by Gavin-TC**
Looks for `GameState` to be changed to `GameState.LOGGING_IN` rather than `GameState.LOGGED_IN`, since this would cause the plugin to play sounds everytime the player teleported, swapped worlds, loaded chunks, etc.

### CODE REVIEW

**Comment by YvesW** [comment]
Please don't close and open new PRs. You can convert to draft if it's not ready for merging.

**Comment by Gavin-TC** [comment]
> Please don't close and open new PRs. You can convert to draft if it's not ready for merging.

Ah, sorry, that's my bad. Is there anything I should do to this closed one, or just don't close a PR in the future?

**Comment by YvesW** [comment]
Nah, you already opened a new PR so can't do anything anymore. Just gotta remember that you can fix basically any problem without needing to close and/or open a new PR.

**Comment by Gavin-TC** [comment]
> Nah, you already opened a new PR so can't do anything anymore. Just gotta remember that you can fix basically any problem without needing to close and/or open a new PR.

Gotcha, thanks man.

**Pull request closed without merging**
