### PR TITLE
Update random-hopper to v1.3

### PR DESCRIPTION
**Pull request by rugg0064**
Update random-hopper to v1.3
* Block hop commands during loading and hopping game states
* Add persistent config

### CODE REVIEW

**Comment by YvesW** [comment]
Not an extensive review, but could you remove the prints, or at least make them log.debug?

FYI you don't need to unset a configuration before setting it. Also, when a config key doesn't exist yet, getConfiguration will return null, but I assume you accounted for that.

**Comment by rugg0064** [comment]
> Not an extensive review, but could you remove the prints, or at least make them log.debug?
I've removed the prints

> FYI you don't need to unset a configuration before setting it. Also, when a config key doesn't exist yet, getConfiguration will return null, but I assume you accounted for that.
Addressed the configuration unset.
getConfiguration should be handled by the generic try catch, I think at least.

**Comment by iProdigy** [comment]
```
random-hopper: plugin uses terminally deprecated APIs:
Use ComponentID or InterfaceID instead of WidgetInfo or WidgetID
```

**Comment by YvesW** [comment]
You're adding a binary file now.

**Comment by rugg0064** [comment]
> You're adding a binary file now.
😓 Apologies. I have no idea where that came from...

**Pull request merged**
