### PR TITLE
Update RHUD

### PR DESCRIPTION
**Pull request by Beardedrasta**
[Remodeled and Improved. Config options extended - xp tracker - toggles - fonts - colors - sizes.)

### CODE REVIEW

**Comment by Felanbird** [comment]
If you run into build errors, don't open a new PR, push changes to your existing PR

**Comment by Beardedrasta** [comment]
Trying to figure out how to make that happen. All i can find is create pull request not push

**Comment by Felanbird** [comment]
If you have a PR open any changes you push to the branch will _just_ appear, so however you are making your changes, just continue to do that, but without closing/opening PRs

**Comment by Felanbird** [comment]
Update the `master` branch on your fork of this repo, exactly like you already did earlier.
https://github.com/Beardedrasta/plugin-hub/commits/master

If you already did that, `git push` your change

**Comment by Bram91** [comment]
Dont rename your plugin file, keep using your old one. You can rename your plugin in your plugin itself. The plugin file is not userfacing so there is no need to ever rename it.

**Comment by Beardedrasta** [comment]
Ok noted, I will remember that for next pull. Thanks. Now to wait for it to get pulled. Haha. Cant wait for it to go live.

**Comment by Felanbird** [comment]
> Ok noted, I will remember that for next pull. Thanks. Now to wait for it to get pulled. Haha. Cant wait for it to go live.

What Bram91 said wasn't a suggestion btw, it won't be approved if you change the plugin file. 
Just update the old one with your new repo name & commit

**Comment by Beardedrasta** [comment]
I'm unsure what i should do now. I remodeled my entire layout and copy pasted stuff from my previous plugin file to the new one and deleted the other one. So since that plugin file is gone now my plugin cant be updated anymore?

**Comment by Bram91** [comment]
edit `plugins/rasta-hud` and change it to your new github repo & commit hash and dont create a new file named `plugins/rhud`

**Comment by Beardedrasta** [comment]
I fixed everything, Hopefully itll be grabbed soon, thanks guys!

**Comment by Nightfirecat** [comment]
Code LGTM, but it looks like very large sections were copied directly from core plugins without attribution. Please add copyright headers and/or other attribution as needed to indicate their original source.

**Comment by Beardedrasta** [comment]
Yeah not really sure what i can do to make this happen now. I updated and commited with the copyrights added from what i did take (noted most of it is my script i got the base from statusbars)

**Comment by Beardedrasta** [comment]
But after i updated with copyrights now its checking for the file i already fixed in the repo

**Review by Beardedrasta — COMMENTED** [review]
Nothing was changed but the copyrights added before the text but somehow failed the check now.

**Comment by Bram91** [comment]
Looks like you committed the wrong hash in your plugin file, I think you meant to use `98adb99ade22ac1d64643d07139981315beee7ee` since thats the commit that updates your runelite-plugin.properties to use the new class.

**Comment by Beardedrasta** [comment]
Ok fingers crossed it gets passed now i was excited to see nightfire commented cause thats usually a go. :( anywho thanks again.

**Comment by Beardedrasta** [comment]
Sorry for so many complications, I just like the way statusbars stock plugin had its layout, was much cleaner then mine so converted my script into that model and added alot more, Just forgot to add in the copyrights from it.

**Pull request merged**
