### PR TITLE
Added Audible loot notification plugin

### PR DESCRIPTION
**Pull request by Pfannaa**

### CODE REVIEW

**Comment by YvesW** [comment]
Please don't close and open new PRs. Read the build the log, fix the issue, and push a new commit commit hash to this same branch.

**Comment by Pfannaa** [comment]
@YvesW 
Gotcha. Sorry if it caused any inconveniences.
Checks should pass now.

**Comment by CreativeTechGuy** [comment]
Hey @Pfannaa, I'm not sure if this plugin is needed since this use-case (and tons more) are already covered by [Watchdog](https://runelite.net/plugin-hub/show/watchdog). For example, below is an alert I have which plays a custom sound, and flashes the screen and shows an overlay when I receive a drop valued at 10M-999M.

You can easily create custom alerts for almost anything you want using Watchdog which can play any sound file on your computer and be triggered by most actions in the game.

```
{
    "type": "ChatAlert",
    "message": "Valuable drop: .* \\(\\d{2,3},\\d+,\\d+.*",
    "regexEnabled": true,
    "enabled": true,
    "name": "Massive valuable drop",
    "debounceTime": 100,
    "notifications": [
        {
            "type": "Sound",
            "path": "super-sound.wav",
            "gain": 4,
            "fireWhenFocused": true,
            "fireWhenAFK": false,
            "fireWhenAFKForSeconds": 1
        },
        {
            "type": "Sound",
            "path": "super-sound.wav",
            "gain": 9,
            "fireWhenFocused": true,
            "fireWhenAFK": true,
            "fireWhenAFKForSeconds": 10
        },
        {
            "type": "ScreenFlash",
            "color": "#9400FF00",
            "flashMode": "FLASH",
            "flashDuration": 0,
            "fireWhenFocused": true,
            "fireWhenAFK": false,
            "fireWhenAFKForSeconds": 1
        },
        {
            "type": "Overlay",
            "color": "#4613FF00",
            "textColor": "#FFFFFFFF",
            "sticky": false,
            "timeToLive": 5,
            "message": "Massive Drop!",
            "fireWhenFocused": true,
            "fireWhenAFK": false,
            "fireWhenAFKForSeconds": 1
        }
    ]
}
```

**Comment by Pfannaa** [comment]
Hey @CreativeTechGuy , didn't even know about Watchdog. Just saw the ImaDrum Alerts plugin and thought i'd do my own with some funny sounds.

**Comment by CreativeTechGuy** [comment]
@Pfannaa I'm not anyone important so this is just a community member's opinion. But I think it's a dangerous trend to have tons of very similar plugins, especially when the features overlap heavily. So I'd vote to have people contribute to existing plugins when they need features rather than forking and creating their own plugin which is 90% the same. Or in this case, this feature is covered completely by an existing plugin.

I don't want to diminish what you are doing. Like it's great that people want to create new plugins and build stuff. But it feels like that effort could be spent tackling the harder/unique problems that haven't been solved before.

**Comment by Pfannaa** [comment]
@CreativeTechGuy While i generally agree with your sentiment, i really like the plugin hubs aspect that the user decides which plugin they want to install or not.
If someone decides that predefined sounds are more their thing, maybe this plugin fits their needs more than one in which they would have to find own sounds. Maybe some functionality which watchdog doesn't cover will come over time, since this is just version 1.0 (if even). Maybe a user doesn't need visualized triggers and doesn't want to deal with all the overhead it brings. If a user doesn't like the plugin, just uninstall it and find another one which meets your personal needs, since that's what the plugin-hub is for. I feel a bit different about this and wouldn't call i a dangerous trend.

**Comment by Felanbird** [comment]
> If someone decides that predefined sounds are more their thing, maybe this plugin fits their needs more than one in which they would have to find own sounds. 

We don't have the rights to distribute most if not all of these sounds, which is why plugins like watchdog require user setup. (especially not the one owned by Mojang/Microsoft). It's not a user accessibility thing, it's a legal thing. 
https://github.com/runelite/plugin-hub/pull/3380#issuecomment-1259735450
https://github.com/runelite/plugin-hub/pull/4016#issuecomment-1460194162
https://github.com/runelite/plugin-hub/pull/4576#issuecomment-1640504322
https://github.com/runelite/plugin-hub/pull/3767#issuecomment-1384850598

> Maybe a user doesn't need visualized triggers and doesn't want to deal with all the overhead it brings.

If you don't want visualized triggers from watchdog, what's stopping you from just not adding a visualized trigger, to your notification?

> wouldn't call i a dangerous trend, it's rather using the plugin-hub's flexibility.

It's definitely a dangerous trend we're trying to put a stop to, there's almost 10 discord plugins that basically all do the same thing but for a different "type" (collection/loot/death/gim/etc) which we've now shown is very easily maintained as a single plugin

**Comment by Pfannaa** [comment]
@Felanbird I got all the sounds from https://freesound.org/ on which i assumed come from individuals which recreated these sounds. 
Because they are stating: "Freesound aims to create a [huge collaborative database](https://blog.freesound.org/?s=numbers) of audio snippets, samples, recordings, and all sorts of bleeps, ... released under Creative Commons licenses that allow their reuse." at https://freesound.org/help/about/

**Comment by Felanbird** [comment]
Then you should probably document that information somewhere, especially if your plan is to have users add more files. 
Previous to that comment all that was seen is a bunch of sound files included, one of which sounding exactly like it was pulled out of Minecraft.

**Comment by Pfannaa** [comment]
Yeah i get that. That's on me.
I'll put the link and the statements into my plugin repo if that's okay.

**Comment by pajlada** [comment]
Not all sound on freesound.org are CC0, some require attribution, some prohibit commercial use. I'd err on the side of caution and map the audio files to a freesound.org link so the license can be verified by others

**Comment by Pfannaa** [comment]
@pajlada Sounds good. Gonna do that tomorrow.

**Comment by Pfannaa** [comment]
Added links to each sound including the creators names in the readme

**Pull request merged**
