### PR TITLE
update monster-monitor to 1.3.0

### PR DESCRIPTION
**Pull request by ChunkyAtlas**
feat: Improve UI, background tasks, and better despawn handling

- Wrapped all UI updates like `repaint()` in `SwingUtilities.invokeLater()` to ensure smooth, flicker-free interactions.
- Made logging more efficient by using `BufferedWriter` and moving save operations to a background thread with `saveLogAsync()`.
- Cleaned up the `onMenuOpened()` logic in `MonsterMonitorMenuHandler` by breaking it into smaller methods—easier to read and tweak.
- Refactored the `MonsterMonitorBox` to make the UI layout code more modular. It’s now much easier to follow.
- Improved despawn handling in `DeathTracker` by splitting out conditions into helper methods—makes it easier to understand and modify.
- Made sure that the overlay updates properly whenever NPC data changes.
- Improved number formatting—big numbers are now displayed as "1k" or "1.5m" for easier reading.
- Updated the font to 'SansSerif' for a cleaner, more modern look.
- Tweaked the kill limit spinner to handle large numbers better while staying compact.
- Enhanced the logger to automatically update old logs with any missing information required for new features.
- Made the startup process smoother, ensuring the overlay is in the right state from the start.
- Cleaned up the options panel layout for a more polished overall look and feel.
- Added a new `ProgressBar` that tracks progress towards NPC kill limits:
  - The bar changes color as you get closer to your goal, shifting from red to orange to green.
- Fixed a bug where bosses with large areas (like Tempoross) would count as a kill when they moved out of view—now it only counts when you actually kill them.
- Adjusted Giant Mole tracking to ignore its digging phases—only the final phase counts as a kill.
- Added right-click options to "Ignore" or "Monitor" NPCs directly from the game interface.
- Added a config option for toggling these right-click menu entries.
- Fixed an issue where the overlay and progress bar wouldn’t snap like other overlays.

### CODE REVIEW

**Comment by ChunkyAtlas** [comment]
Should be the last fix (Unless you guys find something I messed up)

**Comment by ChunkyAtlas** [comment]
> Should be the last fix (Unless you guys find something I messed up)

Okay for real this time

**Comment by Adam-** [comment]
Please remove your `com.google.code.gson:gson:2.8.5` dependency. This is already a transitive dependency via the client and redefining it is causing gson to get repacked with your plugin.

**Comment by ChunkyAtlas** [comment]
> Please remove your `com.google.code.gson:gson:2.8.5` dependency. This is already a transitive dependency via the client and redefining it is causing gson to get repacked with your plugin.

Removed! Sorry about that

**Pull request merged**
