### PR TITLE
Schboop

### PR DESCRIPTION
**Pull request by katlande**
This is a fan-made plugin for OSRS youtuber Schboop's community. It plays sound clips from Schboop's videos in reaction to various triggers.

### CODE REVIEW

**Comment by LlemonDuck** [comment]
You need to put your code into a separate repository instead of committing it against this repo

https://github.com/runelite/plugin-hub?tab=readme-ov-file#submitting-a-plugin

**Comment by katlande** [comment]
> You need to put your code into a separate repository instead of committing it against this repo
> 
> https://github.com/runelite/plugin-hub?tab=readme-ov-file#submitting-a-plugin

Can you clarify what this means? Sorry, I am really god awful at git. I used these instructions to set up this request and thought I had followed them exactly.

**Comment by Felanbird** [comment]
You skipped step 1 https://github.com/runelite/plugin-hub?tab=readme-ov-file#creating-new-plugins as you don't have a repo that was generated from `runelite/example-plugin`

Your repo will have this little note at the top like [quest-helper](https://github.com/Zoinkwiz/quest-helper) does 
image

**Comment by YvesW** [comment]
You accidentally PRed from the wrong branch (not your ``patch-1`` branch, but your ``Schboop`` branch which contains your plugin's code instead of the pluginhub file). You can either:
- Move your Schboop branch commits to another branch, then make sure the ``Schboop`` branch contains just the commits from the ``patch-1`` branch (with some changes to the file if necessary) and force push.
- Or close this PR and open a PR from the correct branch. I generally never recommend closing a PR, but the feature branch you PR from can't be changed once the PR is created AFAIK.

You might also want to consider renaming your repo to e.g. ``kat-RL-plugins`` in case you want to create more plugins as branches of that repo in the future. Currently it's a fork of runelite/plugin-hub and you can fork a repo once. Doesn't matter that much, but it's a bit weird if you submit ``NewNotSchoobPlugin`` from the ``Schboop`` repo in the future.

**Pull request closed without merging**
