### PR TITLE
Create PM Colors

### PR DESCRIPTION
**Pull request by PresNL**
This plugin adds the ability to highlight private messages from certain users in a specified color when using split private chat

[Plugin at work](https://gfycat.com/fewnegativeanhinga)

### CODE REVIEW

**Comment by PresNL** [comment]
Converted to draft as I'm adding some extra functionality that might break currently highlighted players

**Comment by PresNL** [comment]
Plugin has now been updated with new functionality that allows you to specify which color to highlight certain users in

[Plugin at work](https://gfycat.com/glitteringecstaticbird)

**Comment by PresNL** [comment]
This functionality was request in https://github.com/runelite/runelite/issues/10316

**Comment by PresNL** [comment]
Plugin now has a much more robust way of setting the colors thanks to Rayni and Hydrox and I have added toggles for highlighting the Message content, username and log in/out message (with default settings in the config to match) 

[Plugin at work](https://gfycat.com/snivelingpersonalinsect)

**Comment by PresNL** [comment]
I also works in all private chats now instead of only in split private chat

**Comment by Nightfirecat** [comment]
Please add a support URL to your runelite-plugin.properties file.

**Comment by PresNL** [comment]
Woops, I have added it

**Pull request merged**
