### PR TITLE
Cm auto splitter

### PR DESCRIPTION
**Pull request by SkyBouncer**
Plugin for automating splits in the LiveSplit program for cox challenge mode.

### CODE REVIEW

**Comment by Nightfirecat** [comment]
We don't want plugins to send keypresses with `Robot`.

**Comment by SkyBouncer** [comment]
Do you have a preferred alternative, or is keypresses a no go?

**Comment by Nightfirecat** [comment]
Other plugins which interact with external plugins will either invoke commands ([eg. bitwarden plugin](https://github.com/runelite/plugin-hub/blob/master/plugins/bitwarden-plugin#L3)) or load an SDK to interface with some external software. I'd recommend looking into alternatives such as that. I don't see there being situations where simulating keypresses will be acceptable.

**Comment by Hannah-GBS** [comment]
LiveSplit has a [server component](https://github.com/LiveSplit/LiveSplit.Server) you could use. Not sure about other split programs.

**Comment by SkyBouncer** [comment]
Ok, it's updated.

**Comment by Nightfirecat** [comment]
Your LICENSE must give attribution to De0 as you are using some of his code. This looks good otherwise.

**Comment by SkyBouncer** [comment]
I'm not that familiar with open source licenses, but hopefully it's good now

**Pull request merged**
