### PR TITLE
Add video recorder

### PR DESCRIPTION
**Pull request by Skretzo**
Changes that could improve the performance of this plugin are highly appreciated.

-----

# Video Recorder
icon

## Info
Capture the in-game screen as a video.

The output video file is encoded with the [TechSmith Screen Capture Codec](https://www.techsmith.com/codecs.html) and stored in an AVI file container. To play the video you must either use [VLC media player](https://www.videolan.org/vlc/) or install the aforementioned [TSCC codec](https://www.techsmith.com/codecs.html). The latter will also allow you to edit the video in a video editing software. The output video file will use the current timestamp as its name and be saved to a folder named `videos` inside your `.runelite` folder. A button in the plugin panel with the text `Open output folder` will take you directly there.

animation

## Config options
- Stop on logout: `false`
  - Whether to stop the video recording when your in-game character is logged out.
- Exclude login screen: `false`
  - Whether to pause the video recording when the login screen is displayed.
- Include cursor: `true`
  - Whether to include the cursor in the video.
    To use a custom cursor place a file 'cursor.png' in the '.runelite' folder.
- FPS: `25`
  - The framerate (frames/second) for the video.
- Keyframe interval: `80`
  - The interval (number of frames) between keyframes (versus delta/prediction frames)
    - A lower interval (e.g. 1) gives a bigger output file, but faster seeking (good for editing)
    - A moderate interval (e.g. 80) gives a good trade-off between output file size and seeking (recommended)
    - A higher interval (e.g. 50 FPS * 60 seconds = 3000) gives a smaller output file, but slower seeking (good for archiving)
- Compression level: `6`
  - The amount of compression for each video frame
    - 1: fast compression (bigger file size, faster seeking)
    - 6: default compression (recommended)
    - 9: high compression (smaller file size, slower seeking)
- Start video hotkey: `Not set`
  - The hotkey that will start the video recording. Alternatively use the start button in the plugin panel.
- Stop video hotkey: `Not set`
  - The hotkey that will stop the video recording. Alternatively use the stop button in the plugin panel.

## Acknowledgements
This plugin is using the [Monte Media Library](http://www.randelshofer.ch/monte/) to create video files, a project under the [Creative Commons BY 3.0 license](http://www.randelshofer.ch/monte/license.html#CCBY).

### CODE REVIEW

**Comment by Nightfirecat** [comment]
It looks like Monte Media Library is available via Maven central. Can you add that dependency rather than inlining it in your project?

**Comment by Nightfirecat** [comment]
Monte Media Library is 1/5th the size of the entire RuneLite project, which is already very large. This is not reasonable for us to review in full.

**Comment by Skretzo** [comment]
Most of Monte Media Library is superfluous for this plugin. Would you be willing to review this again if I inlined a minimal version of only the necessary parts? Like I did the first time around, but less abstraction (it was 35 classes).

**Comment by Nightfirecat** [comment]
We'd be willing to consider it in that state, yes.

**Comment by Skretzo** [comment]
> consider it in that state

Are you referring to the [previous state](https://github.com/Skretzo/runelite-plugins/tree/59442dcc0db9c332f314fa65118be0f1dd4a2fab/src/main/java/com/videorecorder/video) or the proposed state with less abstraction? What would suit you and/or the other reviewers best?

**Comment by Nightfirecat** [comment]
With less abstraction, if possible.

**Comment by Skretzo** [comment]
I have now inlined the project with less abstraction (15 classes vs previously 35).
Would you like me to remove javadoc and comments, which constitutes roughly 35 % of the code lines?

**Comment by Nightfirecat** [comment]
Comments/javadoc aren't an issue, I'll let you know once I get around to looking through it.

**Comment by Skretzo** [comment]
No problem and no need to hurry. You don't need to prioritize this plugin even though it has been around for a while :)

**Pull request merged**
