### PR TITLE
Create happy-jewelry

### PR DESCRIPTION
**Pull request by astroferrous**
Happy Jewelry new plugin request!

Plays a sound to let you know your jewelry enjoyed being rubbed.

### CODE REVIEW

**Comment by tylerwgrass** [comment]
```
happy_jewelry: invalid plugin file name "happy_jewelry"
in file plugins/happy_jewelry
plugin file names must be lowercase alphanumeric + dashes. try: "happy-jewelry"
```

**Comment by astroferrous** [comment]
> ```
> happy_jewelry: invalid plugin file name "happy_jewelry"
> in file plugins/happy_jewelry
> plugin file names must be lowercase alphanumeric + dashes. try: "happy-jewelry"
> ```

updated

**Comment by iProdigy** [comment]
You are opening `InputStream`s but never close them; please fix this resource leak

Also your `soundVolume` config option is not implemented

**Comment by astroferrous** [comment]
> You are opening `InputStream`s but never close them; please fix this resource leak
> 
> Also your `soundVolume` config option is not implemented

Updated. I've pushed the changes to my plugin repo and changed the commit SHA in the plugins/happy-jewelry file; is that all that's required to do for updating?

**Comment by LlemonDuck** [comment]
Yep

**Comment by LlemonDuck** [comment]
This plugin kinda pushes the boundaries on what we consider unsavoury to host. If you would prefer not to drop the idea, you can update the plugin to support a custom sound file from the .runelite directory instead, use a less overtly sexual sound as the default, and override it on your own install with whatever you feel like hearing.

**Comment by astroferrous** [comment]
> This plugin kinda pushes the boundaries on what we consider unsavoury to host. If you would prefer not to drop the idea, you can update the plugin to support a custom sound file from the .runelite directory instead, use a less overtly sexual sound as the default, and override it on your own install with whatever you feel like hearing.
> 
> Otherwise if you don't plan on doing that, just close the PR.

updated to use new sound from .runelite dir

**Comment by iProdigy** [comment]
You can ignore that secondary failure; `This plugin requires a review from a Plugin Hub maintainer. The reviewer will request any additional changes if needed.`

**Comment by astroferrous** [comment]
> This plugin kinda pushes the boundaries on what we consider unsavoury to host. If you would prefer not to drop the idea, you can update the plugin to support a custom sound file from the .runelite directory instead, use a less overtly sexual sound as the default, and override it on your own install with whatever you feel like hearing.
> 
> Otherwise if you don't plan on doing that, just close the PR.

Is there anything else I need to do for this to be reviewed?

**Comment by tylerwgrass** [comment]
Just wait, reviews are done in reviewers' free time and with leagues happening right now that might mean reviews take longer as people are enjoying the game mode.

**Comment by LlemonDuck** [comment]
* replace printStackTrace with log.error https://github.com/astroferrous/happy-jewelry/blob/1289f62b170241cbeb7e00d0f155f0e783c500f9/src/main/java/com/happyjewelry/HappyJewelryPlugin.java#L124

**Pull request merged**
