### PR TITLE
Create zeahrctracker

### PR DESCRIPTION
**Pull request by Waldxn**
Tracks Blood/Soul runes crafted in Zeah, as well as your profit.

### CODE REVIEW

**Comment by Waldxn** [comment]
License check now failing after new push? File is still in repo.

**Comment by Nightfirecat** [comment]
You need to update the plugin manifest to point to a commit which has LICENSE pushed. eg. `13481cf9fba8b375187786b97c053b70c8637b92`, not `9073aa638b43520978d515799ced32e2245df93c`

**Comment by Waldxn** [comment]
Thanks, so I need to push the license file every time I need to update the plugin?

**Comment by Nightfirecat** [comment]
No, you just need to update the manifest when you want changes to reflect in this PR

**Comment by Waldxn** [comment]
Does everything look good to merge?

**Comment by Waldxn** [comment]
Hide the plugin if you could please. Need to fix an issue with data storage.

**Comment by Nightfirecat** [comment]
Open a PR adding `disabled=temporarily disabled while fixes are in development` to the manifest if you like

**Pull request merged**
