### PR TITLE
Object Highlighter

### PR DESCRIPTION
**Pull request by ShaneeexD**
Enables players to highlight any in-game object with customizable colors and styles through a simple shift + right-click interface.

Includes individual highlighting or "All"

### CODE REVIEW

**Comment by YvesW** [comment]
Why are you trying to remake object indicators? What does this plugin do significantly different that the core plugin doesn't already do (better)?

**Comment by ShaneeexD** [comment]
> Why are you trying to remake object indicators? What does this plugin do significantly different that the core plugin doesn't already do (better)?

Mine allows to tag "All" of that object ID as well as individually, which can be useful for certain cases

**Comment by raiyni** [comment]
We no longer allow highlight by id plugins

**Comment by ShaneeexD** [comment]
> We no longer allow highlight by id plugins

Ah okay then, sorry for asking but I'm curious as to why

**Comment by cdfisher** [comment]
> > We no longer allow highlight by id plugins
> 
> Ah okay then, sorry for asking but I'm curious as to why

There's too much potential for abuse, and it puts a big burden on reviewers.

**Pull request closed without merging**
