### PR TITLE
add decimal-prices

### PR DESCRIPTION
**Pull request by rmaes4**
This plugin lets you type decimals when buying and selling at the GE. For example you can type "1.2m" and it will be entered as "1,200,000". This saves you from having to type longer numbers.

### CODE REVIEW

**Comment by Nightfirecat** [comment]
You must [license your repository.](https://github.com/runelite/plugin-hub#licensing-your-repository)

**Comment by rmaes4** [comment]
> You must [license your repository.](https://github.com/runelite/plugin-hub#licensing-your-repository)

I thought I did? 

Screen Shot 2020-09-07 at 11 32 23 AM

**Comment by rmaes4** [comment]
It should be fixed now.

**Review by Nightfirecat — APPROVED** [review]
LGTM. I'm fine with this if others are as well.

**Comment by rmaes4** [comment]
Just curious, when will this be merged?

**Pull request merged**
