### PR TITLE
adding EventsAPI Plugin to PluginHub

### PR DESCRIPTION
**Pull request by morgan-vanv**
Hello!
I appreciate y'all taking the time to look this over. Much of EventsAPI's current functionality is directly taken from the OSRSEvents Plugin. My only major change from this so far is to add the periodic polling of run energy, map position, etc. and adding that as a new type of request option. Everything else is basically the same so far besides that.

If I only intended to make this small change I likely would've attempted to just reach out and merge my changes into their branch, but in the future, I want to be able to have full control so I can support my specific use cases. Again, most of all of this information is in my README so I won't repeat myself necessarily and give y'all twice as much to read. 

It might help in your review process to do a `git diff` between my repo and OSRSEvents as considering that plugin is already approved and it is 90% of what this plugin is, hopefully this whole process doesn't take up too much of your time.

If you need anything else from me, please don't hesitate to reach out. Also I encourage any feedback if you have it.
Also, apologies if this is not done in the proper way. I've been scouring the wiki and READMEs, so I think this is correct but as this is my first plugin I'm sure its possible I might be overlooking something.

All the best!

### CODE REVIEW

**Comment by Nightfirecat** [comment]
You don't have to keep closing and reopening the PR, you can just push new commits and CI will build them

**Comment by morgan-vanv** [comment]
> You don't have to keep closing and reopening the PR, you can just push new commits and CI will build them

thanks so much for the heads up. apologies for being a clown and likely pinging y'all a lot

**Comment by morgan-vanv** [comment]
should I be concerned / doing anything to address this skipped 'upload' test?

**Comment by Nightfirecat** [comment]
No, the upload job does not run for pull requests

**Comment by morgan-vanv** [comment]
hey y'all! I know it says to be patient in the docs/wiki but I was just curious what the timeline/ETA might be on this. also if there is anything I need to modify or anything y'all need from me please don't hesitate to reach out.

all the best

**Comment by morgan-vanv** [comment]
hey I'm sorry to pester y'all again, but should I avoid updating / improving the plugin until it is merged? I've done some refactoring to streamline things, but I don't want to interrupt, delay, or otherwise complicate the review process

thanks again, 
morgan

**Comment by Nightfirecat** [comment]
Generally you can always push updates so long as nobody's told you (recently) that they were actively reviewing; we'll just review the full diff once we get to it regardless

**Pull request merged**
