### PR TITLE
Create baplus

### PR DESCRIPTION
**Pull request by hisean1**
BAPlus provides speedrunning splits in the chat, as well as point breakdowns at the end of a game.

See PR: https://github.com/runelite/runelite/pull/12405 for more detailed info.

### CODE REVIEW

**Review by Nightfirecat — CHANGES_REQUESTED** [review]
You must [license your repository.](https://github.com/runelite/plugin-hub#licensing-your-repository)

**Comment by Nightfirecat** [comment]
Someone in Discord mentioned, is the plugin icon taken from a streamer's set of emotes? If so, have you gotten permission to use it?

**Comment by hisean1** [comment]
> Someone in Discord mentioned, is the plugin icon taken from a streamer's set of emotes? If so, have you gotten permission to use it?

image

emote in question is coxiePremium

**Comment by Nightfirecat** [comment]
Looks like you're still using the wrong commit. LICENSE was added in 28d56b6eb7adce84c506546c95de7915c95bcd97, can you use that as the commit hash for this PR? Thanks.

**Comment by hisean1** [comment]
I have no idea why I put that commit hash in there...

I added a tiny bit more functionality, updated the readme, and hopefully have chosen the most recent hash (which includes the license).

**Pull request merged**
