### PR TITLE
add hunter pouch overlay plugin

### PR DESCRIPTION
**Pull request by trs**
This plugin adds an overlay to the hunter pouches showing the number of meat/furs inside.

icon

### CODE REVIEW

**Comment by trs** [comment]
I've found a few issues I'd like to sort out before adding to the hub

**Comment by Felanbird** [comment]
Just switch this PR to a draft until you've made the changes you feel necessary, and then update this PR to the new commit hash.

**Comment by trs** [comment]
Okay, after some fixes and testing this should be working good now. It previously wasn't taking into account if multiple actions were occurring during a single tick (like filling both meat and fur pouches quickly).

**Comment by Nightfirecat** [comment]
I see your plugin doesn't currently have any config options, [but "pouch" isn't a sufficiently distinct config group](https://github.com/trs/runelite-hunter-pouch-overlay/blob/dcc682ba14bb869cdbc2ac7f80aacfb466aa0da3/src/main/java/com/pouch/HunterPouchConfig.java#L7); please either remove the config interface or change the config group to be more unique. (either would help avoid possible conflicts in the future should you decide to add configs later on)
Code LGTM otherwise

**Comment by LlemonDuck** [comment]
Convert this off of draft when you've made the requested changes

**Comment by MESLewis** [comment]
Closed for inactivity, you can reopen this if you would like to make the requested changes.

**Pull request closed without merging**
