### PR TITLE
adds bingo helper

### PR DESCRIPTION
**Pull request by IronEvil478**
A plugin to help support clan bingo events through runelite. This takes in a Json string defining all the items of the bingo and when one of the items is gained it will send a screenshot to discord through a web hook.

### CODE REVIEW

**Comment by iProdigy** [comment]
have you considered using an existing discord webhook plugin that supports arbitrary item allowlists?

**Comment by IronEvil478** [comment]
So I looked through the hub filtered on the tag discord looking for something, I grabbed some honorable mentions but none matched the goal of a simple setup for the end user for clan events.
I looked at the following:
1. https://runelite.net/plugin-hub/show/discord-screenshot
2. https://runelite.net/plugin-hub/show/droptracker
3. https://runelite.net/plugin-hub/show/clan-tracker
4. https://runelite.net/plugin-hub/show/clan-chat-webhook
5. https://runelite.net/plugin-hub/show/better-discord-loot-logger
6. https://runelite.net/plugin-hub/show/universal-discord-notifications
7. https://runelite.net/plugin-hub/show/dink

A common issue I came across was that the setup was super complex requiring changing in-game settings along with a number of plugin settings for some to function at all. Others had the issue that they were not tied to item names but rather everything over a value, this doesn't work great for the bingos my clan hosts and, as other items fall in price that could get that number rather low to catch all the barrows items(A common tile I've seen across many clan events).

If you have another plugin that matches the simplicity of a single string setup for everything or one that is simple to set-up with a fixed list of items I'm happy to look it over to use or maybe look to work on with said creator.

**Comment by iProdigy** [comment]
> If you have another plugin that matches the simplicity of a single string setup for everything or one that is simple to set-up with a fixed list of items I'm happy to look it over to use or maybe look to work on with said creator.

dink supports an item allowlist and you can do `::dinkexport`/`::dinkimport` to simplify sharing the setup, and it may be even easier once https://github.com/pajlads/DinkPlugin/pull/488 is merged (disclosure: i'm a maintainer of that plugin)

**Comment by Nightfirecat** [comment]
Do you have any thoughts on prodigy's comment above? I'm happy to review this if it's still wanted, but if dink covers this use case sufficiently, I'm happy also for it to be a stand-in for this use case.

**Comment by IronEvil478** [comment]
> Do you have any thoughts on prodigy's comment above? I'm happy to review this if it's still wanted, but if dink covers this use case sufficiently, I'm happy also for it to be a stand-in for this use case.

I did have a long think on it, I’d like for it to be added with the custom messaging as well as the noting of what team the post is for. After I have the clan try it I do plan to expand it based around there feedback as well as any other clan that uses it.

**Comment by raiyni** [comment]
I believe this plugin covers this already? https://runelite.net/plugin-hub/show/bingo-event-automated

**Pull request merged**
