### PR TITLE
Add Music replacer

### PR DESCRIPTION
**Pull request by alowaniak**
Gives the ability to replace music tracks with music of your own choosing (as requested in runelite/runelite#3390).
See the [readme](https://github.com/alowaniak/music-replacer/blob/master/README.md) for more details.

### CODE REVIEW

**Comment by Nightfirecat** [comment]
Does this plugin really need to distribute nearly 400mb of ffmpeg binaries? And why is adding a new maven repo needed?

**Comment by alowaniak** [comment]
> Does this plugin really need to distribute nearly 400mb of ffmpeg binaries? And why is adding a new maven repo needed?

I'm also not too happy with the ffmpeg distribution, but I've had a hard time finding (mp3/AAC) audio players* in java.
In the jar it should shrink to 160mb and currently I'm only possibly extracting 3 out of the 8 so (for the time-being) I could half that.
(I've only got a windows machine so I can't personally test the others.)

I'm using the extra maven repo to pull a github dependency to not have to do too much low level audio playing on my own.
It's quite tiny though, so I could just roll it within the source without that much effort.


*: I *might* be able to get it to work with mp3spi & JAAD
But when I tried with jlayer/JAAD it wasn't playing any sound and I couldn't really figure out why.

**Comment by abextm** [comment]
We require all plugin hub jars to be <=10MiB, and now the build script enforces that, so this will no longer build. In addition we require that you pin your dependencies [as per the readme](https://github.com/runelite/plugin-hub#third-party-dependencies), which is definitely incompatible with how you have versioned `AudioCue`, and incompatible with anything from jitpack that doesn't explicitly have a reproducible build. Further, I need a way to verify that your natives are not malicious, which I have no good way of doing other than building them myself, which I'm not particularly interested in doing, especially for something as large and unwieldy as FFmpeg.

**Comment by alowaniak** [comment]
I must admit I was doubting it would get accepted, mainly because of the "verify that your natives are not malicious" part (I wasn't aware of size limits but it's understandable).

I assume the `NewPipeExtractor` dependency with jitpack is allowed? Would other jitpack dependencies pinned with `short commit hash` be

**Comment by alowaniak** [comment]
I must admit I was doubting it would get accepted, mainly because of the "verify that your natives are not malicious" part (I wasn't aware of size limits but it's understandable).

I assume the `NewPipeExtractor` dependency with jitpack is allowed? Would other jitpack dependencies pinned with `short commit hash` be

**Comment by alowaniak** [comment]
I've removed the FFmpeg binaries and now download via an API that does to `.wav` conversion.
(Local files won't be converted though, so those need to be `.wav`.)
I've also "inlined" the `AudioCue`, mostly because I plan on tailoring it more to my use-case.

**Comment by Nightfirecat** [comment]
Who owns `https://4rri42wrbl.execute-api.us-east-1.amazonaws.com`? Is it a free-for-public-use API, or do we have their blessing to access it?

**Comment by alowaniak** [comment]
> Who owns `https://4rri42wrbl.execute-api.us-east-1.amazonaws.com`? Is it a free-for-public-use API, or do we have their blessing to access it?

I've created it specifically for this plugin 😅

**Review by Nightfirecat — APPROVED** [review]
LGTM

**Review by abextm — CHANGES_REQUESTED** [review]
I can't tell if this is secure or not given its heavy use of reflection and execution of code that has came over the network.

**Comment by abextm** [comment]
Since this has outstanding required changes and hasn't been updated for a while, I am closing it as stale. You can reopen it once you make the required changes.

**Comment by alowaniak** [comment]
> Since this has outstanding required changes and hasn't been updated for a while, I am closing it as stale. You can reopen it once you make the required changes.

I've removed all dependencies it now only connects to my own server.

**Comment by Nightfirecat** [comment]
It looks like [AudioMixerTrack is licensed under GPLv3?](https://github.com/alowaniak/music-replacer/blob/33e3df32e0dc8623b7d621fe2a5a9c81688a249a/src/main/java/com/adonax/audiocue/AudioMixerTrack.java#L5-L9) We can't distribute GPL code.

**Comment by alowaniak** [comment]
> It looks like [AudioMixerTrack is licensed under GPLv3?](https://github.com/alowaniak/music-replacer/blob/33e3df32e0dc8623b7d621fe2a5a9c81688a249a/src/main/java/com/adonax/audiocue/AudioMixerTrack.java#L5-L9) We can't distribute GPL code.

Hmm I didn't catch that. On the repo https://github.com/philfrei/AudioCue it just said BSD
I guess it's copied of an earlier project...?
I'm not too versed in licenses and legal matters but I assume it would be okay if I just remove the AudioMixerTrack?

**Comment by Nightfirecat** [comment]
Yes, if that was removed (and no other files are similarly GPL licensed) that would resolve this issue.

**Review by Nightfirecat — APPROVED** [review]
LGTM

**Pull request merged**
