### PR TITLE
Create alch-items

### PR DESCRIPTION
**Pull request by ajsprojects**
Plugin that shows you the best items to high alch

### CODE REVIEW

**Comment by ajsprojects** [comment]
Any idea what I can do to reduce the output jar file size?

**Comment by Adam-** [comment]
It's probably due to this `htmlunit` you've added, how large is it?

**Comment by ajsprojects** [comment]
> It's probably due to this `htmlunit` dep you've added, how large is it?

Only 2MB according to maven repo. If it is causing the issue is there any workout aside from not using it?

**Comment by Adam-** [comment]
The total size of it also includes its transitive dependencies, so it could be large. If you are using it to read the wiki, maybe look at using the wikis api instead?

**Pull request closed without merging**
