### PR TITLE
Bone Running Plugin

### PR DESCRIPTION
**Pull request by Elrol**
This is a plugin was made to make bone running easier
It adds lots of features: 
-Displaying clan chat above the chat window
-A calculator to price bone ran
-Turns 1 trade request into 8 to keep the client from having to spam trade
-Allows you to set a client to highlight and filter messages sent by them
-Filters trade chat to hide messages that aren't trade requests
-Allows for coloring the clan chat as well as displaying ranked members in a different color
-Switches the Offer option with the Offer All option to make trades easier

It also has some clan specific features for Run4Less
-Runner data, which displays who you ran for, how many bones, what type of bones, how much you were paid etc
-Adds in chat bone calculator to price bones in chat
-Allows for the pinging of ranked members in the clan chat
-Will display the Run4Less logo if you are a ranked member in the clan

### CODE REVIEW

**Comment by Mrnice98** [comment]
is "Turns 1 trade request into 8 to keep the client from having to spam trade" in line with jagex rules ?

**Comment by Elrol** [comment]
I don't recall seeing anything against it, but if it is then I can easily remove that feature.
I will double check and make sure

**Comment by Mrnice98** [comment]
its just client side right, not sending the trade request to the person you are running for 8 times at once right ? i read it as the reverse initially.

**Comment by Elrol** [comment]
Yeah, it just posts the same request that was received multiple times to fill the chat box to make it easier to click them, it doesnt request a trade.

**Comment by abextm** [comment]
[This](https://github.com/Elrol/Run4LessPlugin/blob/25fe5314477c1e1c0b105faf96d4383f0b36b09a/src/main/java/com/github/elrol/run4lessplugin/Run4LessOverlay.java#L37) should be: `ImageUtil.getResourceStreamFromClass(Run4LessOverlay.class, "filename.png");` and the image should be included in the resources of your plugin. Ditto [here](https://github.com/Elrol/Run4LessPlugin/blob/25fe5314477c1e1c0b105faf96d4383f0b36b09a/src/main/java/com/github/elrol/run4lessplugin/Run4LessPlugin.java#L80-L81).

Neither of [these keys](https://github.com/Elrol/Run4LessPlugin/blob/25fe5314477c1e1c0b105faf96d4383f0b36b09a/src/main/java/com/github/elrol/run4lessplugin/Run4LessPlugin.java#L34-L35) should be set.

You need to remove all the stuff you add to various managers in `shutDown`.

Any [files you write](https://github.com/Elrol/Run4LessPlugin/blob/25fe5314477c1e1c0b105faf96d4383f0b36b09a/src/main/java/com/github/elrol/run4lessplugin/RunnerStats.java#L12) MUST be prefixed with/in a directory named something resembling your plugin's name

**Comment by Elrol** [comment]
Perfect, I will have those changes done in a short while and will recommit the changes.

**Pull request merged**
