### PR TITLE
lowercase-usernames: add plugin

### PR DESCRIPTION
**Pull request by dekvall**
Display usernames in upper/lowercase to avoid lookalikes

Closes: runelite/runelite#11386

### CODE REVIEW

**Comment by Eliofx92** [comment]
Can this be a default enabled plugin so it benefits everyone who uses RL?

**Comment by Spedwards** [comment]
> Can this be a default enabled plugin so it benefits everyone who uses RL?

It's an external plugin. Anyone who installs it will have it, those who don't want it, won't have it. Simple as that.

This won't be added to the main client.

**Comment by Eliofx92** [comment]
> > Can this be a default enabled plugin so it benefits everyone who uses RL?
> 
> It's an external plugin. Anyone who installs it will have it, those who don't want it, won't have it. Simple as that.
> 
> This won't be added to the main client.

I understand. I feel you're missing an opportunity to protect your users.

**Comment by Spedwards** [comment]
@dekvall The uppercase mode affects player levels and removes all colour from them. I don't think that this is ideal.

Uppercase levels

**Comment by nlruk** [comment]
Wow, that was fast! thanks for making this. 

Btw you only need lowercase mode to avoid lookalikes. I don't see the need for uppercase.

**Comment by nlruk** [comment]
Wow, that was fast! thanks for making this.

Btw you only need lowercase mode to avoid lookalikes. I don't see the need for uppercase. It actually causes the problem of the lookalike names.

Thanks again @dekvall

**Comment by Eliofx92** [comment]
> Wow, that was fast! thanks for making this.
> 
> Btw you only need lowercase mode to avoid lookalikes. I don't see the need for uppercase. It actually causes the problem of the lookalike names.
> 
> Thanks again @dekvall

no two characters look the same uppercase tho

**Comment by Eliofx92** [comment]
> > Can this be a default enabled plugin so it benefits everyone who uses RL?
> 
> It's an external plugin. Anyone who installs it will have it, those who don't want it, won't have it. Simple as that.
> 
> This won't be added to the main client.

I understand. I feel you're missing an opportunity to protect your users. 


> Wow, that was fast! thanks for making this.
> 
> Btw you only need lowercase mode to avoid lookalikes. I don't see the need for uppercase. It actually causes the problem of the lookalike names.
> 
> Thanks again @dekvall

no two characters look the same uppercase tho

**Comment by nlruk** [comment]
I see what you mean 😄

**Comment by nlruk** [comment]
There is a bug on DMM

Screenshot 2020-05-03 at 19 59 50


Screenshot 2020-05-03 at 19 58 52

**Comment by Nightfirecat** [comment]
@nlruk Please file this as an issue report to the maintainer of this plugin using their support link: `https://github.com/dekvall/runelite-external-plugins/tree/lowercase-usernames`

We don't manage the code or update cycle of plugin hub plugins. Plugin authors do.

**Comment by nlruk** [comment]
> @nlruk Please file this as an issue report to the maintainer of this plugin using their support link: `https://github.com/dekvall/runelite-external-plugins/tree/lowercase-usernames`
> 
> We don't manage the code or update cycle of plugin hub plugins. Plugin authors do.

sorry, I will do.

**Pull request merged**
