### PR TITLE
Create TranslationPlugin

### PR DESCRIPTION
**Pull request by PlayerCoder1**
Translates everything in the chatbox from NPC dialogs to Players talking on the side panel for now it's English to Spanish but I'm going to add more langages in the futur

### CODE REVIEW

**Comment by raiyni** [comment]
1. This plugin should adhere to their api usage and handle api limits correct https://mymemory.translated.net/doc/usagelimits.php
2. Don't spin up new threads every chat message, use an executor pool or something. 
3. Inject our okhttp client

**Comment by PlayerCoder1** [comment]
> 1. This plugin should adhere to their api usage and handle api limits correct https://mymemory.translated.net/doc/usagelimits.php
> 2. Don't spin up new threads every chat message, use an executor pool or something.
> 3. Inject our okhttp client

is everything good now?

**Comment by Nightfirecat** [comment]
We have not re-checked yet, please be patient

**Comment by PlayerCoder1** [comment]
Oh I didn't know it had to be in lower caps sorry

**Pull request closed without merging**
