### PR TITLE
Toa modern: life no more

### PR DESCRIPTION
**Pull request by PaJauKat**
Highlight target tile of Electric Skulls at Wardens P2

Show a counter for Mining Obelisk of Akkha Path

Let you hide "Choose" option on both supplies Bundles (there is a gif at "readme" file showing this)

### CODE REVIEW

**Comment by LlemonDuck** [comment]
> Highlight target tile of Electric Skulls at Wardens P2

This violates the Third Party Client Guidelines

> Show a counter for Mining Obelisk of Akkha Path

This is also a rejected feature of the existing Tombs of Amascut plugin, Jagex has requested that we do not add this feature. (LlemonDuck/tombs-of-amascut#19)


> Let you hide "Choose" option on both supplies Bundles (there is a gif at "readme" file showing this)

This one would be fine.

**Comment by PaJauKat** [comment]
so i have to delete some features and send a pull resquest again?

**Comment by LlemonDuck** [comment]
Yes, you can update this PR with a revised version of the plugin. The only feature so far that you could include is the "hide choose on supply bundles". 

I'm also the author of the existing Tombs of Amascut plugin, I'd be happy to accept contributions there if you are interested.

**Comment by PaJauKat** [comment]
I would like to contribute to your plugin, but it's my first plugin and would me so happy posting a plugin in my name. I have been wanting this for a while ;)

**Pull request merged**
