### PR TITLE
God Wars kill count info boxes

### PR DESCRIPTION
**Pull request by abd-khrubi**
This plugin replaces the GWD kc widget with info boxes.

kc-all

### CODE REVIEW

**Comment by DominickCobb-rs** [comment]
This would be a great addition to https://runelite.net/plugin-hub/show/better-godwars-overlay

**Comment by abd-khrubi** [comment]
> This would be a great addition to https://runelite.net/plugin-hub/show/better-godwars-overlay

I respectfully disagree, while both [better-godwars-overlay](https://runelite.net/plugin-hub/show/better-godwars-overlay) and my plugin are similar I feel that they server different purposes, [better-godwars-overlay](https://runelite.net/plugin-hub/show/better-godwars-overlay) aims to cleanup the original GWD kc interface while preserving its essence, while my plugin removes the original interface and replaces it with minimalistic info boxes to reduce clutter while doing content in GWD.

I think merging the two plugins together would only hide one functionality behind (somewhat convoluted) option menu, and both plugins can coexist at the same time.

**Comment by abd-khrubi** [comment]
But if you still think it's better for them to be the same plugin I can migrate my code to [better-godwars-overlay](https://runelite.net/plugin-hub/show/better-godwars-overlay) although I see that it's currently hosted not by the original author

**Comment by DominickCobb-rs** [comment]
You're both modifying the same thing. It would be helpful to have both options in a single plugin so people don't have to guess which it is they want. I'd wait until official word from a RL maintainer says the same thing, but it's a common sentiment with hub plugins that have similar counterparts.

**Comment by YvesW** [comment]
I'm not sure why it's currently hosting as part of Adam's plugins. I'd personally recommend contributing to ``better-godwars-overlay`` indeed. You could add it as a config option that's disabled by default.
If Adam just took the plugin to fix an API change, he might even transfer the repo to you if you actually want to maintain the plugin, but that's not up to me.

**Comment by abd-khrubi** [comment]
@YvesW Sure I can add it as a config option to `better-godwars-overlay` 
I wouldn't mind maintaining the the plugin too. @Adam- Are you ok with me transferring the plugin to myself?

**Comment by LlemonDuck** [comment]
Yes, we can transfer you the plugin. Adam has it now since it was unmaintained after an update. 

Ideally here you would make your changes to the plugin, and then two PRs here on the plugin hub: one changes the ownership to your own repo but does NOT change the commit, for ease of our review. Then also a second PR changing the commit hash to whatever changes you wanted to make.

**Comment by abd-khrubi** [comment]
@LlemonDuck I accidently closed this PR 😬, I have just opened a PR to take ownership of the plugin and I'll be opening another PR with the changes

**Pull request closed without merging**
