### PR TITLE
Update Global Chat

### PR DESCRIPTION
**Pull request by RusseII**
Fixes the security issues that resulted in plugin getting disabled in https://github.com/runelite/plugin-hub/commit/9f331caab55f672ad96ea8d69e55d33bae08da57
CleanShot 2024-07-31 at 11 59 31@2x

1) > This is exfiltrating all dms to a channel anyone can subscribe

* Moves from using ably's [basic auth](https://ably.com/docs/auth/basic) to using [token auth](https://ably.com/docs/auth/token) with minimal permissions. 
* Revoked previous API key
* [Encrypts](https://ably.com/docs/channels/options/encryption) all messages 

CleanShot 2024-07-31 at 11 42 58@2x

2) > allows spoofing messages with the mod crowns.
* Fixed by only allowing ironman icons with the new and `getValidAccountIcon` and `isInvalidUsername` function

### CODE REVIEW

**Comment by SheeranJL** [comment]
bump

**Comment by LlemonDuck** [comment]
Instead of checking for specific control characters, it's better to just sanitize the entire message using `Text#removeTags. <https://github.com/RusseII/region-chat/compare/403f4d0d17dd537838f3929a37bb095e1e5e3372...RusseII:9cdb1c0f31c57a214209a836cfbb2973254d629d#diff-51d34e1338ae68af40061f38cd1ddea82fbcf922e3c55828aa0e3264d16fd0c2R366-R368>

**Comment by LlemonDuck** [comment]
Marking as draft for now. Please make the requested changes, then mark the plugin as ready for review.

**Comment by RusseII** [comment]
Thanks @LlemonDuck. Added your suggestions

**Pull request merged**
