### PR TITLE
Create twitch-emotes

### PR DESCRIPTION
**Pull request by loldudester**
Adds Twitch Global Emotes to chat, similar to the Emojis plugin.

### CODE REVIEW

**Comment by Nightfirecat** [comment]
You need to fix your runelite-plugin.properties. Specifically, you need to change `com.TwitchEmotes.TwitchEmotesPlugin` to `com.TwitchEmotes.TwitchEmotePlugin` (no `s` after `Emote`

**Comment by loldudester** [comment]
Ah yup, I changed that halfway through and knew I would miss it somewhere.

**Comment by Adam-** [comment]
Someone brought up on Discord - I don't think we have the rights to redistribute the twitch emote icons?

**Comment by loldudester** [comment]
Yeah, turns out it'd need permission. I've shot an email to their brand questions address and am waiting to hear back. This will have to sit in purgatory until then.

**Comment by Nightfirecat** [comment]
Any word on this? I recall you saying in Discord that you're still awaiting a reply. In the meantime, it would likely be better to close this since I doubt we'll hear back from Twitch on this in a timely fashion.

**Comment by loldudester** [comment]
Yeah I think this one's dead in the water, so I'll close it

**Pull request closed without merging**
