### PR TITLE
Update runekit

### PR DESCRIPTION
**Pull request by ImToxicCode**
Updated logging.. Version might have been incorrect? Works fine in debug mode but not in production.

### CODE REVIEW

**Comment by raiyni** [comment]
Those log statements won't be ran for users anyway.

**Comment by ImToxicCode** [comment]
> Those log statements won't be ran for users anyway.

I know, I wanted to see if updating the commit string would update it properly.

**Comment by raiyni** [comment]
This update wouldn't make a difference for that since nothing is being changed.

**Comment by ImToxicCode** [comment]
> This update wouldn't make a difference for that since nothing is being changed.

Never mind, I just tried it again and its working now. That so odd.

Thank you

**Pull request closed without merging**
