### PR TITLE
Update temple-osrs

### PR DESCRIPTION
**Pull request by SMaloney2017**
DT2 Bosses, Error Catching for missing Icons

### CODE REVIEW

**Comment by Adam-** [comment]
You have a gif with a png file extension which breaks our code scanner.  Don't do this.
```
src/main/resources/com/templeosrs/bosses/game_icon_ironehb.png:                      GIF image data, version 89a, 16 x 16
```

**Review by Adam- — CHANGES_REQUESTED** [review]
fails scanner

**Comment by SMaloney2017** [comment]
Fixed that weird GIF, but I'm not seeing any scanner output in the build details so I hope that was the only one...

**Comment by Nightfirecat** [comment]
The scanner output is not public. Also you have other images which have the same problem--namely the below files:

```
$ git ls-files *.png | xargs file | grep -E 'png:\s+GIF'
src/main/resources/com/templeosrs/overall.png:                                       GIF image data, version 89a, 16 x 16
src/main/resources/com/templeosrs/skills/skill_icon_agility.png:                     GIF image data, version 89a, 16 x 16
src/main/resources/com/templeosrs/skills/skill_icon_attack.png:                      GIF image data, version 89a, 16 x 16
src/main/resources/com/templeosrs/skills/skill_icon_construction.png:                GIF image data, version 89a, 16 x 16
src/main/resources/com/templeosrs/skills/skill_icon_cooking.png:                     GIF image data, version 89a, 16 x 16
src/main/resources/com/templeosrs/skills/skill_icon_crafting.png:                    GIF image data, version 89a, 16 x 16
src/main/resources/com/templeosrs/skills/skill_icon_defence.png:                     GIF image data, version 89a, 16 x 16
src/main/resources/com/templeosrs/skills/skill_icon_ehp.png:                         GIF image data, version 89a, 16 x 16
src/main/resources/com/templeosrs/skills/skill_icon_f2pehp.png:                      GIF image data, version 89a, 16 x 16
src/main/resources/com/templeosrs/skills/skill_icon_fantasyehp.png:                  GIF image data, version 89a, 16 x 16
src/main/resources/com/templeosrs/skills/skill_icon_farming.png:                     GIF image data, version 89a, 16 x 16
src/main/resources/com/templeosrs/skills/skill_icon_firemaking.png:                  GIF image data, version 89a, 16 x 16
src/main/resources/com/templeosrs/skills/skill_icon_fishing.png:                     GIF image data, version 89a, 16 x 16
src/main/resources/com/templeosrs/skills/skill_icon_fletching.png:                   GIF image data, version 89a, 16 x 16
src/main/resources/com/templeosrs/skills/skill_icon_herblore.png:                    GIF image data, version 89a, 16 x 16
src/main/resources/com/templeosrs/skills/skill_icon_hitpoints.png:                   GIF image data, version 89a, 16 x 16
src/main/resources/com/templeosrs/skills/skill_icon_hunter.png:                      GIF image data, version 89a, 16 x 16
src/main/resources/com/templeosrs/skills/skill_icon_ironehp.png:                     GIF image data, version 89a, 16 x 16
src/main/resources/com/templeosrs/skills/skill_icon_lvl3ehp.png:                     GIF image data, version 89a, 16 x 16
src/main/resources/com/templeosrs/skills/skill_icon_magic.png:                       GIF image data, version 89a, 16 x 16
src/main/resources/com/templeosrs/skills/skill_icon_mining.png:                      GIF image data, version 89a, 16 x 16
src/main/resources/com/templeosrs/skills/skill_icon_overall.png:                     GIF image data, version 89a, 16 x 16
src/main/resources/com/templeosrs/skills/skill_icon_prayer.png:                      GIF image data, version 89a, 16 x 16
src/main/resources/com/templeosrs/skills/skill_icon_ranged.png:                      GIF image data, version 89a, 18 x 18
src/main/resources/com/templeosrs/skills/skill_icon_runecraft.png:                   GIF image data, version 89a, 16 x 16
src/main/resources/com/templeosrs/skills/skill_icon_slayer.png:                      GIF image data, version 89a, 16 x 16
src/main/resources/com/templeosrs/skills/skill_icon_smithing.png:                    GIF image data, version 89a, 16 x 16
src/main/resources/com/templeosrs/skills/skill_icon_strength.png:                    GIF image data, version 89a, 16 x 16
src/main/resources/com/templeosrs/skills/skill_icon_thieving.png:                    GIF image data, version 89a, 16 x 16
src/main/resources/com/templeosrs/skills/skill_icon_uimehp.png:                      GIF image data, version 89a, 16 x 16
src/main/resources/com/templeosrs/skills/skill_icon_woodcutting.png:                 GIF image data, version 89a, 16 x 16
```

**Comment by SMaloney2017** [comment]
I see, I suppose I've just been saving images from the OSRS HiScores so I had no idea. I appreciate the insight, I'll get these fixed.

**Comment by SMaloney2017** [comment]
Alright, all should have been replaced. Sorry about that scanner trouble, shouldn't be an issue from here on out.

**Pull request merged**
