### PR TITLE
Plugin that replaces Uri dialogue with Dril tweets

### PR DESCRIPTION
**Pull request by Mike-U5**
This plugin does not connect to any kind of API, the tweets are randomly picked from a hardcoded list in DrilQuotes.java.

(NpcDialogueReplacementPlugin was the original name for this plugin before it was repurposed)

### CODE REVIEW

**Comment by geheur** [comment]
There is another uri quotes plugin #5307 . Is yours better than theirs?

**Comment by raiyni** [comment]
I don't think we can accept this plugin as it's pretty vulgar

**Comment by Mike-U5** [comment]
@geheur If sidesteps the issue mentioned by @raiyni then it seems to be better.

**Comment by Mike-U5** [comment]
The other plugin doesn't seem to be in the hub yet but I will test to see if that one covers this use-case first.

**Pull request closed without merging**
