### PR TITLE
Update ba-minigame to v1.3

### PR DESCRIPTION
**Pull request by BegOsrs**
Allow draggable teammates health widget.
Option to hide teammates health widget.

### CODE REVIEW

**Comment by raiyni** [comment]
Can this be made moveable in core runelite?

**Comment by BegOsrs** [comment]
> Can this be made moveable in core runelite?

https://github.com/runelite/runelite/pull/13852

**Comment by raiyni** [comment]
> > Can this be made moveable in core runelite?
> 
> Sent a pull request: [runelite/runelite#13852](https://github.com/runelite/runelite/pull/13852)
> I'll revert changes on this plugin when and if changes on runelite are approved

Moveable overlay merged into master

**Comment by BegOsrs** [comment]
> > > Can this be made moveable in core runelite?
> > 
> > 
> > Sent a pull request: [runelite/runelite#13852](https://github.com/runelite/runelite/pull/13852)
> > I'll revert changes on this plugin when and if changes on runelite are approved
> 
> Moveable overlay merged into master

Ty, updated code to remove movable widgets
But i'd like to keep the option to hide teammates health, and show it while pressing ctrl key

**Comment by raiyni** [comment]
Can you reset the hidden widgets on shutdown then it should be ✔

**Comment by BegOsrs** [comment]
> Can you reset the hidden widgets on shutdown then it should be ✔

Done

**Pull request merged**
