### PR TITLE
add antifire-checker plugin

### PR DESCRIPTION
**Pull request by sariyamelody**
I've written a plugin to warn you when you're almost out of antifire juice. Great for people who walk away from their desk habitually.

### CODE REVIEW

**Comment by sariyamelody** [comment]
image
Here's a screenshot of it in action!

**Comment by sariyamelody** [comment]
bumping the version to address the gradle lint failure

**Comment by cdfisher** [comment]
Can this not already be accomplished with something like Watchdog?

**Comment by sariyamelody** [comment]
I went looking extensively and Watchdog never came up, that might be a route that could address this need.

Investigating Watchdog now, it appears that it does not have any way to grab arbitrary varbits (i.e. Varbits.ANTIFIRE / Varbits.SUPER_ANTIFIRE) or their related status effects, which means that Watchdog is limited to alerting on "has the 'antifire close to expiry' message fired?" or similar -- the point of this is allowing configurable thresholds for users to manage their own AFK desires :)

**Comment by sariyamelody** [comment]
(Another update, to fix the lint again, hopefully!)

**Comment by adamk33n3r** [comment]
Is that an...UNDERLAY? :O but reading this, there's nothing saying I wouldn't add a varbit option ;) I actually have had pouches requested which I think also use varbits etc so it'll probably happen at some point.

**Pull request merged**
