### PR TITLE
Add Giants' Foundry Mould Helper plugin

### PR DESCRIPTION
**Pull request by Lawst96**
A plugin that highlights the name of the best moulds for a given commission at Giants' Foundry.

Would ideally make it actually calculate the best mould based on your level and what moulds you have available. But this is just a simple version that looks for a string match, for now.

### CODE REVIEW

**Review by LlemonDuck — APPROVED** [review]

**Comment by LlemonDuck** [comment]
Leaving this for someone else to merge but you could use `client.getLocalPlayer().getWorldLocation()` here: https://github.com/Lawst96/giants-foundry-mould-helper/blob/23efd5cdb5c56747265712cd73ba9b841611b22e/src/main/java/com/giantsfoundrymouldhelper/GiantsFoundryMouldHelper.java#L63

**Comment by pwatts6060** [comment]
FYI The other Giant Foundry plugin does this as well: https://github.com/runelite/plugin-hub/pull/2800

**Comment by Lawst96** [comment]
> FYI The other Giant Foundry plugin does this as well: #2800

Oh, didn't notice that someone had already made this. 
I'll probably just close this PR as it does essentially the same thing.

**Comment by pwatts6060** [comment]
> > FYI The other Giant Foundry plugin does this as well: #2800
> 
> Oh, didn't notice that someone had already made this. I'll probably just close this PR as it does essentially the same thing.

I think that makes the most sense. There doesn't seem to be anything from here that isn't already done with the other plugin. If you have other ideas though that could be added to the other foundry plugin or improvements for the mould helper it would be nice to add those.

**Pull request closed without merging**
