### PR TITLE
Add Flip Assistant Plugin

### PR DESCRIPTION
**Pull request by AlmostEvil665**
This plugin only logs GE Data to the .runelite folder to be read by an external project I am working on.

### CODE REVIEW

**Comment by raiyni** [comment]
Stop closing and opening prs, just make commits to the same branch

**Comment by AlmostEvil665** [comment]
Thanks for the input. I'll make this changes and let you know once its done. I've got some class work to catch up on then I can implement these changes.

**Comment by AlmostEvil665** [comment]
Went ahead and made the changes requested. The plugin is only intended to be used on a windows computer so I've just prevented it from running on other OS. I've also removed the config file since I don't intend on having any settings. Let me know if that works for you guys or any other changes you'd like to see.

**Comment by LlemonDuck** [comment]
We have the `OSType` utility class to help with this https://github.com/AlmostEvil665/GeOfferExporter/blob/b14e66dd41ecbd82e6ada75734bfeaa068b460b5/src/main/java/com/FlipAssistant/geofferexporter.java#L34

`RuneLite.RUNELITE_DIR` would be more portable https://github.com/AlmostEvil665/GeOfferExporter/blob/b14e66dd41ecbd82e6ada75734bfeaa068b460b5/src/main/java/com/FlipAssistant/geofferexporter.java#L67

If you are planning to only use the plugin for yourself or some friends, you may also find the shadow jar gradle plugin useful to distribute a version of RuneLite with this plugin, without requiring it to be deployed to the plugin hub.

> Add the following line to your plugins block:
> ```groovy
> id "com.github.johnrengelman.shadow" version "6.1.0"
> ```
> 
> Add this block elsewhere in the file, changing the Main-Class to your plugin's test:
> ```groovy
>  shadowJar {
>    from sourceSets.test.output
>    configurations = [project.configurations.testRuntimeClasspath]
>    manifest {
>      attributes "Main-Class": "com.example.ExamplePluginTest"
>    }
>  }
>```
> 
> Then run ./gradlew shadowJar and a runnable jar will appear in build/libs/*-all.jar

**Pull request closed without merging**
