### PR TITLE
Create inventory-free-slots

### PR DESCRIPTION
**Pull request by Scraxer**
Hey there, I couldn't find any great options for displaying an accurate inventory counter on my bags.
I hate having to do the 28 - whatever is in my bags to work out how many slots I have free or doing basic math each time...

I thought other people might find that useful as well.
It's my first time making a RuneLite plugin, it seemed to work without issues when I compiled RuneLite.
image
image

### CODE REVIEW

**Comment by cdfisher** [comment]
It looks like this is something that "Inventory Summary" already does.

**Comment by Scraxer** [comment]
I tried Inventory Summary, but this is all it did for me:
image

It doesn't show me my inventory free slots remaining on the bag icon, it just pops up this secondary window showing my inventory and a togglable count.

I don't think it does the exact same thing my plugin does, particularly with the changing colours relative to spaces free.

**Comment by cdfisher** [comment]
The two are similar enough in functionality that we would prefer that you try and contribute to the existing plugin, in this case probably by doing something like adding an "Inventory overlay" config option or similar, rather than submitting an entirely new plugin that does nearly the exact same thing.

**Comment by Scraxer** [comment]
Completely understand your logic - less plugins with more functionality makes sense.
My plugin here has a very narrow scope and is simplistic, it aims to not replace the inventory or be an "all-in-one" summary, but rather fills the void where an expected function should exist. 

I was quite surprised this feature wasn't already a default plugin within RuneLite core...

I'll be honest, I'm not going to try and rewrite both Enriath's plugin and my own to get this through the door... If Enriath wants to, great. After showing some friends they thought it was very handy so I felt the need to share it :)

**Comment by YvesW** [comment]
Does this plugin do anything significantly different from the already existing inventory count plugin? We'd strongly prefer if you contibute to that plugin instead.

**Comment by Scraxer** [comment]
> Does this plugin do anything significantly different from the already existing inventory count plugin? We'd strongly prefer if you contibute to that plugin instead.

Just checked out Inventory Count (https://github.com/robrichardson13/inventory-count), I hadn't actually seen that plugin until you mentioned it. Looks like it hasn't had any updates or improvements since inception.

Major differences between them would be

**Theirs:**
- Has one option to render the inventory counter as a separate overlay, or on top of the bag.

**Mine:**
- Allows you to adjust the font size.
- Allows you to enable a text border/shadow for better visibility.
- Changes colours relative to your spaces free. (Green = 50% free, Yellow = 30-49% free, Orange = 10-29% free, Red = 0-10% free)

**Plans for mine:**
- Repositionable.
- Adjustable colours/colour blind mode.
- Sounds / alerts.

It's going to be a heck of a lot easier to push these through my own channel, rather than pick up that existing version. I can reach out to Robin Richardson and see how reactive they are?

**Comment by YvesW** [comment]
We do generally prefer that your changes get merged into the already existing plugin (since they do a lot of the same), or that you get added as a contributor to their repo. That way existing users can benefit from your changes, and you already get a sizable active install base!
If the original author does not respond to PRs, issues, discord<sup>#</sup> messages in the RL server, emails (can get the address via their commits most likely), and any other way to contact them with the request for your code to be merged or for you to be added as contributor (unless they decline of course), for approximately one month, we could transfer the repo.

``#`` = (``/whois`` them in our server, they linked their account)

@robrichardson13

**Comment by Scraxer** [comment]
Reached out to rob in a few different ways, let's see how we go. While I'm at it, may as well throw in an extra feature to count unstackable things in your inventory & show on tooltip.

**Comment by Scraxer** [comment]
@robrichardson13 Hey Rob, any feedback?

**Comment by LlemonDuck** [comment]
@Scraxer if you can please make an issue asking for ownership directly on the inventory count repository, we'll transfer the plugin ownership to you if there is no response.

**Comment by Scraxer** [comment]
> @Scraxer if you can please make an issue asking for ownership directly on the inventory count repository, we'll transfer the plugin ownership to you if there is no response.

Hi there, I will give this a shot.
I did see that the plugin is being maintained by another user, but no direct feature improvements.

**Comment by LlemonDuck** [comment]
Ah, I see. Seeing as it's still maintained by _someone_, it would probably be best you just PR your feature to their repo. Hopefully @zenrion would be willing to review it? I assume it'll be a small diff considering the groundwork is all there already. Should just be a single text overlay on the inventory icon and corresponding config options, right?

Looks like there may have been some confusion in robrichardson13/inventory-count#3. You're hoping to add new features to their plugin, not asking whether zenrion would take over yours.

**Comment by zenrion** [comment]
> > @Scraxer if you can please make an issue asking for ownership directly on the inventory count repository, we'll transfer the plugin ownership to you if there is no response.
> 
> Hi there, I will give this a shot. I did see that the plugin is being maintained by another user, but no direct feature improvements.

Hey @Scraxer, I actually just implemented some changes regarding text positioning, color selection and enabling an outline to the inventory overlay.

Perhaps you could pull the latest changes and check them out and extend them?

**Comment by Scraxer** [comment]
> > > @Scraxer if you can please make an issue asking for ownership directly on the inventory count repository, we'll transfer the plugin ownership to you if there is no response.
> > 
> > 
> > Hi there, I will give this a shot. I did see that the plugin is being maintained by another user, but no direct feature improvements.
> 
> Hey @Scraxer, I actually just implemented a bugfix and some [changes regarding text positioning, color selection and enabling an outline](https://github.com/robrichardson13/inventory-count/pull/7) to the inventory overlay pretty recently.
> 
> Perhaps you could pull the latest changes and add any extra feature enhancements to it?

Hey @zenrion I saw that, good stuff. My colour selection function is one that changes colour based on the number of free remaining slots, rather than being a static colour that somebody can choose. I'll see how far I get using that plugin, it looks like there are some reasonable differences in logic and function design.

**Comment by Scraxer** [comment]
Hi team, I contributed to the Inventory Count plugin:
https://github.com/robrichardson13/inventory-count/pull/9

My features have been accepted and you should find a PR updating the plugin on the hub at some stage over the next few days.

As far as my plugin "inventory free slots" I don't think we need it anymore, I'll close the request.

**Pull request closed without merging**
