### PR TITLE
Create guilt-tripper

### PR DESCRIPTION
**Pull request by Kimpulla**
Guilt Tripper is a Runelite plugin designed for Old School Runescape, adding a unique twist to the gaming experience. This plugin periodically sends messages to players, humorously "accusing" them of playing too much and suggesting they take a break. And much more!

1. When the player starts the game, the plugin sends a welcome message in the chat.

2. Every 30 minutes, the plugin humorously reprimands the player for playing too much.

3. The plugin features 5 different sound effects, which can be turned off if desired. There is also a volume control for these sounds.

4. When the player dies, the plugin plays a custom sound effect.

**Epic feature:**

The plugin includes "pet" drop rates from bosses, such as the "Pet Kraken" which can be obtained with a 1/3000 chance upon defeating the Kraken boss. This meme feature displays the message "You have a funny feeling like you're being followed" in the chat, similar to what would happen if you were actually about to receive a pet. However, about 5 seconds later, a new message appears in the chat saying "Turns out it was just a lost kitten. -Guilt Tripper"

### CODE REVIEW

**Comment by raiyni** [comment]
Please don't close and reopen prs. You can push updated commit hashes to your current branch and the runner will pickup the changes.

**Comment by Kimpulla** [comment]
> Please don't close and reopen prs. You can push updated commit hashes to your current branch and the runner will pickup the changes.

Yeah, I realized it a after, mb.

**Comment by Kimpulla** [comment]
> Please use a unique ConfigGroup, not "example".
> 
> Please change your `Installation` instructions. How did you come up with these? It almost sounds like some cheat client. `Download the Guilt Tripper Plugin from the Runelite GitHub page.` is incorrect, I very much doubt it's called `Plugins` and not `Plugin Hub`, there is very likely no `Browse plugins` button, there should not be a downloaded folder.
> 
> Could you make it clear in the chat messages (specifically of the "epic feature") that it's the guilt tripper plugin? I foresee this causing some support traffic, either because people don't know what plugin causes the message or because they're not sure if Jagex is fucking with them or some plugin they installed.
> 
> I also doubt that we can distribute these sounds, but I'm not a copyright expert. `You cannot sell or distribute Content (either in digital or physical form) on a Standalone basis. Standalone means where no creative effort has been applied to the Content and it remains in substantially the same form as it exists on our website.`


As stated in the README file "(Installation not available at the moment)", installation is not yet possible. The installation instructions are thus incomplete, as the plugin has not yet been approved. Therefore, the installation instructions are not precise, but let's correct them as well.

If I mention in the chat that the "epic feature" is from the Guilt-Tripper plugin, it might spoil the whole idea. On the other hand, I could present it in the chat as: "Turns out it was just a lost kitten. - Guilt Tripper".

As for the sound effects, they are all royalty-free sound effects that have not been modified. However, I can try some other solutions regarding these.

**Comment by cdfisher** [comment]
> If I mention in the chat that the "epic feature" is from the Guilt-Tripper plugin, it might spoil the whole idea. On the other hand, I could present it in the chat as: "Turns out it was just a lost kitten. - Guilt Tripper".

Not marking the fake pet drop messages themselves as being from the plugin is almost certainly going to cause confusion and likely support traffic that we'd have to deal with.

Plugins having secret "surprise" features that users aren't aware of when installing is something I would broadly categorize as being something that's undesired, and that sort of thing again generally ends up showing up in the support channel a fair bit.

**Comment by DapperMickie** [comment]
> > Please use a unique ConfigGroup, not "example".
> > Please change your `Installation` instructions. How did you come up with these? It almost sounds like some cheat client. `Download the Guilt Tripper Plugin from the Runelite GitHub page.` is incorrect, I very much doubt it's called `Plugins` and not `Plugin Hub`, there is very likely no `Browse plugins` button, there should not be a downloaded folder.
> > Could you make it clear in the chat messages (specifically of the "epic feature") that it's the guilt tripper plugin? I foresee this causing some support traffic, either because people don't know what plugin causes the message or because they're not sure if Jagex is fucking with them or some plugin they installed.
> > I also doubt that we can distribute these sounds, but I'm not a copyright expert. `You cannot sell or distribute Content (either in digital or physical form) on a Standalone basis. Standalone means where no creative effort has been applied to the Content and it remains in substantially the same form as it exists on our website.`
> 
> As stated in the README file "(Installation not available at the moment)", installation is not yet possible. The installation instructions are thus incomplete, as the plugin has not yet been approved. Therefore, the installation instructions are not precise, but let's correct them as well.
> 
> If I mention in the chat that the "epic feature" is from the Guilt-Tripper plugin, it might spoil the whole idea. On the other hand, I could present it in the chat as: "Turns out it was just a lost kitten. - Guilt Tripper".
> 
> As for the sound effects, they are all royalty-free sound effects that have not been modified. However, I can try some other solutions regarding these.

Either way, you'd want the changes to your README as part of the PR before it's actually merged, because changing the README would require another PR to update the text shown on the RL website. The website uses the README file state of the commit in your PR as opposed to just grabbing the latest version from your plugin's repo.

**Comment by cdfisher** [comment]
> > > Please use a unique ConfigGroup, not "example".
> > > Please change your `Installation` instructions. How did you come up with these? It almost sounds like some cheat client. `Download the Guilt Tripper Plugin from the Runelite GitHub page.` is incorrect, I very much doubt it's called `Plugins` and not `Plugin Hub`, there is very likely no `Browse plugins` button, there should not be a downloaded folder.
> > > Could you make it clear in the chat messages (specifically of the "epic feature") that it's the guilt tripper plugin? I foresee this causing some support traffic, either because people don't know what plugin causes the message or because they're not sure if Jagex is fucking with them or some plugin they installed.
> > > I also doubt that we can distribute these sounds, but I'm not a copyright expert. `You cannot sell or distribute Content (either in digital or physical form) on a Standalone basis. Standalone means where no creative effort has been applied to the Content and it remains in substantially the same form as it exists on our website.`
> > 
> > 
> > As stated in the README file "(Installation not available at the moment)", installation is not yet possible. The installation instructions are thus incomplete, as the plugin has not yet been approved. Therefore, the installation instructions are not precise, but let's correct them as well.
> > If I mention in the chat that the "epic feature" is from the Guilt-Tripper plugin, it might spoil the whole idea. On the other hand, I could present it in the chat as: "Turns out it was just a lost kitten. - Guilt Tripper".
> > As for the sound effects, they are all royalty-free sound effects that have not been modified. However, I can try some other solutions regarding these.
> 
> Either way, you'd want the changes to your README as part of the PR before it's actually merged, because changing the README would require another PR to update the text shown on the RL website. The website uses the README file state of the commit in your PR as opposed to just grabbing the latest version from your plugin's repo.

They already have changed their README but need to update the commit hash in the plugin-hub repo. THe latest commit in their plugin's repo is 68f929a0c2d49dd11efab08e267d4da7cec35bce

**Pull request merged**
