### PR TITLE
Inventory-Setups-1.6

### PR DESCRIPTION
**Pull request by dillydill123**
Inventory Setups 1.6:

Adds a way to view setups in game using the "Show worn items" menu.

Adds Spellbook to the setup so you can make sure you are on the correct setup

Adds a help button that links to the read me (https://github.com/dillydill123/inventory-setups#inventory-setups) which now contains pictures and gifs to help new users. This button can be hidden in the config (learning from jagex's mistakes).

### CODE REVIEW

**Comment by Nightfirecat** [comment]
FYI `assert` will cause client hanging if it evaluates to `false`.

**Comment by dillydill123** [comment]
Are asserts enabled in releases? I thought they are only active during debug. This is how I’ve always used them (in C++ for example).

I think the asserts are fine and won’t get triggered. But if you have a strong opinion on removing them I don’t have a problem either.

**Comment by abextm** [comment]
asserts are only enabled if you run with `-ea`

**Comment by Nightfirecat** [comment]
I believe they're only enabled for players running dev builds, but that will likely affect some nonzero number of players. See #292 for reference

**Comment by dillydill123** [comment]
It sounds like it won’t affect many players if one does trigger and I like having them in there for debug purposes. If you still think they should be removed it’s not a problem though.

**Comment by Nightfirecat** [comment]
I'll merge it as-is, but I worry with things like these that it will cause more traffic to `#support` if any of the assertions are buggy or overly strict.

**Pull request merged**
