### PR TITLE
update raid-data-tracker to include toa and tob hm uniques

### PR DESCRIPTION
**Pull request by Leigham**
lots of changes with this, the way the files are written to, and folders changed if the user changes thier name.

### CODE REVIEW

**Comment by Leigham** [comment]
its ready to go, ,just testing for any small changes before its finished review.

**Comment by LlemonDuck** [comment]
Please remove `CoX Insider` from the authors tag in this PR, the tag is only for GitHub usernames. You can place display names in runelite-plugin.properties but I see you already have.

Actual diff link, for my own sake as I review it: https://github.com/CasvM/runelite-external-plugins/compare/28c1a040e04928ac0e7a82d352894a2a611793c6...raid-tracker

**Comment by Leigham** [comment]
@LlemonDuck  Done, also took this time to add in gp/hr tracking.

**Comment by LlemonDuck** [comment]
authors should contain *your* GitHub name, as you're the non-owner author. We can already infer that CasvM has access, he owns the repo. Use `authors=Leigham`

**Comment by Leigham** [comment]
Alrighty, ill sort that while I get this arithmatic issue done.

**Comment by Leigham** [comment]
Done , holy shit, vscode would run the gradle stuff before I had a chance to commit.

**Comment by LlemonDuck** [comment]
There's a lot of things that need changes here but mostly this is just extremely difficult to read.

Migration failed on my user profile.

* Move this out of onVarbitChanged https://github.com/CasvM/runelite-external-plugins/compare/28c1a040e04928ac0e7a82d352894a2a611793c6...raid-tracker#diff-321833cb2db743f83003c80d235683d6cdf0c364aac38158392dfa0e75352a3cR161
* Use Files#move instead of File#renameTo in IOUtils https://github.com/CasvM/runelite-external-plugins/compare/28c1a040e04928ac0e7a82d352894a2a611793c6...raid-tracker#diff-2d3c61eb8670f2a62dea0632fd282afe35fbc75d6a8b42badd3bdb9f478442b5R54 and https://github.com/CasvM/runelite-external-plugins/compare/28c1a040e04928ac0e7a82d352894a2a611793c6...raid-tracker#diff-2d3c61eb8670f2a62dea0632fd282afe35fbc75d6a8b42badd3bdb9f478442b5R92
* Use Paths#get's vararg syntax instead of manually formatting strings e.g. `Paths.get(RUNELITE_DIR, PLUGIN_DIR, somePath)`
* The existing plugin data folder is `~/.runelite/raid-data tracker`, which matches FileReadWriter#getPath, but you use `~/.runelite/raid-data-tracker` everywhere else. Which is it?
* You are not verifying that the paths returned by IOUtils#generatePath are valid, which caused a FileNotFoundException on my machine from the parent dir not existing https://github.com/CasvM/runelite-external-plugins/compare/28c1a040e04928ac0e7a82d352894a2a611793c6...raid-tracker#diff-d2d5be49a1687efc4de05de33bd7e98ee2252a7fc0ed1c42a4a3b6f45a4b7334R150
* Also you are swallowing the exception in updateRTList so if anything goes wrong writing out user data it is just simply lost, whether the error would be transient or not https://github.com/CasvM/runelite-external-plugins/compare/28c1a040e04928ac0e7a82d352894a2a611793c6...raid-tracker#diff-d2d5be49a1687efc4de05de33bd7e98ee2252a7fc0ed1c42a4a3b6f45a4b7334R159
* There's a lot of spelling errors all over the place but the ones in the RaidUniques enum matter since you use them in your serialization, effectively locking you into these spellings forever else requiring yet another data migration. The proper spellings are in the ItemIDs within the same line, and you can confirm correct capitalization/apostrophe placement on the wiki https://github.com/CasvM/runelite-external-plugins/compare/28c1a040e04928ac0e7a82d352894a2a611793c6...raid-tracker#diff-a9c7e00a2beda34ff0a5c4c992e4e8e58ab7de547e18acaebaf33bf603983fd3R34
  * Also it's `Amascut` not `Amascot`
* You should prune unused methods/fields/constants, empty blocks, etc to make this easier to read, and if you're going to add a checkstyle config it would be nice to actually use it:

**Comment by Nightfirecat** [comment]
Hi @Leigham, has any progress been made in the past month toward fixing the issues Llemonduck highlighted?

**Comment by Leigham** [comment]
I have made a start, but everything got busy leading upto christmas. Will be starting to work on it again soon.

**Comment by raiyni** [comment]
Considering it's been several months, I'm going to close this. You can reopen it when you get back to it.

**Pull request closed without merging**
