### PR TITLE
Create nex-timers

### PR DESCRIPTION
**Pull request by imKwok**
This plugin displays splits of the Nex boss fight, between Nex herself and the minions, and can print results to game chat as well.

### CODE REVIEW

**Comment by cdfisher** [comment]
Does this do anything either of the two existing Nex splits hub plugins don't already do?

**Comment by imKwok** [comment]
> Does this do anything either of the two existing Nex splits hub plugins don't already do?

Yes, I believe one of the splits plugins is for loot splits, and the other one doesn't function as a split timer with an overlay.

**Comment by cdfisher** [comment]
> > Does this do anything either of the two existing Nex splits hub plugins don't already do?
> 
> Yes, I believe one of the splits plugins is for loot splits, and the other one doesn't function as a split timer with an overlay.

In that case we would recommend that you try to collaborate with the author of the existing Nex Splits plugin to add additional functionality to that rather than adding a whole new plugin to the hub.

**Comment by imKwok** [comment]
> > > Does this do anything either of the two existing Nex splits hub plugins don't already do?
> > 
> > 
> > Yes, I believe one of the splits plugins is for loot splits, and the other one doesn't function as a split timer with an overlay.
> 
> In that case we would recommend that you try to collaborate with the author of the existing Nex Splits plugin to add additional functionality to that rather than adding a whole new plugin to the hub.

I see. I will try to contact the author.

**Pull request closed without merging**
