### PR TITLE
Switching maintainer in equipment inspector plugin

### PR DESCRIPTION
**Pull request by Waistcoat**

### CODE REVIEW

**Comment by LlemonDuck** [comment]
@botanicvelious do you give permission to @Waistcoat to take over this plugin?

**Comment by botanicvelious** [comment]
Not sure who this is, checked his repo and its just a clone of mine, @Waistcoat if you are going to add things I don't mind transferring it, but at this point it looks like nothing has been changed.

**Comment by Adam-** [comment]
FYI the best way to have multiple contributors on one plugin is to just add the 2nd person as a collaborator to the plugin instead of transferring ownership of the plugin around.

**Comment by botanicvelious** [comment]
I added him as a collaborator you can close this

**Pull request closed without merging**
