### PR TITLE
Update action-progress

### PR DESCRIPTION
**Pull request by guillaume009**

### CODE REVIEW

**Comment by guillaume009** [comment]
Plugin author is unresponsive, but I would still like to merge my change that he approved

**Comment by Felanbird** [comment]
This plugin doesn't build against the past 2 runelite versions, so bumping it to the version with your PR from September does not do anything.

**Comment by guillaume009** [comment]
That's correct indeed. I fixed that on a fork I made for that project. Not sure I can just change the repository to be mine instead but it's the best solution I could come up with

**Comment by Felanbird** [comment]
It's preferred for the author to add you as a collaborator of the repo, but if you nor the runelite devs are able to receive a response from them, then transfer of the project is the next approach.

**Comment by guillaume009** [comment]
Only way I know how to reach him is here. I can tag him an wait a little bit and otherwise we merge this? 

@CalebWhiting

**Comment by Felanbird** [comment]
> Only way I know how to reach him is here. I can tag him an wait a little bit and otherwise we merge this?

I've given him a poke in the runelite discord as well, but yes waiting is the current step.

**Comment by guillaume009** [comment]
Can we update this?

**Comment by Felanbird** [comment]
> Can we update this?

One of the members poked him again in the discord last Wednesday, and you _were_ next in the notifications list, but when you bump a PR it falls to the bottom of the Github notifications, and these PRs are often reviewed in that order.

**Comment by Nightfirecat** [comment]
I've written Caleb an email asking him to review this pull request and give his feedback. Check back with me in a few days if you don't hear anything and I'll go forward with reviewing the changes here.

**Pull request merged**
