### PR TITLE
Create limpwurt-login

### PR DESCRIPTION
**Pull request by Gavin-TC**
Simple plugin that plays a sound clip from YouTuber Limpwurt when the player logs in. Basically a modified "C Engineer: Completed" plugin which only plays a single sound.

### CODE REVIEW

**Comment by Nightfirecat** [comment]
I've not reviewed the code whatsoever, but do you have permission from limpwurt to use his voice clip in this way?

**Comment by Gavin-TC** [comment]
> I've not reviewed the code whatsoever, but do you have permission from limpwurt to use his voice clip in this way?

For some reason I never thought about this, but I did go ahead and DM him on Discord and he said go for it.

**Comment by Gavin-TC** [comment]
> Can you include said conversation? We can't take your word that you spoke to someone

Gotcha. Here's a screenshot:image

**Comment by Nightfirecat** [comment]
You should not [use the C Engineer plugin's icon](https://github.com/Gavin-TC/limpwurt-login/blob/3906a2c888e94479c359bf8b41f5623c46be1b54/icon.png) for this plugin.
Code LGTM otherwise

**Comment by Gavin-TC** [comment]
> You should not [use the C Engineer plugin's icon](https://github.com/Gavin-TC/limpwurt-login/blob/3906a2c888e94479c359bf8b41f5623c46be1b54/icon.png) for this plugin. Code LGTM otherwise

Good point, thanks for mentioning that!

**Pull request merged**
