### PR TITLE
Add ImaDrum Money plugin

### PR DESCRIPTION
**Pull request by EwwItsMike**
A simple plugin that plays a random sound clip of content creator ImaDrum when you receive a good drop.

### CODE REVIEW

**Comment by Nightfirecat** [comment]
Do you have permission from ImaDrum to use their voice clips in this plugin?

**Comment by EwwItsMike** [comment]
> Do you have permission from ImaDrum to use their voice clips in this plugin?

I do! He recorded them specifically for this plugin and sent them to me. Need me to provide any proof of that?

Also, seems like build failed, did I mess up something simple?

**Comment by Nightfirecat** [comment]
> Need me to provide any proof of that?

Yes please.

Your build is failing because your plugin properties file has `plugins=com.imadrummoney.MoneySoundPlugin`, but your plugin is actually located at `com.imadrummoney.ImadrumMoneyPlugin`

**Comment by EwwItsMike** [comment]
Updated plugin properties file in the plugin repo, and updated commit hash in this fork.
Hopefully enough proof of Drum providing the sound clips himself for this plugin: https://gyazo.com/4a49736d51708eb3d282a3a176ae2d41
If this is not sufficient, feel free to @ me or DM me on discord (Ew Its Mike#1946) so I can get it sorted out

**Comment by Nightfirecat** [comment]
The "bruh.wav" sound is something we can't distribute without permission from the maker of the sound. (it looks like your plugin doesn't actually use it at all? should be able to remove it without changing the behavior at all) The rest looks fine to me.

**Pull request closed without merging**
