### PR TITLE
Refreshed the Organized Crime Plugin

### PR DESCRIPTION
**Pull request by Mordo95**
* Original creator has been added as collaborator to the repository.

Plugin creator didn't respond for over a year to pull requests and the plugin contains a nasty bug that stops the plugin from working altogether. It's been fixed in this repo, and I've fixed some other problems with the plugin documented in README.md. Planning to add more features soon.

### CODE REVIEW

**Comment by Nightfirecat** [comment]
@DylanLange, are you fine with Mordo95 taking over development of this plugin?

**Comment by Mordo95** [comment]
Welp this is how my attempts to get in contact with this guy went.

**Comment by Adam-** [comment]
Moving the plugin to you is probably fine. Though I would prefer if you simply cloned the existing plugin instead of deleted all of the history since it is much easier to review and maintain in general.

**Comment by Mordo95** [comment]
> Moving the plugin to you is probably fine. Though I would prefer if you simply cloned the existing plugin instead of deleted all of the history since it is much easier to review and maintain in general.

All done!

**Pull request merged**
