### PR TITLE
Create tedious-collection-log

### PR DESCRIPTION
**Pull request by evaan**

### CODE REVIEW

**Comment by Nightfirecat** [comment]
You should probably not use the C Engineer logo as your plugin's icon. Also, do you have permission from Tedious to use his voice clip in this plugin?

**Comment by evaan** [comment]
Fixed, and yes I did get permission from him to make this plugin

**Comment by Nightfirecat** [comment]
...could we see evidence of said permission?

**Comment by evaan** [comment]
image
image

**Pull request merged**
