### PR TITLE
Adding plug-in OSRSKillboard

### PR DESCRIPTION
**Pull request by Osrskillboard**
Plugin to log PvP kills to an online killboard.

### CODE REVIEW

**Comment by melkypie** [comment]
This needs a warning added as it's sending data to `https://api.osrskillboard.com/`. You can use [this](https://github.com/runelite/plugin-hub/blob/master/plugins/rune-cafe-cashflow#L3) as an example

**Comment by Osrskillboard** [comment]
Updating license to BSD 2-Clause "Simplified" Licens.

**Comment by abextm** [comment]
This won't work for people not logged into a runelite account, which is probably not what you want.

**Comment by Osrskillboard** [comment]
Hey @abextm, - could you expand on this? 

The only thing that doesn't seem to work in test is getting the prices of the loot. However, the same happens with the LootTracker add-in and that works in the live client when I'm not logged in.

**Comment by abextm** [comment]
[This code](https://github.com/Osrskillboard/OSRSKillboard-plugin/blob/b2af3851e1725709f4bfc3b3986e653506f89afa/src/main/java/com/osrskillboard/OsrsKillboardPlugin.java#L101-L109) runs when you login/logout of your RuneLite account, so your client will be nulled out if you aren't logged into RuneLite. Since you client has no dependence on the rl account logged into, this seems pointless.

**Comment by Osrskillboard** [comment]
@abextm thanks for the info! Cleared that up. I still and getting to know the codebases and... Java.

**Comment by abextm** [comment]
You still also have [this](https://github.com/Osrskillboard/OSRSKillboard-plugin/commit/578b0590eebd93a9e54f8eb21f4fd282ea15b524#diff-8919b879a0fa56bcaed9bd474f70c05b5be02c15b86279a298000b3fa69dfb3fR118-R131) and a no-op invokeLater callback

**Comment by Osrskillboard** [comment]
Thanks for the reviews and the pointers. I appreciate your patience.

Also cleared up the unused ClientThread and SessionManager.

**Pull request merged**
