### PR TITLE
Create ToA Potion Deposit

### PR DESCRIPTION
**Pull request by ealahd**
Prevents players from using items on other players in ToA nexus room since clicking potions on other players often causes annoyance.

### CODE REVIEW

**Comment by geheur** [comment]
Does this actually work?
the menu is rebuilt 30 times per game tick. this sounds like it has a 1/30 chance of working.

**Comment by ealahd** [comment]
Not really too familiar with the API and just salvaged the code from an already approved plugin. Worked in testing but the testing included going into the nexus room with alt and main a few times. I can test further to see if you have a point.

**Comment by MESLewis** [comment]
There is already a [comprehensive toa plugin](https://runelite.net/plugin-hub/show/tombs-of-amascut) that this feature could be added to. I suggest contacting @LlemonDuck to get this feature added to the existing plugin.

**Comment by LlemonDuck** [comment]
I would gladly welcome this as a feature in the Tombs of Amascut plugin, and may add it regardless. Would you be interested in PRing it instead of creating a whole new plugin for users to find and install?

**Comment by ealahd** [comment]
Yeah absolutely would be better not to have it as a separate plugin. I can PR or you can implement it yourself whichever you prefer. I don't really know what I am doing so it might be better you just add it yourself.

**Comment by LlemonDuck** [comment]
Thanks, will do. I'll ping you in the corresponding ToA plugin PR soon as an FYI.

**Pull request closed without merging**
