### PR TITLE
Transfer ownership of UniversalDiscordNotifier and latest changes

### PR DESCRIPTION
**Pull request by TomBolks**
Since the last PR from MidgetJake to update the plugin failed and he doesn't seem to be currently active, I created this PR. 
This PR contains the same bugfixes and changes his PR originally was supposed to add.

### CODE REVIEW

**Comment by Felanbird** [comment]
That's a very funny PR name for changes that make you the new owner of this plugin 🤔 

I'd assume the maintainers are going to ask you if you have permission from MidgetJake to take over his plugin

**Comment by TomBolks** [comment]
As far as I know he was the only maintainer (beside myself for some stuff) and doesn't seem to be responding on my current PR's and he didn't to his previous PR to update. I don't mind reverting it to his repo and using the last commit from that. 

I don't know the procedure for plugins when the previous author becomes inactive.

**Comment by Felanbird** [comment]
> As far as I know he was the only maintainer (beside myself for some stuff) and doesn't seem to be responding on my current PR's and he didn't to his previous PR to update. I don't mind reverting it to his repo and using the last commit from that.
> 
> I don't know the procedure for plugins when the previous author becomes inactive.

You can either update this PR title to something along the lines of `Transfer ownership of UniversalDiscordNotifier` and update the body to explain the situation, and let the maintainers decide.

Or,

You could take a look at https://github.com/pajlads/DinkPlugin as we were in the same boat as you. 
Due to the issues UniversalDiscordNotifier had that weren't getting fixed, we also forked the repo and have been working extremely hard to actually truly make a centralized plugin, and one that will finally not be abandoned. 🙂

**Comment by TomBolks** [comment]
Thanks, changed the title for now. Will look at your plugin this weekend, if I can use that.

**Comment by Nightfirecat** [comment]
I'm converting this to a draft PR for the time being. In the event that the Dink plugin covers your use case, feel free to close this PR. If there is some need to transfer ownership, please take some time to reach out to the original plugin author--via GitHub, Discord, email, or other means, not just taking for granted that it is abandoned, and we can go from there.

**Comment by TomBolks** [comment]
The changes similiar to mine in this PR, seems to be added just 15 minutes ago to Dink. 
So I will use that plugin instead and close this PR.

**Pull request closed without merging**
