### PR TITLE
Applying a plugin

### PR DESCRIPTION
**Pull request by sanderaigar**
A notification plugin with TTS. 
Currently only available for HP detection, will add more in the future.

### CODE REVIEW

**Comment by cdfisher** [comment]
I believe this is already something that Watchdog does.

**Comment by sanderaigar** [comment]
> I believe this is already something that Watchdog does.

Oh. I was not aware. I’ll give it a look.

**Comment by sanderaigar** [comment]
> I believe this is already something that Watchdog does.

It's close, but not what I intended. At least I could not figure out how to setup it to do what I want it to do :)

**Comment by YvesW** [comment]
What do you want to do?
How does your plugin significantly differ from Watchdog?

**Comment by LlemonDuck** [comment]
Closing as stale. Reopen if you are still interested in submitting this plugin, although we'd prefer not to duplicate Watchdog here.

**Pull request closed without merging**
