### PR TITLE
Add autocast-utilities

### PR DESCRIPTION
**Pull request by jcarbelbide**
Add Autocast Utilities external plugin. 

This plugin displays an overlay when a magic weapon capable of autocasting is equipped. The overlay shows the name and icon of the current spell. If the player's magic level falls below the level required for the spell, the overlay has the option to flash and send a game notification. 

[Link to plugin](https://github.com/jcarbelbide/autocast-utilities/tree/rename-package-statements).

Thank you for your time!

### CODE REVIEW

**Comment by jcarbelbide** [comment]
Related to issue #14503

**Comment by jcarbelbide** [comment]
Hi, I think I fixed the build issue (had the wrong path for the plugin in the .properties file). Please let me know if there's any other help needed on my side.

**Comment by adamk33n3r** [comment]
Does this work for when you run out of runes and try to attack? This happens to me all the time 😅 I accidentally attack something without runes in my inventory and it deselects my autocast without me realizing. I grab runes at some later point to do some combat and I just start whackin' 'em 😆

**Comment by jcarbelbide** [comment]
> Does this work for when you run out of runes and try to attack? This happens to me all the time 😅 I accidentally attack something without runes in my inventory and it deselects my autocast without me realizing. I grab runes at some later point to do some combat and I just start whackin' 'em 😆

Hey Adam, I didn't think about that. It currently does not notify when that happens, but I think that can be added. I'm working on another plugin right now that I want to release asap, but after I'm done with that, I'll work on adding that feature in. I'll create an issue on the repo for this and tag you. Thanks for the suggestion!

**Comment by abextm** [comment]
your package statements are wrong; they should just read `com.autocastutilities`, not that.
otherwise lgtm

**Comment by jcarbelbide** [comment]
Thanks, abex. I have updated the path of the plugin.

**Comment by raiyni** [comment]
It looks like you renamed your repository

**Comment by jcarbelbide** [comment]
You're right, thank you, raiyni! I seem to have missed that. I've updated the repository name.

**Pull request merged**
