### PR TITLE
Adding zeah rc helper plugin

### PR DESCRIPTION
**Pull request by fSunday**
Highlights Zeah Runecrafting Altars(Blood/Soul)

### CODE REVIEW

**Comment by Bram91** [comment]
Does this plugin do anything that <https://runelite.net/plugin-hub/show/zom-dense-essence> doesn't? You could make a PR to their repo to prevent clutter on the hub. Though it seems that `zom-dense-essence` covers all the functionality already.

**Comment by fSunday** [comment]
That plugin highlights the runestones when you can mine them - this one highlights the altars when you have dark essence fragments/blocks in your inventory. I guess I can make a PR to that one instead?

**Comment by Bram91** [comment]
That would be preferred yes, it would make sense for a feature like this to be included in there.

**Comment by fSunday** [comment]
Sounds good - thanks.

**Pull request closed without merging**
