### PR TITLE
Create boss_voicer

### PR DESCRIPTION
**Pull request by GaelL42**
Sol Heredit (& Minimus) Voice Acting!

### CODE REVIEW

**Review by GaelL42 — COMMENTED** [review]
Dash instead of underscore!

**Review by GaelL42 — COMMENTED** [review]
Now it should respect the 10MB limit!

**Comment by GaelL42** [comment]
Don't hesitate to contact me for any questions about the plugin! I am most reachable on Discord (gael.l)!
I've just now joined the Runelite Discord if there's anything I can help with.
To address the elephant in the room : I know there is a risk you guys refuse the plugin, due to the following ToS clause : 
"Adds additional visual or audio indicators of a boss mechanic except in cases where this is a manually triggered external helper."
The plugin this is based on, Nex Nostalgia, functions much the same way (reading overhead text lines from a boss and playing an audio clip), but it was probably accepted due to, well, nostalgia!
Here's an example video of how my plugin works in practice, alongside with the existing SoundSwapper plugin for a truly immersive experience : 
https://www.youtube.com/watch?v=L3RH9J1Av_0&ab_channel=GaelL 
Hopefully it will be fine, but I'm ready to accept that it's not!
Thanks, 
Gael L

**Comment by GaelL42** [comment]
Important note : I am expanding Sol Voicer to become Boss Voicer (to also encompass General Graardor, K'ril Tsutsaroth, Vet'ion/Calvar'ion, and others). If you accept the pull request now, I'll do another one when everything else is ready, but it's ok if you don't! The big concern will be to fit everything within 10 megabytes for sure.

**Comment by GaelL42** [comment]
The plugin now encompasses the 4 GWD bosses, Barrows, Vet'ion/Calvar'ion & Verzik Vitur on top of Sol Heredit!
Here are video examples of each boss voicing...
General Graardor : https://www.youtube.com/watch?v=ep_LR_96BHM&ab_channel=GaelL
Kree'arra : https://www.youtube.com/watch?v=-oteT7t8AY0&ab_channel=GaelL
K'ril Tsutsaroth : https://www.youtube.com/watch?v=K_A-AMWel4I&ab_channel=GaelL
Commander Zilyana : https://www.youtube.com/watch?v=0OBgH4MzCkU&ab_channel=GaelL
Vet'ion/Calvar'ion : https://www.youtube.com/watch?v=oL7afGMLpWs&ab_channel=GaelL
Barrows Brothers : https://www.youtube.com/watch?v=pRbsRT1UNCE&ab_channel=GaelL
Verzik Vitur : https://www.youtube.com/watch?v=8ciVUzDA0XU&ab_channel=GaelL  
Sol Heredit (failure) : https://www.youtube.com/watch?v=7mQYyO949lo&ab_channel=GaelL
Sol Heredit (success) : https://www.youtube.com/watch?v=9vjBZYxikwU&ab_channel=GaelL
Sorry for the rather bad sound quality in some of them, I had to reduce the hertz from 16000 to 11025 to make it all fit within 10 megabytes (and baaarely, with 9.91mb to its name)!
(I also might try to find an actual woman to re-voice Zilyana since my voicing is rather silly.)

I understand that the plugin still might get refused due to concerns about ToS, but, I've asked Ash what he thinks : 
https://x.com/GaelTakesTheL/status/1809805347395158178
We'll see what he has to say, if it can help in any way! Cheers.

**Comment by Nightfirecat** [comment]
This LGTM. Do you want to rename your repository to match the new (that is, no-longer exclusive to Sol Heredit) behavior before it's added?

**Comment by GaelL42** [comment]
> This LGTM. Do you want to rename your repository to match the new (that is, no-longer exclusive to Sol Heredit) behavior before it's added?

Done!

**Comment by Nightfirecat** [comment]
I'd also recommend updating the repository link in this PR, as github does not indefinitely support repository redirects.

**Comment by GaelL42** [comment]
> I'd also recommend updating the repository link in this PR, as github does not indefinitely support repository redirects.

That should do it!

**Pull request merged**
