### PR TITLE
Create camera keyframe plugin

### PR DESCRIPTION
**Pull request by mlgudi**
Adds a camera keyframing plugin. Users can create sequences of camera positions using the side-panel, and then play them back with customisable durations/easing between each point.

### CODE REVIEW

**Comment by adamk33n3r** [comment]
Surprised this hasn't existed yet!

**Comment by cdfisher** [comment]
This may be better as an enhancement to the existing hub plugin "Camera Points". Have you tried reaching out to the author of that about possibly contributions to that plugin?

**Comment by mlgudi** [comment]
> Surprised this hasn't existed yet!

The recent API addition of setting of camera targets made it possible! A beautiful addition to the API which I am sure will have many benefits.

> This may be better as an enhancement to the existing hub plugin "Camera Points". Have you tried reaching out to the author of that about possibly contributions to that plugin?

I was not aware this plugin existed. I would note the new camera target APIs are only available in detached/oculus mode, though I am happy to rewrite it as an extension of Camera Points if it is deemed more appropriate.

**Comment by raiyni** [comment]
I think it's fine as its own plugin as it's more of a camera orchestrator instead of spots to switch back and forth between.

**Comment by raiyni** [comment]
If you can add an indicator the chat message came from your plugin, will be good to go. eg prepending the message with a highlighted [Keyframecamera] or something similar.

**Comment by mlgudi** [comment]
> If you can add an indicator the chat message came from your plugin, will be good to go. eg prepending the message with a highlighted [Keyframecamera] or something similar.

Thanks! I've now added the message prefix.

**Comment by mlgudi** [comment]
Unsure of the etiquette on bumping PRs, but it has been a while so... Bump! Any chance this could get merged?

**Comment by Felanbird** [comment]
The queue for new plugins is very behind right now, you almost never would need to bump a PR on this repo

But it still needs a full proper review before it can be merged

**Pull request merged**
