### PR TITLE
[New Plugin] Add Easy Mixology plugin

### PR DESCRIPTION
**Pull request by VM9797**
A plugin which highlights most actions at the mixing mixology minigame, making it a laid back experience.

### CODE REVIEW

**Comment by VM9797** [comment]
Updated to version 1.1.0 adding agitator and alembic speed-up highlight, added target potion selection strategy configuration

**Comment by VM9797** [comment]
Updated to version 1.2.0, adding overlay box with information, low level hopper warning and more customizability

**Comment by VM9797** [comment]
Updated to version 1.3.0, adding infobox highlight for speedup actions and digweed detection

**Comment by hex-agon** [comment]
Hey, let's collaborate over https://github.com/hex-agon/mastering-mixology, i'll be porting the features you created in yours to it

**Comment by VM9797** [comment]
> Hey, let's collaborate over https://github.com/hex-agon/mastering-mixology, i'll be porting the features you created in yours to it

I would do it the other way around, I would like to keep maintaining my plugin

**Pull request closed without merging**
